### ISSUE TITLE
Facing ASAN:DEADLYSIGNAL AddressSanitizer: stack-overflow

### ISSUE THREAD

**Issue by srajan3012** [google/sanitizers#1005]
Hi

I am using gcc-7.3.0 to compile a binary and link with libasan.so.4 
CFLAGS :  -fsanitize=address -fsanitize-recover=address -fno-omit-frame-pointer
LDFLAGS: -fsanitize=address

Everything goes fine, but when I run the binary the following error shows up:

```
ASAN:DEADLYSIGNAL
=================================================================
==26809==ERROR: AddressSanitizer: stack-overflow on address 0x7ffd42628fe0 (pc 0x7fb9c31e90fe bp 0x000000000000 sp 0x7ffd42628fe0 T0)

```
It seems that it is going in an infinite loop. My function foo() calls getenv() which leads to the never ending loop. Below is the call stack trace from gdb.

```
#195950 0x00007ffff3de65e5 in _dlerror_run () from /lib64/libdl.so.2
#195951 0x00007ffff3de6128 in dlsym () from /lib64/libdl.so.2
#195952 0x000000001268c2d3 in free ()
#195953 0x00007ffff3de65e5 in _dlerror_run () from /lib64/libdl.so.2
#195954 0x00007ffff3de6128 in dlsym () from /lib64/libdl.so.2
#195955 0x000000001268c2d3 in free ()
#195956 0x00007ffff3de65e5 in _dlerror_run () from /lib64/libdl.so.2
#195957 0x00007ffff3de6128 in dlsym () from /lib64/libdl.so.2
#195958 0x000000001268c2d3 in free ()
#195959 0x00007ffff3de65e5 in _dlerror_run () from /lib64/libdl.so.2
#195960 0x00007ffff3de6128 in dlsym () from /lib64/libdl.so.2
#195961 0x000000001268c474 in getenv()
#195962 0x0000000003f3aeab in foo()
```
How can I overcome this. Any help is appreciated.
Thanks.

**Comment by kcc** [comment]
I don't think we've seen this before. 
Some suggestions: 

* try removing  -fsanitize-recover=address
* try using a newer gcc or clang
* try creating a minimized reproducer and sending it here

**Comment by chefmax** [comment]
@srajan3012 Can you also provide libc version on your system?

**Comment by srajan3012** [comment]
@chefmax GNU libc version: 2.17

**Comment by chefmax** [comment]
Hm, afaik ASan doesn't intercept `getenv` so the fact that address of `free` is close to `getenv` looks suspicious. @srajan3012 can you please:
* Provide full compile/link flags four your binary
* Print current mapping in GDB
?

**Comment by srajan3012** [comment]
These are the flags used:
> CCFLAGS :  -fno-omit-frame-pointer -fsanitize-recover=address -fsanitize=address -fno-ipa-cp-clone -fno-lifetime-dse -fstack-reuse=none -fno-omit-frame-pointer -fno-strict-aliasing -fno-shrink-wrap -frecord-gcc-switches
> LDFLAG: -fsanitize=addressAfter some digging it seems that the reason may be order of linking of libraries.
`libasan.so` is above `libc.so` in my ldd output; Perhaps `libasan.so` contains a wrapper over `free()` function and that wrapper has a call to `dlsym ()`



Below code is a wrapper over free(). This is exported as wrapper.so
In this, dlsym should use free() from linked lib libc.so at runtime.
```
void free(void* p) {
  printf("custom free function\n");
  void (*origFree)(void*) = dlsym(RTLD_NEXT,"free");
  printf("custom free called ");
  origFree(p);
}
```
However, if in the linking order, this wrapper.so is above libc.so we get 

```
#14031 0x00007ffff76638c9 in printf () from /lib64/libc.so.6
#14032 0x00007ffff7bd97f3 in free () from ./libWrap.so
#14033 0x00007ffff7659281 in vfprintf () from /lib64/libc.so.6
#14034 0x00007ffff76638c9 in printf () from /lib64/libc.so.6
#14035 0x00007ffff7bd97f3 in free () from ./libWrap.so
#14036 0x00007ffff7659281 in vfprintf () from /lib64/libc.so.6
#14037 0x00007ffff76638c9 in printf () from /lib64/libc.so.6
#14038 0x00007ffff7bd97f3 in free () from ./libWrap.so
#14039 0x00007ffff7659281 in vfprintf () from /lib64/libc.so.6
#14040 0x00007ffff76638c9 in printf () from /lib64/libc.so.6
#14041 0x00000000004007a8 in main ()
```
How can I get current mapping if GDB?

**Comment by chefmax** [comment]
> After some digging it seems that the reason may be order of linking of libraries.
libasan.so is above libc.so in my ldd output; Perhaps libasan.so contains a wrapper over free() function and that wrapper has a call to dlsym ()

Yes, libasan has its own `free` (and `malloc` and other stuff) that **must** come before libc.

> How can I get current mapping in GDB?

Just run `info proc mappings ` in GDB.

**Comment by srajan3012** [comment]
@chefmax 
```
Mapped address spaces:

          Start Addr           End Addr       Size     Offset objfile
            0x400000         0x16ff7000 0x16bf7000        0x0 MASKED_PATH_LOCAL/bin/my_binary
          0x171f6000         0x1735f000   0x169000 0x16bf6000 MASKED_PATH_LOCAL/bin/my_binary
          0x1735f000         0x173ea000    0x8b000 0x16d5f000 MASKED_PATH_LOCAL/bin/my_binary
          0x173ea000         0x17439000    0x4f000        0x0 [heap]
          0x7fff7000         0x8fff7000 0x10000000        0x0
          0x8fff7000      0x2008fff7000 0x20000000000     0x0
       0x2008fff7000     0x10007fff8000 0xdfff0001000     0x0
      0x600000000000     0x607000000000 0x7000000000      0x0
      0x607000000000     0x607000010000    0x10000        0x0
      0x607000010000     0x607e00000000 0xdffff0000       0x0
      0x607e00000000     0x607e00010000    0x10000        0x0
      0x607e00010000     0x640000000000 0x381ffff0000     0x0
      0x640000000000     0x640000003000     0x3000        0x0
      0x7fffef800000     0x7fffef900000   0x100000        0x0
      0x7fffefa00000     0x7fffefb00000   0x100000        0x0
      0x7fffefc00000     0x7fffefd00000   0x100000        0x0
      0x7fffefe00000     0x7fffeff00000   0x100000        0x0
      0x7ffff0000000     0x7ffff0100000   0x100000        0x0
      0x7ffff016e000     0x7ffff24c0000  0x2352000        0x0
      0x7ffff24c0000     0x7ffff24d5000    0x15000        0x0 /usr/lib64/libgcc_s-4.8.5-20150702.so.1
      0x7ffff24d5000     0x7ffff26d4000   0x1ff000    0x15000 /usr/lib64/libgcc_s-4.8.5-20150702.so.1
      0x7ffff26d4000     0x7ffff26d5000     0x1000    0x14000 /usr/lib64/libgcc_s-4.8.5-20150702.so.1
      0x7ffff26d5000     0x7ffff26d6000     0x1000    0x15000 /usr/lib64/libgcc_s-4.8.5-20150702.so.1
      0x7ffff26d6000     0x7ffff27bf000    0xe9000        0x0 /usr/lib64/libstdc++.so.6.0.19
      0x7ffff27bf000     0x7ffff29bf000   0x200000    0xe9000 /usr/lib64/libstdc++.so.6.0.19
      0x7ffff29bf000     0x7ffff29c7000     0x8000    0xe9000 /usr/lib64/libstdc++.so.6.0.19
      0x7ffff29c7000     0x7ffff29c9000     0x2000    0xf1000 /usr/lib64/libstdc++.so.6.0.19
      0x7ffff29c9000     0x7ffff29de000    0x15000        0x0
      0x7ffff29de000     0x7ffff2b96000   0x1b8000        0x0 /usr/lib64/libc-2.17.so
      0x7ffff2b96000     0x7ffff2d96000   0x200000   0x1b8000 /usr/lib64/libc-2.17.so
      0x7ffff2d96000     0x7ffff2d9a000     0x4000   0x1b8000 /usr/lib64/libc-2.17.so
      0x7ffff2d9a000     0x7ffff2d9c000     0x2000   0x1bc000 /usr/lib64/libc-2.17.so
      0x7ffff2d9c000     0x7ffff2da1000     0x5000        0x0
      0x7ffff2da1000     0x7ffff2db7000    0x16000        0x0 /usr/lib64/libresolv-2.17.so
      0x7ffff2db7000     0x7ffff2fb7000   0x200000    0x16000 /usr/lib64/libresolv-2.17.so
      0x7ffff2fb7000     0x7ffff2fb8000     0x1000    0x16000 /usr/lib64/libresolv-2.17.so
      0x7ffff2fb8000     0x7ffff2fb9000     0x1000    0x17000 /usr/lib64/libresolv-2.17.so
      0x7ffff2fb9000     0x7ffff2fbb000     0x2000        0x0
      0x7ffff2fbb000     0x7ffff2fd1000    0x16000        0x0 /usr/lib64/libnsl-2.17.so
      0x7ffff2fd1000     0x7ffff31d0000   0x1ff000    0x16000 /usr/lib64/libnsl-2.17.so
      0x7ffff31d0000     0x7ffff31d1000     0x1000    0x15000 /usr/lib64/libnsl-2.17.so
      0x7ffff31d1000     0x7ffff31d2000     0x1000    0x16000 /usr/lib64/libnsl-2.17.so
      0x7ffff31d2000     0x7ffff31d4000     0x2000        0x0
      0x7ffff31d4000     0x7ffff31eb000    0x17000        0x0 /usr/lib64/libpthread-2.17.so
      0x7ffff31eb000     0x7ffff33ea000   0x1ff000    0x17000 /usr/lib64/libpthread-2.17.so
      0x7ffff33ea000     0x7ffff33eb000     0x1000    0x16000 /usr/lib64/libpthread-2.17.so
      0x7ffff33eb000     0x7ffff33ec000     0x1000    0x17000 /usr/lib64/libpthread-2.17.so
      0x7ffff33ec000     0x7ffff33f0000     0x4000        0x0
      0x7ffff33f0000     0x7ffff34f1000   0x101000        0x0 /usr/lib64/libm-2.17.so
      0x7ffff34f1000     0x7ffff36f0000   0x1ff000   0x101000 /usr/lib64/libm-2.17.so
      0x7ffff36f0000     0x7ffff36f1000     0x1000   0x100000 /usr/lib64/libm-2.17.so
      0x7ffff36f1000     0x7ffff36f2000     0x1000   0x101000 /usr/lib64/libm-2.17.so
      0x7ffff36f2000     0x7ffff36f4000     0x2000        0x0 /usr/lib64/libdl-2.17.so
      0x7ffff36f4000     0x7ffff38f4000   0x200000     0x2000 /usr/lib64/libdl-2.17.so
      0x7ffff38f4000     0x7ffff38f5000     0x1000     0x2000 /usr/lib64/libdl-2.17.so
      0x7ffff38f5000     0x7ffff38f6000     0x1000     0x3000 /usr/lib64/libdl-2.17.so
      0x7ffff38f6000     0x7ffff3b69000   0x273000        0x0 /MASKED_PATH/lib/libxyz1.so
      0x7ffff3b69000     0x7ffff3d68000   0x1ff000   0x273000 /MASKED_PATH/lib/libxyz1.so
      0x7ffff3d68000     0x7ffff3d69000     0x1000   0x272000 /MASKED_PATH/lib/libxyz1.so
      0x7ffff3d69000     0x7ffff3d6c000     0x3000   0x273000 /MASKED_PATH/lib/libxyz1.so
      0x7ffff3d6c000     0x7ffff3d6f000     0x3000        0x0
      0x7ffff3d6f000     0x7ffff3dce000    0x5f000        0x0 /MASKED_PATH/lib/libxyz2.so
      0x7ffff3dce000     0x7ffff3fcd000   0x1ff000    0x5f000 /MASKED_PATH/lib/libxyz2.so
      0x7ffff3fcd000     0x7ffff3fce000     0x1000    0x5e000 /MASKED_PATH/lib/libxyz2.so
      0x7ffff3fce000     0x7ffff3fcf000     0x1000    0x5f000 /MASKED_PATH/lib/libxyz2.so
      0x7ffff3fcf000     0x7ffff3fd1000     0x2000        0x0
      0x7ffff3fd1000     0x7ffff4023000    0x52000        0x0 /MASKED_PATH/lib/libxyz3.so
      0x7ffff4023000     0x7ffff4223000   0x200000    0x52000 /MASKED_PATH/lib/libxyz3.so
      0x7ffff4223000     0x7ffff4224000     0x1000    0x52000 /MASKED_PATH/lib/libxyz3.so
      0x7ffff4224000     0x7ffff4225000     0x1000    0x53000 /MASKED_PATH/lib/libxyz3.so
      0x7ffff4225000     0x7ffff4226000     0x1000        0x0 /usr/lib64/libaio.so.1.0.1
      0x7ffff4226000     0x7ffff4425000   0x1ff000     0x1000 /usr/lib64/libaio.so.1.0.1
      0x7ffff4425000     0x7ffff4426000     0x1000        0x0 /usr/lib64/libaio.so.1.0.1
      0x7ffff4426000     0x7ffff4427000     0x1000     0x1000 /usr/lib64/libaio.so.1.0.1
      0x7ffff4427000     0x7ffff4446000    0x1f000        0x0 /MASKED_PATH/lib/libxyz3.so
      0x7ffff4446000     0x7ffff4646000   0x200000    0x1f000 /MASKED_PATH/lib/libxyz3.so
      0x7ffff4646000     0x7ffff4647000     0x1000    0x1f000 /MASKED_PATH/lib/libxyz3.so
      0x7ffff4647000     0x7ffff4648000     0x1000    0x20000 /MASKED_PATH/lib/libxyz3.so
      0x7ffff4648000     0x7ffff4746000    0xfe000        0x0 /MASKED_PATH/lib/libxyz4.so
      0x7ffff4746000     0x7ffff4946000   0x200000    0xfe000 /MASKED_PATH/lib/libxyz4.so
      0x7ffff4946000     0x7ffff4947000     0x1000    0xfe000 /MASKED_PATH/lib/libxyz4.so
      0x7ffff4947000     0x7ffff4948000     0x1000    0xff000 /MASKED_PATH/lib/libxyz4.so
      0x7ffff4948000     0x7ffff4a67000   0x11f000        0x0 /MASKED_PATH/lib/libxyz5.so
      0x7ffff4a67000     0x7ffff4c67000   0x200000   0x11f000 /MASKED_PATH/lib/libxyz5.so
      0x7ffff4c67000     0x7ffff4c68000     0x1000   0x11f000 /MASKED_PATH/lib/libxyz5.so
      0x7ffff4c68000     0x7ffff4c69000     0x1000   0x120000 /MASKED_PATH/lib/libxyz5.so
      0x7ffff4c69000     0x7ffff4c6a000     0x1000        0x0
      0x7ffff4c6a000     0x7ffff4c6c000     0x2000        0x0 /MASKED_PATH/lib/libxyz6.so
      0x7ffff4c6c000     0x7ffff4e6b000   0x1ff000     0x2000 /MASKED_PATH/lib/libxyz6.so
      0x7ffff4e6b000     0x7ffff4e6c000     0x1000     0x1000 /MASKED_PATH/lib/libxyz6.so
      0x7ffff4e6c000     0x7ffff4e6d000     0x1000     0x2000 /MASKED_PATH/lib/libxyz6.so
      0x7ffff4e6d000     0x7ffff5920000   0xab3000        0x0 /MASKED_PATH/lib/libxyz7.so
      0x7ffff5920000     0x7ffff5b1f000   0x1ff000   0xab3000 /MASKED_PATH/lib/libxyz7.so
      0x7ffff5b1f000     0x7ffff5b39000    0x1a000   0xab2000 /MASKED_PATH/lib/libxyz7.so
      0x7ffff5b39000     0x7ffff5b40000     0x7000   0xacc000 /MASKED_PATH/lib/libxyz7.so
      0x7ffff5b40000     0x7ffff5b45000     0x5000        0x0
      0x7ffff5b45000     0x7ffff5b71000    0x2c000        0x0 /MASKED_PATH/lib/libxyz8.so
      0x7ffff5b71000     0x7ffff5d70000   0x1ff000    0x2c000 /MASKED_PATH/lib/libxyz8.so
      0x7ffff5d70000     0x7ffff5d71000     0x1000    0x2b000 /MASKED_PATH/lib/libxyz8.so
      0x7ffff5d71000     0x7ffff5d72000     0x1000    0x2c000 /MASKED_PATH/lib/libxyz8.so
      0x7ffff5d72000     0x7ffff5daa000    0x38000        0x0 /MASKED_PATH/lib/libxyz9.so
      0x7ffff5daa000     0x7ffff5fa9000   0x1ff000    0x38000 /MASKED_PATH/lib/libxyz9.so
      0x7ffff5fa9000     0x7ffff5faa000     0x1000    0x37000 /MASKED_PATH/lib/libxyz9.so
      0x7ffff5faa000     0x7ffff5fab000     0x1000    0x38000 /MASKED_PATH/lib/libxyz9.so
      0x7ffff5fab000     0x7ffff5fb2000     0x7000        0x0 /usr/lib64/librt-2.17.so
      0x7ffff5fb2000     0x7ffff61b1000   0x1ff000     0x7000 /usr/lib64/librt-2.17.so
      0x7ffff61b1000     0x7ffff61b2000     0x1000     0x6000 /usr/lib64/librt-2.17.so
      0x7ffff61b2000     0x7ffff61b3000     0x1000     0x7000 /usr/lib64/librt-2.17.so
      0x7ffff61b3000     0x7ffff61fa000    0x47000        0x0 /MASKED_PATH/lib/libxyz10.so
      0x7ffff61fa000     0x7ffff63f9000   0x1ff000    0x47000 /MASKED_PATH/lib/libxyz10.so
      0x7ffff63f9000     0x7ffff63fb000     0x2000    0x46000 /MASKED_PATH/lib/libxyz10.so
      0x7ffff63fb000     0x7ffff63fc000     0x1000    0x48000 /MASKED_PATH/lib/libxyz10.so
      0x7ffff63fc000     0x7ffff6512000   0x116000        0x0 /MASKED_PATH/lib/libxyz11.so
      0x7ffff6512000     0x7ffff6711000   0x1ff000   0x116000 /MASKED_PATH/lib/libxyz11.so
      0x7ffff6711000     0x7ffff6712000     0x1000   0x115000 /MASKED_PATH/lib/libxyz11.so
      0x7ffff6712000     0x7ffff6713000     0x1000   0x116000 /MASKED_PATH/lib/libxyz11.so
      0x7ffff6713000     0x7ffff6809000    0xf6000        0x0 /MASKED_PATH/lib/libxyz12.so
      0x7ffff6809000     0x7ffff6a08000   0x1ff000    0xf6000 /MASKED_PATH/lib/libxyz12.so
      0x7ffff6a08000     0x7ffff6a0c000     0x4000    0xf5000 /MASKED_PATH/lib/libxyz12.so
      0x7ffff6a0c000     0x7ffff6a1f000    0x13000    0xf9000 /MASKED_PATH/lib/libxyz12.so
      0x7ffff6a1f000     0x7ffff6a20000     0x1000        0x0
      0x7ffff6a20000     0x7ffff6a21000     0x1000        0x0 /MASKED_PATH/lib/libxyz13.so
      0x7ffff6a21000     0x7ffff6c20000   0x1ff000     0x1000 /MASKED_PATH/lib/libxyz13.so
      0x7ffff6c20000     0x7ffff6c21000     0x1000        0x0 /MASKED_PATH/lib/libxyz13.so
      0x7ffff6c21000     0x7ffff6c22000     0x1000     0x1000 /MASKED_PATH/lib/libxyz13.so
      0x7ffff6c22000     0x7ffff6c24000     0x2000        0x0 /MASKED_PATH/lib/libxyz14.so
      0x7ffff6c24000     0x7ffff6e23000   0x1ff000     0x2000 /MASKED_PATH/lib/libxyz14.so
      0x7ffff6e23000     0x7ffff6e24000     0x1000     0x1000 /MASKED_PATH/lib/libxyz14.so
      0x7ffff6e24000     0x7ffff6e25000     0x1000     0x2000 /MASKED_PATH/lib/libxyz14.so
      0x7ffff6e25000     0x7ffff6f6f000   0x14a000        0x0 /MASKED_PATH_LOCAL/lib/libasan.so
      0x7ffff6f6f000     0x7ffff716f000   0x200000   0x14a000 /MASKED_PATH_LOCAL/lib/libasan.so
      0x7ffff716f000     0x7ffff7176000     0x7000   0x14a000 /MASKED_PATH_LOCAL/lib/libasan.so
      0x7ffff7176000     0x7ffff7ddb000   0xc65000        0x0
      0x7ffff7ddb000     0x7ffff7dfc000    0x21000        0x0 /usr/lib64/ld-2.17.so
      0x7ffff7ea4000     0x7ffff7fcd000   0x129000        0x0
      0x7ffff7fcd000     0x7ffff7ff7000    0x2a000        0x0
      0x7ffff7ff7000     0x7ffff7ffa000     0x3000        0x0 [vvar]
      0x7ffff7ffa000     0x7ffff7ffc000     0x2000        0x0 [vdso]
      0x7ffff7ffc000     0x7ffff7ffd000     0x1000    0x21000 /usr/lib64/ld-2.17.so
      0x7ffff7ffd000     0x7ffff7ffe000     0x1000    0x22000 /usr/lib64/ld-2.17.so
      0x7ffff7ffe000     0x7ffff7fff000     0x1000        0x0
      0x7fffff7ff000     0x7ffffffff000   0x800000        0x0
  0xffffffffff600000 0xffffffffff601000     0x1000        0x0 [vsyscall]

```

**Comment by yugr** [comment]
> Perhaps libasan.so contains a wrapper over free() function and that wrapper has a call to dlsym ()

@chefmax 

There is a special hack to avoid calling system `malloc` from `dlsym` at startup (see `ReallocFromLocalPool` in `asan_malloc_linux.cc`). It seems it tries to call `dlsym` for some reason...

**Comment by yugr** [comment]
@srajan3012 I think you are running under ASLR because addresses in GDB do not match addresses in backtrace.

**Comment by srajan3012** [comment]
oh..I am new to C and gdb..
Do I need to run without ASLR? If yes, how can I do so?
