### ISSUE TITLE
ASAN: initialization failure on Android

### ISSUE THREAD

**Issue by alek314** [google/sanitizers#1023]
In the function call InitializeAsanCommonInterceptors(), the following check failed:
"((__interception::real_memcpy)) != (0)"
NDK version is r16b with gnustl-static, Android 8.0, using wrap.sh approach.
getenforce shows "PERMISSIVE"

After update to NDK r18b, with -DANDROID_STL=c++_static,  the crashed stack changed:
__cxa_atexit
unknown>
unknown>
__dl__ZL13call_functionPKcPFviPPcS2_ES0
__dl__ZL10call_arrayIPFviPPcS1_EEvPKcPT_jbS5_
__dl__ZN6soinfo17call_constructorsEV
__dl__ZN6soinfo17call_constructorsEV
__dl__Z9do_dlopenPKciPK17android_dlextinfoPKv
__dl__ZL10dlopen_extPKciPK17android_dlextinfoPKv
android_dlopen_ext
android::OpenNativeLibrary

Any idea? thank you

**Comment by alek314** [comment]
Eugenis, you are right.
I am using Android Studio for development, and I manually put the wrap.sh script right next to asan-arm-android.so, in the jniLibs/armeabi-v7a folder. But wrap.sh did not made it's way to the APK.

**Comment by alek314** [comment]
After putting wrap.sh into folder app/resources/lib/armeabi-v7a, wrap.sh is properly packaged along side asan.so. When the app start, the following error occured:

 939   939 I zygote  : Ignoring open file descriptor 3
 939   939 I zygote  : Ignoring open file descriptor 4
7409  7409 I zygote  : Late-enabling -Xcheck:jni
7409  7409 W zygote  : Using default instruction set features for ARM CPU variant (cortex-a9) using conservative defaults
7421  7421 I wrap.sh : executing /data/app/com.dy3d-MRYVTaN0O7_J5V3ARv77hA==/lib/arm/wrap.sh failed: No such file or directory
7422  7422 E logwrapper: executing /data/app/com.dy3d-MRYVTaN0O7_J5V3ARv77hA==/lib/arm/wrap.sh failed: No such file or directory
7421  7421 I wrap.sh : wrap.sh terminated by exit(255)
 939   939 I Zygote  : Process 7409 exited cleanly (255)
 939   939 W Zygote  : Error reading pid from wrapped process, child may have died
 939   939 W Zygote  : java.io.EOFException
 939   939 W Zygote  :      at java.io.DataInputStream.readFully(DataInputStream.java:200)
 939   939 W Zygote  :      at java.io.DataInputStream.readInt(DataInputStream.java:389)
 939   939 W Zygote  :      at com.android.internal.os.ZygoteConnection.handleParentProc(ZygoteConnection.java:858)
 939   939 W Zygote  :      at com.android.internal.os.ZygoteConnection.runOnce(ZygoteConnection.java:267)
 939   939 W Zygote  :      at com.android.internal.os.ZygoteServer.runSelectLoop(ZygoteServer.java:164)
 939   939 W Zygote  :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
