### ISSUE TITLE
False-positive on memory allocated by strdup in shared library constructor

### ISSUE THREAD

**Issue by matlo** [google/sanitizers#1029]
Hello,

I am facing what I believe to be a false positive. See attached sample.

[abc.tar.gz](https://github.com/google/sanitizers/files/2636341/abc.tar.gz)

```
matlo@matlo-desktop /tmp $ tar xvf abc.tar.gz 
abc/
abc/a.c
abc/b.c
abc/c.c
abc/run.sh
matlo@matlo-desktop /tmp $ cd abc/
matlo@matlo-desktop /tmp/abc $ ./run.sh 
+ cc -fPIC -Wall -Wextra -g -O0 -shared -o liba.so a.c
+ cc -fPIC -Wall -Wextra -g -O0 -L. -shared -o libb.so b.c -la
+ cc -Wall -Wextra -fsanitize=address -fno-omit-frame-pointer -g -O0 -c -o c.o c.c
+ cc -L. c.o -lasan -la -lb -o c
+ LD_LIBRARY_PATH=.
+ ./c
./c
=================================================================
==24886==ERROR: AddressSanitizer: attempting free on address which was not malloc()-ed: 0x7fc7f67003d8 in thread T0
    #0 0x7fc7f7cc97b8 in __interceptor_free (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xde7b8)
    #1 0x7fc7f6815717 in a_destructor /tmp/abc/a.c:13
    #2 0x7fc7f8bb6b72  (/lib64/ld-linux-x86-64.so.2+0x10b72)
    #3 0x7fc7f763b040  (/lib/x86_64-linux-gnu/libc.so.6+0x43040)
    #4 0x7fc7f763b139 in exit (/lib/x86_64-linux-gnu/libc.so.6+0x43139)
    #5 0x7fc7f7619b9d in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b9d)
    #6 0x5629ed4107d9 in _start (/tmp/abc/c+0x7d9)

Address 0x7fc7f67003d8 is a wild pointer.
SUMMARY: AddressSanitizer: bad-free (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xde7b8) in __interceptor_free
==24886==ABORTING
```
The error disappears if I replace strdup in a.c with memcpy+strcpy.

**Comment by eugenis** [comment]
-lasan is wrong. Add -fsanitize=address to link flags instead.

**Comment by matlo** [comment]
Thanks!
