### ISSUE TITLE
Memory leak detection not working on GCC 4.8.5

### ISSUE THREAD

**Issue by pfirsich** [google/sanitizers#1065]
Hello, this is not really a bug, since it is fixed in a newer version, but sadly I do not have the option to use a version that is newer than 4.8.5. So I am merely asking if there is any way I could still get it to work.

The test files:
segv.cpp
```cpp
#include <cstdlib>

int main(int argc, char** argv) {
    char* buf = 0;
    buf[0] = 0;
    return 0;
}
```
leak.cpp
```cpp
#include <cstdlib>

int main(int argc, char** argv) {
    char* buf = new char[11];
    buf = 0;
    return 0;
}
```

Using GCC 4.8.5
```
$ g++ --version
g++ (GCC) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ g++ -g -fsanitize=address -fno-omit-frame-pointer -static-libasan -O0 segv.cpp
$ export ASAN_OPTIONS=""
$ ./a.out
ASAN:SIGSEGV
=================================================================
==27106== ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x00000041ac7a sp 0x7ffc9866e800 bp 0x7ffc9866e820 T0)
AddressSanitizer can not provide additional info.
    #0 0x41ac79 (<redacted>/a.out+0x41ac79)
    #1 0x7f2c91a0f6d4 (/lib64/libc-2.22.so+0x206d4)
    #2 0x402408 (<redacted>/a.out+0x402408)
==27106== ABORTING

$ g++ -g -fsanitize=address -fno-omit-frame-pointer -static-libasan -O0 leak.cpp
$ ./a.out
$ export ASAN_OPTIONS="detect_leaks=1"
$ ./a.out
$ export ASAN_OPTIONS="detect_leaks=1:atexit=true"
$ ./a.out
AddressSanitizer exit stats:
Stats: 0M malloced (0M for red zones) by 2 calls
Stats: 0M realloced by 0 calls
Stats: 0M freed by 0 calls
Stats: 0M really freed by 0 calls
Stats: 0M (0M-0M) mmaped; 4 maps, 0 unmaps
  mmaps   by size class: 
  mallocs by size class: 2:1; 82:1; 
  frees   by size class: 
  rfrees  by size class: 
Stats: malloc large: 0 small slow: 0
Stats: StackDepot: 2 ids; 0M mapped
Stats: SizeClassAllocator64: 0M mapped in 285 allocations; remains 285
  02 (32): total: 64 K allocs: 256 remains: 256
  41 (2304): total: 128 K allocs: 28 remains: 28
  82 (81920): total: 192 K allocs: 1 remains: 1
Stats: LargeMmapAllocator: allocated 0 times, remains 0 (0 K) max 0 M; by size logs: 
```

Using GCC 5.2.0
```
$ g++ --version
g++ (GCC) 5.2.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ g++ -g -fsanitize=address -fno-omit-frame-pointer -static-libasan -O0 segv.cpp
$ export ASAN_OPTIONS=""
$ ./a.out
ASAN:SIGSEGV
=================================================================
==27250==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x0000004acff6 bp 0x7ffdbfc638d0 sp 0x7ffdbfc638b0 T0)
    #0 0x4acff5 in main <redacted>/segv.cpp:5
    #1 0x7fd35bf176d4 in __libc_start_main (/lib64/libc.so.6+0x206d4)
    #2 0x4050d8 in _start (<redacted>/a.out+0x4050d8)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV <redacted>/segv.cpp:5 main
==27250==ABORTING

$ g++ -g -fsanitize=address -fno-omit-frame-pointer -static-libasan -O0 leak.cpp
$ ./a.out

=================================================================
==28439==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 11 byte(s) in 1 object(s) allocated from:
    #0 0x47cada in operator new[](unsigned long) <redacted>/asan_new_delete.cc:62
    #1 0x4acfbf in main <redacted>/leak.cpp:4
    #2 0x7f7b960976d4 in __libc_start_main (/lib64/libc.so.6+0x206d4)

SUMMARY: AddressSanitizer: 11 byte(s) leaked in 1 allocation(s).
```

As you can see 4.8.5 does not find memory leaks at all, while segmentation faults are detected (with missing info though).

**Comment by kcc** [comment]
Sorry, I don't think we can help here. 
Being stuck with very old compiler versions is a very sad story.
