### ISSUE TITLE
Mem leak in static member function?

### ISSUE THREAD

**Issue by morris-stock** [google/sanitizers#1070]
```
#include <iostream>

#define TM_DUMP \
    std::cout << __PRETTY_FUNCTION__ << std::endl;

class C
{
public:
    C() {
        TM_DUMP
    }
    ~C() {
        TM_DUMP
    }
};

class D
{
public:
    static C *c;

    static void foo() {
        TM_DUMP
        c = new C;
    }

    D() {
        TM_DUMP
        foo();
    }

    ~D() {
        TM_DUMP
    }
};

C *D::c = nullptr;

D d;

int main(int, char *[])
{
    return 0;
}
```
```
$ clang++ --version
clang version 5.0.1 (tags/RELEASE_501/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rh/llvm-toolset-7/root/usr/bin

$ clang++ leak.cc -g3 -O0 -lasan -std=c++11
$ ./a.out 
D::D()
static void D::foo()
C::C()
D::~D()
```
Shoud this be reported?

**Comment by morehouse** [comment]
This is not a memory leak, since we never lose the pointer to `D::c`.

If you were to modify your `main` to something like this:
```c++
int main()
  D d2;
  return 0;
}
```
Then this would be a leak since the original pointer is lost and the memory wasn't freed:

```shell
$ clang++ leak.cc -fsanitize=leak && ./a.out
D::D()
static void D::foo()
C::C()
D::D()
static void D::foo()
C::C()
D::~D()
D::~D()

=================================================================
==128157==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 1 byte(s) in 1 object(s) allocated from:
    #0 0x424b8f in operator new(unsigned long) /usr/local/google/home/mascasa/code/llvm/llvm-project/compiler-rt/lib/lsan/lsan_interceptors.cc:223:35
    #1 0x426281 in D::foo() (/usr/local/google/home/mascasa/a.out+0x426281)
    #2 0x4261ef in D::D() (/usr/local/google/home/mascasa/a.out+0x4261ef)
    #3 0x403dc6 in __cxx_global_var_init.1 (/usr/local/google/home/mascasa/a.out+0x403dc6)
    #4 0x403e0d in _GLOBAL__sub_I_test.cc (/usr/local/google/home/mascasa/a.out+0x403e0d)
    #5 0x42637c in __libc_csu_init (/usr/local/google/home/mascasa/a.out+0x42637c)

SUMMARY: LeakSanitizer: 1 byte(s) leaked in 1 allocation(s).
```
