### ISSUE TITLE
MSAN_OPTIONS=halt_on_error=0 does not work

### ISSUE THREAD

**Issue by Timmmm** [google/sanitizers#1075]
Observe:

```
$ clang++ --version
clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

(Yeah I know it's a bit old)

$ cat main.cpp
#include <iostream>

void foo(int j) {
	asm("" : : "r" (j));
}

int main(int argc, char* argv[]) {
	int *i = new int;
	foo(*i);
	std::cout << "End\n";
}
$ clang++ main.cpp -o main
$ ./main
End
$ clang++ -fsanitize=memory main.cpp -o main
$ ./main
==53565==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x496f1a in foo(int) (/home/timh/main+0x496f1a)
    #1 0x49702b in main (/home/timh/main+0x49702b)
    #2 0x7f7700080b96 in __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310
    #3 0x41af59 in _start (/home/timh/main+0x41af59)

SUMMARY: MemorySanitizer: use-of-uninitialized-value (/home/timh/main+0x496f1a) in foo(int)
Exiting
$ MSAN_OPTIONS=halt_on_error=0 ./main
==53603==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x496f1a in foo(int) (/home/timh/main+0x496f1a)
    #1 0x49702b in main (/home/timh/main+0x49702b)
    #2 0x7f3fedf2db96 in __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310
    #3 0x41af59 in _start (/home/timh/main+0x41af59)

SUMMARY: MemorySanitizer: use-of-uninitialized-value (/home/timh/main+0x496f1a) in foo(int)
Exiting
```

If I do `MSAN_OPTIONS=halt_on_error=2` it complains that it should be 1 or 0 so it is definitely reading it.

**Comment by ramosian-glider** [comment]
Also reproducible on trunk Clang.

**Comment by yugr** [comment]
I thought you also need to compile with `-mllvm -msan-keep-going=1` (acc. to https://github.com/google/sanitizers/issues/725#issuecomment-251195415).

**Comment by Timmmm** [comment]
Ah maybe. Documentation would help... As would an error like "cannot keep going because -msan-keep-going wasn't enabled"
