### ISSUE TITLE
ASAN on windows empty string literal false positive

### ISSUE THREAD

**Issue by mnicolella** [google/sanitizers#1102]
I am trying to reproduce this in a trivial project but haven't been able to yet.

ASAN (windows x64, llvm release 8.0.0) seems to be complaining about me accessing the null terminating byte of the empty string literal

in main.cpp:
```
int
main(int argc, char **argv)
{
	{
		db_strdup("", "file", 12);
	}
...
```

in malloc.cpp:
```
char *
db_strdup(const char *str, const char *file, int line)
{
	int len = strlen(str);
	char *newStr = (char *)db_malloc(len + 1, file, line);
	strcpy(newStr, str);
	return newStr;
}
```

and asan is complaining on the strlen(str) call.

These excerpts from the error message seem to describe fine behavior:
> READ of size 1 at 0x7ff710b1fe80 thread T0
> 0x7ff710b1fe80 is located 0 bytes inside of global variable '<string literal>' defined in 'bdescribed.cpp:12:34' (0x7ff710b1fe80) of size 1

Is this an issue where the shadow bytes forgot to mark the null terminating byte as readable?

[asan_issue.txt](https://github.com/google/sanitizers/files/3245875/asan_issue.txt)

**Comment by eugenis** [comment]
@rnk This could be a problem with string literal merging between instrumented and non-instrumented translation units.

**Comment by mnicolella** [comment]
According to this line from the asan output:
> 0x7ff710b1fe80 is located 0 bytes inside of global variable '<string literal>' defined in 'bdescribed.cpp:12:34' (0x7ff710b1fe80) of size 1
  '<string literal>' is ascii string ''

bdescribed.cpp is also a source file in my project that *is* instrumented.

**Comment by mnicolella** [comment]
If this is helpful, here's a pruned down version of the verbose report_globals:

```
==17444==AddressSanitizer: failed to intercept 'atol'
==17444==AddressSanitizer: libc interceptors initialized
|| `[0x11b4e5e00000, 0x7fffffffffff]` || HighMem    ||
|| `[0x03eb829c0000, 0x11b4e5dfffff]` || HighShadow ||
|| `[0x01eb829c0000, 0x03eb829bffff]` || ShadowGap  ||
|| `[0x01b4e5e00000, 0x01eb829bffff]` || LowShadow  ||
|| `[0x000000000000, 0x01b4e5dfffff]` || LowMem     ||
MemToShadow(shadow): 0x01eb829c0000 0x01f256337fff 0x023256338000 0x03eb829bffff
redzone=16
max_redzone=2048
quarantine_size_mb=256M
thread_local_quarantine_size_kb=1024K
malloc_context_size=30
SHADOW_SCALE: 3
SHADOW_GRANULARITY: 8
SHADOW_OFFSET: 0x1b4e5e00000
==17444==T0: stack [0x00862d200000,0x00862d300000) size 0x100000; local=0x00862d2fec34
==17444==AddressSanitizer Init done
    #0 0x7ff74ccab5d5 in __asan_register_globals C:\src\llvm_package_800-final\llvm\projects\compiler-rt\lib\asan\asan_globals.cc:373
    #1 0x7ff74ccfa282 in _initterm C:\projects\ratlabs\rlrealm-live\roommgr\minkernel\crts\ucrt\src\appcrt\startup\initterm.cpp:21
    #2 0x7ff74ccf51cc in __scrt_common_main_seh f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:251
    #3 0x7ffc3eab4033 in BaseThreadInitThunk+0x13 (C:\Windows\System32\KERNEL32.DLL+0x180014033)
    #4 0x7ffc40e73690 in RtlUserThreadStart+0x20 (C:\Windows\SYSTEM32\ntdll.dll+0x180073690)

=== ID 2139095041; 0x7ff74cdfdfc0 0x7ff74ce4ef00

...

==17444==Added Global[0x7ff74ce01a80]: beg=0x7ff74cddfe80 size=1/64 name=<string literal> module=bdescribed.cpp dyn_init=0 odr_indicator=0x000000000000
==17444==  location (0x7ff74cd194b0): name=bdescribed.cpp[0x7ff74cd194a1], 12 34

...

==17444==Search Global[0x7ff74ce01a80]: beg=0x7ff74cddfe80 size=1/64 name=<string literal> module=bdescribed.cpp dyn_init=0 odr_indicator=0x000000000000
==17444==  location (0x7ff74cd194b0): name=bdescribed.cpp[0x7ff74cd194a1], 12 34

...

```
