### ISSUE TITLE
==9054==WARNING: AddressSanitizer failed to allocate 0x002bffffffd4 bytes

### ISSUE THREAD

**Issue by cxht** [google/sanitizers#1115]
HI! 
When I run ASAN with a target program, the log shows that
`==9054==WARNING: AddressSanitizer failed to allocate 0x002bffffffd4 bytes
==9054==AddressSanitizer's allocator is terminating the process instead of returning 0
==9054==If you don't like this behavior set allocator_may_return_null=1
==9054==AddressSanitizer CHECK failed: ../../../../src/libsanitizer/sanitizer_common/sanitizer_allocator.cc:147 "((0)) != (0)" (0x0, 0x0)
    #0 0x7ff2c4e6a631  (/usr/lib/x86_64-linux-gnu/libasan.so.2+0xa0631)
    #1 0x7ff2c4e6f5e3 in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) (/usr/lib/x86_64-linux-gnu/libasan.so.2+0xa55e3)
    #2 0x7ff2c4de7425  (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x1d425)
    #3 0x7ff2c4e6d865  (/usr/lib/x86_64-linux-gnu/libasan.so.2+0xa3865)
    #4 0x7ff2c4decb4d  (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x22b4d)
    #5 0x7ff2c4e625d2 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x985d2)
    #6 0x443820 in operator new[](unsigned long) (/home/cx/workspace/target_group/sam2p/sam2p+0x443820)
    #7 0x45153b  (/home/cx/workspace/target_group/sam2p/sam2p+0x45153b)
    #8 0x452495  (/home/cx/workspace/target_group/sam2p/sam2p+0x452495)
    #9 0x549071  (/home/cx/workspace/target_group/sam2p/sam2p+0x549071)
    #10 0x405584  (/home/cx/workspace/target_group/sam2p/sam2p+0x405584)
    #11 0x403259  (/home/cx/workspace/target_group/sam2p/sam2p+0x403259)
    #12 0x7ff2c4a2082f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #13 0x4048d8  (/home/cx/workspace/target_group/sam2p/sam2p+0x4048d8)
`
How to solve this problem?

**Comment by eugenis** [comment]
> 0x002bffffffd4 bytes

That's a lot of bytes.
175GB, to be precise.
Did you really mean to allocate that much?

**Comment by sarora5** [comment]
Yes indeed .. It is heavy app and cannot enable ASAN on that ... Thanks for checking

**Comment by ramosian-glider** [comment]
No response in 5 years from the issue author, closing.
