### ISSUE TITLE
MSAN +  getservbyname()

### ISSUE THREAD

**Issue by kevgs** [google/sanitizers#1138]
Hi.

```c
#include <stdlib.h>
#include <netdb.h>

int main() {
  getservbyname("foo", NULL);
}
```

```
clang -g -fno-omit-frame-pointer -Wall -fsanitize=memory -fPIE -pie 1.c && ./a.out
```

```
Uninitialized bytes in __interceptor_strlen at offset 0 inside [0x718000000000, 49)
==1853==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7fa2ba363cff in _nss_files_parse_servent /build/glibc-KRRWSm/glibc-2.29/nss/nss_files/files-service.c:32:1
    #1 0x7fa2ba363e6c in internal_getent /build/glibc-KRRWSm/glibc-2.29/nss/nss_files/files-XXX.c:182:22
    #2 0x7fa2ba36412e in _nss_files_getservbyname_r /build/glibc-KRRWSm/glibc-2.29/nss/nss_files/files-service.c:41:1
    #3 0x7fa2bb330f12 in getservbyname_r /build/glibc-KRRWSm/glibc-2.29/inet/../nss/getXXbyYY_r.c:315:16
    #4 0x7fa2bb330cb2 in getservbyname /build/glibc-KRRWSm/glibc-2.29/inet/../nss/getXXbyYY.c:135:7
    #5 0x56423b778467 in main /home/kevg/fun/cpp_projects/1.c:5:3
    #6 0x7fa2bb224b6a in __libc_start_main /build/glibc-KRRWSm/glibc-2.29/csu/../csu/libc-start.c:308:16
    #7 0x56423b6ff279 in _start (/home/kevg/fun/cpp_projects/a.out+0x1d279)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /build/glibc-KRRWSm/glibc-2.29/nss/nss_files/files-service.c:32:1 in _nss_files_parse_servent
Exiting
```

I'd like to use `getservbyname()` with MSAN. Am I understand correct that it is missing interceptor? Or could this be a bug inside GNU libc?

**Comment by eugenis** [comment]
Yes, a missing interceptor. I don't see a source level workaround for this,
unfortunately.

**Comment by kevgs** [comment]
Thanks for your answer!
You mean my source code or it's not possible to add such interceptor to `compiler-rt`?

**Comment by eugenis** [comment]
Your source code. Adding an interceptor would not be hard at all, but
I'm swamped at the moment.

**Comment by georgthegreat** [comment]
@eugenis, could you, please give an update on the subject?
