### ISSUE TITLE
TSAN: strange warnings with boost::coroutines2

### ISSUE THREAD

**Issue by diameter** [google/sanitizers#1150]
Hi! I'm encountering strange TSAN warnings. It seems like TSAN reports on itself

```WARNING: ThreadSanitizer: data race (pid=9885)
  Write of size 8 at 0x7fff7eeafc28 by thread T42:
    #0 sigfillset <null> (libtsan.so.0+0x4cd84)
    #1 <null> <null> (libunwind.so.8+0x5e58)
    #2 boost::context::fiber::resume() && /usr/local/tatlin/include/boost/context/fiber_fcontext.hpp:288 
    #3 boost::coroutines2::detail::push_coroutine<void>::control_block::resume() /usr/local/tatlin/include/boost/coroutine2/detail/push_control_block_cc.ipp:385 
...
  Previous write of size 8 at 0x7fff7eeafc28 by thread T45:
    #0 sigfillset <null> (libtsan.so.0+0x4cd84)
    #1 <null> <null> (libunwind.so.8+0x5e58)
    #2 boost::context::fiber::resume() && /usr/local/tatlin/include/boost/context/fiber_fcontext.hpp:288 
    #3 boost::coroutines2::detail::push_coroutine<void>::control_block::resume() /usr/local/tatlin/include/boost/coroutine2/detail/push_control_block_cc.ipp:385 
```

Questionable instances of boost::coroutines2::coroutine<void> are totally different, I can't understand how access to them can cause data races.

If I run the program in gdb, I get this:
```
Thread 228 "zzz" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff87b7f420 (LWP 17893)]
0x00007fffb70c1c54 in __tsan_func_entry () from /usr/lib64/libtsan.so.0
(gdb) bt
#0  0x00007fffb70c1c54 in __tsan_func_entry () from /usr/lib64/libtsan.so.0
#1  0x000000001063d21c in std::thread::_State_impl<std::thread::_Invoker<std::tuple<std::__future_base::_Async_state_impl<std::thread::_Invoker<std::tuple<EventLoopImpl::run(std::shared_ptr<EventLoop> const&, int)::{lambda()#1}> >, int>::_Async_state_impl(std::tuple<Event
LoopImpl::run(std::shared_ptr<EventLoop> const&, int)::{lambda()#1}>&&)::{lambda()#1}> > >::~_State_impl() (this=0x7fffb1302200, __in_chrg=<optimized out>) at /usr/include/c++/8/thread:188
#2  0x00007fffb6b0b990 in ?? () from /usr/lib64/libstdc++.so.6
#3  0x00007fffb705017c in ?? () from /usr/lib64/libtsan.so.0
#4  0x00007fffb68585e4 in start_thread () from /lib64/libpthread.so.0
#5  0x00007fffb6766568 in clone () from /lib64/libc.so.6
```

That's gcc8 on ppc64le
```
Information for package libtsan0:
---------------------------------
Repository     : SLE-Module-Basesystem-Updates
Name           : libtsan0
Version        : 8.2.1+r264010-1.3.7
Arch           : ppc64le
Vendor         : SUSE LLC <https://www.suse.com/>
Support Level  : Level 3
Installed Size : 1.2 MiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : gcc8-8.2.1+r264010-1.3.7.src
Summary        : The GNU Compiler Thread Sanitizer Runtime Library
```

**Comment by dvyukov** [comment]
What do these folks do:
    #2 boost::context::fiber::resume() && /usr/local/tatlin/include/boost/context/fiber_fcontext.hpp:288 
    #3 boost::coroutines2::detail::push_coroutine<void>::control_block::resume() /usr/local/tatlin/include/boost/coroutine2/detail/push_control_block_cc.ipp:385
?

The problem may be with non-instrumented libunwind.so, tsan may not see some synchronization hap penning there. Maybe suppressing it with `called_from_lib`:
https://github.com/google/sanitizers/wiki/ThreadSanitizerSuppressions
will help.

**Comment by diameter** [comment]
boost/context/fiber_fcontext.hpp:
```
280     fiber resume() && {
281         BOOST_ASSERT( nullptr != fctx_);
282         return { detail::jump_fcontext(
283 #if defined(BOOST_NO_CXX14_STD_EXCHANGE)
284                     detail::exchange( fctx_, nullptr),
285 #else
286                     std::exchange( fctx_, nullptr),
287 #endif
288                     nullptr).fctx };
289     }
```
boost/coroutine2/detail/push_control_block_cc.ipp:
```
382 inline
383 void
384 push_coroutine< void >::control_block::resume() {
385     c = std::move( c).resume();
386     if ( except) {
387         std::rethrow_exception( except);
388     }
389 }
```

I've added "called_from_lib:libunwind.so" suppression -- it didn't help, the SEGV is still there. Trying to reproduce the warning.

**Comment by diameter** [comment]
you are right, the problems are independent, but it was worth a shot.

**Comment by dvyukov** [comment]
Does the suppression affect the race?

**Comment by diameter** [comment]
So far I can't reproduce the race warnings anymore, the suppression really helped.

But, this only works with optimised (release) build of the program, debug build always fails with SEGFAULT in __tsan_func_entry (), I can't reproduce the race because of this.

**Comment by dvyukov** [comment]
Hard to say what happens with __tsan_func_entry.
Running clang may help b/c it contains debug symbols, so at least we will see line numbers and ensure that the problem is not fixed on head.
However, fibers/coroutines are not officially supported by tsan at the moment. So the end result may be that, yes, it's just not supported.
Tsan now has fibers API:
https://github.com/llvm-mirror/compiler-rt/blob/master/include/sanitizer/tsan_interface.h#L139-L151
but it requires manual annotations in the fibers runtime, which is not done for boost.
