### ISSUE TITLE
g++: error: unrecognized command line option '-shared-libasan'

### ISSUE THREAD

**Issue by hbsun2113** [google/sanitizers#1169]
I add ```-fsanitize=address -shared-libasan``` to my makefile(because I want to get a .so file) and meet the following problem:
![image](https://user-images.githubusercontent.com/27994442/69697306-1018b580-111d-11ea-9938-7c2c664d6b24.png)
![image](https://user-images.githubusercontent.com/27994442/69697342-2161c200-111d-11ea-86a5-e98dbac2a4b6.png)

My g++ version is:
![image](https://user-images.githubusercontent.com/27994442/69697234-e1024400-111c-11ea-8ef4-e7b7163fe95c.png)
Can anyone help me?

**Comment by mrichtarsky** [comment]
That option is only relevant for clang, where static ASan runtime is default. For gcc shared already is default and you can just remove it.

**Comment by hbsun2113** [comment]
> That option is only relevant for clang, where static ASan runtime is default. For gcc shared already is default and you can just remove it.

Now my profile is following:
![image](https://user-images.githubusercontent.com/27994442/69699687-8ae4cf00-1123-11ea-890c-50641ca760d9.png)

But I meet the following running error:
![image](https://user-images.githubusercontent.com/27994442/69699717-989a5480-1123-11ea-938a-c9bed34e21ac.png)

**Comment by yugr** [comment]
Please provide full compile, link and run commands (better plain text rather than screeshots).

**Comment by hbsun2113** [comment]
My ps_Makefile is:
```
$(info "ps start")
ifdef config
$(info "isconfig")
include $(config)
endif

include make/ps.mk
ifndef CXX
CXX = g++
endif
$(info "CXX = " $(CXX))

ifndef DEPS_PATH
DEPS_PATH = $(shell pwd)/deps
endif


ifndef PROTOC
PROTOC = ${DEPS_PATH}/bin/protoc
endif

INCPATH = -I./pssrc -I./include -I$(DEPS_PATH)/include -fsanitize=address
CFLAGS = -std=c++11 -msse2 -fPIC -O3 -ggdb  -Wall -finline-functions $(INCPATH) $(ADD_CFLAGS)


include make/deps.mk


lint:
	python tests/lint.py ps all include/ps pssrc

ps: build/libps.a


PS_OBJS = $(addprefix build/, customer.o postoffice.o van.o meta.pb.o)

build/libps.a: $(PS_OBJS)
	ar crv $@ $(filter %.o, $?)

build/%.o: pssrc/%.cc ${ZMQ} pssrc/meta.pb.h
	@mkdir -p $(@D)
	$(CXX) $(INCPATH) -std=c++0x -MM -MT build/$*.o $< >build/$*.d
	$(CXX) $(CFLAGS) -c $< -o $@

pssrc/%.pb.cc pssrc/%.pb.h : pssrc/%.proto ${PROTOBUF}
	$(PROTOC) --cpp_out=./pssrc --proto_path=./pssrc $<

-include build/*.d
-include build/*/*.d

include pstests/test.mk
pstests: $(TEST)

include pslib/pslib.mk
pslib: $(PSLIB)

$(info "athena start")
CUDA_DIR = /usr/local/cuda

CC_SRCS := $(wildcard src/*.cc)
CC_OBJS := ${CC_SRCS:src/%.cc=build/obj/%.o}
CUDA_SRCS := $(wildcard src/*.cu)
CUDA_OBJS := ${CUDA_SRCS:src/%.cu=build/obj/%.o}
OBJS := $(CC_OBJS) $(CUDA_OBJS)

CC = g++
WARNINGS = -Wall -Wfatal-errors -Wno-unused -Wno-unused-result
CC_FLAGS = -std=c++11 -fPIC $(WARNINGS) -I$(CUDA_DIR)/include
LD_FLAGS = -L$(CUDA_DIR)/lib64 -lcuda -lcudart -lcublas -lcudnn -lnccl

NVCC = /usr/local/cuda/bin/nvcc
NVCC_FLAGS = -std=c++11 --compiler-options '-fPIC'
ARCH = -gencode arch=compute_30,code=sm_30 \
       -gencode arch=compute_35,code=sm_35 \
       -gencode arch=compute_50,code=[sm_50,compute_50] \
       -gencode arch=compute_52,code=[sm_52,compute_52]

all: athena ps pstests pslib

athena: build/lib/libc_runtime_api.so

build/lib/libc_runtime_api.so: $(OBJS)
	@mkdir -p build/lib
	$(CC) -shared $^ -o $@ $(LD_FLAGS)

build/obj/%.o: src/%.cc
	@mkdir -p build/obj
	$(CC) $(CC_FLAGS) -c $< -o $@

build/obj/%.o: src/%.cu
	@mkdir -p build/obj
	$(NVCC) $(ARCH) $(NVCC_FLAGS) -c $< -o $@




.PHONY: clean all
clean:
	-rm -rf build $(TEST) $(PSLIB) pstests/*.d pslib/*.d
	find src -name "*.pb.[ch]*" -delete
	find pssrc -name "*.pb.[ch]*" -delete
```




My pslib.mk is:
```
PSLIB_SRC = pslib/worker.cc
PSLIB = $(patsubst pslib/%.cc, pslib/%.so, $(PSLIB_SRC))

# -ltcmalloc_and_profiler
LDFLAGS = -Wl,-rpath,$(DEPS_PATH)/lib $(PS_LDFLAGS_SO) -pthread

pslib/%.so: pslib/%.cc build/libps.a
	$(CXX) -std=c++11 $(CFLAGS) -MM -MT pslib/$* $< >pslib/$*.d
	$(CXX) -std=c++11 $(CFLAGS) -shared $^ -o $@ $(LDFLAGS)
#	$(CXX) -std=c++0x $(CFLAGS) -o $@ $(filter %.cc %.a, $^) $(LDFLAGS)

-include pslib/*.d

```



My ps.mk is:
```
#---------------------------------------------------------------------------------------
#  parameter server configuration script
#
#  include ps.mk after the variables are set
#
#----------------------------------------------------------------------------------------

ifeq ($(USE_KEY32), 1)
ADD_CFLAGS += -DUSE_KEY32=1
endif

PS_LDFLAGS_SO = -L$(DEPS_PATH)/lib -lprotobuf-lite -lzmq -pg  -fsanitize=address
PS_LDFLAGS_A = $(addprefix $(DEPS_PATH)/lib/, libprotobuf-lite.a libzmq.a)
```



My deps.mk is:
```
# Install dependencies

URL1=https://raw.githubusercontent.com/mli/deps/master/build
URL2=https://github.com/google/protobuf/releases/download/v3.5.1
ifndef WGET
WGET = wget
endif

# protobuf
PROTOBUF = ${DEPS_PATH}/include/google/protobuf/message.h
${PROTOBUF}:
	$(eval FILE=protobuf-cpp-3.5.1.tar.gz)
	$(eval DIR=protobuf-3.5.1)
	rm -rf $(FILE) $(DIR)
	$(WGET) $(URL2)/$(FILE) && tar --no-same-owner -zxf $(FILE)
	cd $(DIR) && export CFLAGS=-fPIC && export CXXFLAGS=-fPIC && ./configure -prefix=$(DEPS_PATH) && $(MAKE) && $(MAKE) install
	rm -rf $(FILE) $(DIR)

# zmq
ZMQ = ${DEPS_PATH}/include/zmq.h

${ZMQ}:
	$(eval FILE=zeromq-4.1.4.tar.gz)
	$(eval DIR=zeromq-4.1.4)
	rm -rf $(FILE) $(DIR)
	$(WGET) $(URL1)/$(FILE) && tar --no-same-owner -zxf $(FILE)
	cd $(DIR) && export CFLAGS=-fPIC && export CXXFLAGS=-fPIC && ./configure -prefix=$(DEPS_PATH) --with-libsodium=no --with-libgssapi_krb5=no && $(MAKE) && $(MAKE) install
	rm -rf $(FILE) $(DIR)

# lz4
LZ4 = ${DEPS_PATH}/include/lz4.h
${LZ4}:
	$(eval FILE=lz4-r129.tar.gz)
	$(eval DIR=lz4-r129)
	rm -rf $(FILE) $(DIR)
	wget $(URL1)/$(FILE) && tar --no-same-owner -zxf $(FILE)
	cd $(DIR) && $(MAKE) && PREFIX=$(DEPS_PATH) $(MAKE) install
	rm -rf $(FILE) $(DIR)

# cityhash
CITYHASH = ${DEPS_PATH}/include/city.h
${CITYHASH}:
	$(eval FILE=cityhash-1.1.1.tar.gz)
	$(eval DIR=cityhash-1.1.1)
	rm -rf $(FILE) $(DIR)
	wget $(URL1)/$(FILE) && tar --no-same-owner -zxf $(FILE)
	cd $(DIR) && ./configure -prefix=$(DEPS_PATH) --enable-sse4.2 && $(MAKE) CXXFLAGS="-g -O3 -msse4.2" && $(MAKE) install
	rm -rf $(FILE) $(DIR)


# # gflags
# ${DEPS_PATH}/include/google/gflags.h:
# 	$(eval FILE=gflags-2.0-no-svn-files.tar.gz)
# 	$(eval DIR=gflags-2.0)
# 	rm -rf $(FILE) $(DIR)
# 	wget $(URL)/$(FILE) && tar -zxf $(FILE)
# 	cd $(DIR) && ./configure -prefix=$(DEPS_PATH) && $(MAKE) && $(MAKE) install
# 	rm -rf $(FILE) $(DIR)
# gflags: | ${DEPS_PATH}/include/google/gflags.h

# # glog
# ${DEPS_PATH}/include/glog/logging.h: | ${DEPS_PATH}/include/google/gflags.h
# 	$(eval FILE=v0.3.4.tar.gz)
# 	$(eval DIR=glog-0.3.4)
# 	rm -rf $(FILE) $(DIR)
# 	wget https://github.com/google/glog/archive/$(FILE) && tar -zxf $(FILE)
# 	cd $(DIR) && ./configure -prefix=$(DEPS_PATH) --with-gflags=$(DEPS_PATH) && $(MAKE) && $(MAKE) install
# 	rm -rf $(FILE) $(DIR)
# glog: | ${DEPS_PATH}/include/glog/logging.h
```

My test.mk is:
```
TEST_SRC = $(wildcard pstests/test_*.cc)
TEST = $(patsubst pstests/test_%.cc, pstests/test_%, $(TEST_SRC))

# -ltcmalloc_and_profiler
LDFLAGS = -Wl,-rpath,$(DEPS_PATH)/lib $(PS_LDFLAGS_SO) -pthread 
pstests/% : pstests/%.cc build/libps.a
	$(CXX) -std=c++0x $(CFLAGS) -MM -MT pstests/$* $< >pstests/$*.d
	$(CXX) -std=c++0x $(CFLAGS) -o $@ $(filter %.cc %.a, $^) $(LDFLAGS)

-include pstests/*.d
```


And my cmd is:
make clean -f ps_Makefile
make all -f ps_Makefile

**Comment by hbsun2113** [comment]
The make information is:
```
"ps start"
"CXX = " g++
"athena start"
rm -rf build  pstests/test_connection  pstests/test_simple_app  pstests/test_kv_app_multi_workers  pstests/test_kv_app  pslib/worker.so pstests/*.d pslib/*.d
find src -name "*.pb.[ch]*" -delete
find pssrc -name "*.pb.[ch]*" -delete
"ps start"
"CXX = " g++
"athena start"
g++ -std=c++11 -fPIC -Wall -Wfatal-errors -Wno-unused -Wno-unused-result -I/usr/local/cuda/include -c src/cuda_device_api.cc -o build/obj/cuda_device_api.o
g++ -std=c++11 -fPIC -Wall -Wfatal-errors -Wno-unused -Wno-unused-result -I/usr/local/cuda/include -c src/gpu_chunk.cc -o build/obj/gpu_chunk.o
g++ -std=c++11 -fPIC -Wall -Wfatal-errors -Wno-unused -Wno-unused-result -I/usr/local/cuda/include -c src/c_runtime_api.cc -o build/obj/c_runtime_api.o
g++ -std=c++11 -fPIC -Wall -Wfatal-errors -Wno-unused -Wno-unused-result -I/usr/local/cuda/include -c src/cpu_device_api.cc -o build/obj/cpu_device_api.o
g++ -std=c++11 -fPIC -Wall -Wfatal-errors -Wno-unused -Wno-unused-result -I/usr/local/cuda/include -c src/gpu_runtime.cc -o build/obj/gpu_runtime.o
g++ -shared build/obj/cuda_device_api.o build/obj/gpu_chunk.o build/obj/c_runtime_api.o build/obj/cpu_device_api.o build/obj/gpu_runtime.o -o build/lib/libc_runtime_api.so -L/usr/local/cuda/lib64 -lcuda -lcudart -lcublas -lcudnn -lnccl
/home/xiaonan/hbsun/distribute/Athena/deps/bin/protoc --cpp_out=./pssrc --proto_path=./pssrc pssrc/meta.proto
g++ -I./pssrc -I./include -I/home/xiaonan/hbsun/distribute/Athena/deps/include -fsanitize=address -std=c++0x -MM -MT build/customer.o pssrc/customer.cc >build/customer.d
g++ -std=c++11 -msse2 -fPIC -O3 -ggdb  -Wall -finline-functions -I./pssrc -I./include -I/home/xiaonan/hbsun/distribute/Athena/deps/include -fsanitize=address  -c pssrc/customer.cc -o build/customer.o
g++ -I./pssrc -I./include -I/home/xiaonan/hbsun/distribute/Athena/deps/include -fsanitize=address -std=c++0x -MM -MT build/postoffice.o pssrc/postoffice.cc >build/postoffice.d
g++ -std=c++11 -msse2 -fPIC -O3 -ggdb  -Wall -finline-functions -I./pssrc -I./include -I/home/xiaonan/hbsun/distribute/Athena/deps/include -fsanitize=address  -c pssrc/postoffice.cc -o build/postoffice.o
g++ -I./pssrc -I./include -I/home/xiaonan/hbsun/distribute/Athena/deps/include -fsanitize=address -std=c++0x -MM -MT build/van.o pssrc/van.cc >build/van.d
g++ -std=c++11 -msse2 -fPIC -O3 -ggdb  -Wall -finline-functions -I./pssrc -I./include -I/home/xiaonan/hbsun/distribute/Athena/deps/include -fsanitize=address  -c pssrc/van.cc -o build/van.o
g++ -I./pssrc -I./include -I/home/xiaonan/hbsun/distribute/Athena/deps/include -fsanitize=address -std=c++0x -MM -MT build/meta.pb.o pssrc/meta.pb.cc >build/meta.pb.d
g++ -std=c++11 -msse2 -fPIC -O3 -ggdb  -Wall -finline-functions -I./pssrc -I./include -I/home/xiaonan/hbsun/distribute/Athena/deps/include -fsanitize=address  -c pssrc/meta.pb.cc -o build/meta.pb.o
ar crv build/libps.a build/customer.o build/postoffice.o build/van.o build/meta.pb.o
a - build/customer.o
a - build/postoffice.o
a - build/van.o
a - build/meta.pb.o
g++ -std=c++0x -std=c++11 -msse2 -fPIC -O3 -ggdb  -Wall -finline-functions -I./pssrc -I./include -I/home/xiaonan/hbsun/distribute/Athena/deps/include -fsanitize=address  -MM -MT pstests/test_connection pstests/test_connection.cc >pstests/test_connection.d
g++ -std=c++0x -std=c++11 -msse2 -fPIC -O3 -ggdb  -Wall -finline-functions -I./pssrc -I./include -I/home/xiaonan/hbsun/distribute/Athena/deps/include -fsanitize=address  -o pstests/test_connection pstests/test_connection.cc build/libps.a -Wl,-rpath,/home/xiaonan/hbsun/distribute/Athena/deps/lib -L/home/xiaonan/hbsun/distribute/Athena/deps/lib -lprotobuf-lite -lzmq -pg  -fsanitize=address -pthread
g++ -std=c++0x -std=c++11 -msse2 -fPIC -O3 -ggdb  -Wall -finline-functions -I./pssrc -I./include -I/home/xiaonan/hbsun/distribute/Athena/deps/include -fsanitize=address  -MM -MT pstests/test_simple_app pstests/test_simple_app.cc >pstests/test_simple_app.d
g++ -std=c++0x -std=c++11 -msse2 -fPIC -O3 -ggdb  -Wall -finline-functions -I./pssrc -I./include -I/home/xiaonan/hbsun/distribute/Athena/deps/include -fsanitize=address  -o pstests/test_simple_app pstests/test_simple_app.cc build/libps.a -Wl,-rpath,/home/xiaonan/hbsun/distribute/Athena/deps/lib -L/home/xiaonan/hbsun/distribute/Athena/deps/lib -lprotobuf-lite -lzmq -pg  -fsanitize=address -pthread
g++ -std=c++0x -std=c++11 -msse2 -fPIC -O3 -ggdb  -Wall -finline-functions -I./pssrc -I./include -I/home/xiaonan/hbsun/distribute/Athena/deps/include -fsanitize=address  -MM -MT pstests/test_kv_app_multi_workers pstests/test_kv_app_multi_workers.cc >pstests/test_kv_app_multi_workers.d
g++ -std=c++0x -std=c++11 -msse2 -fPIC -O3 -ggdb  -Wall -finline-functions -I./pssrc -I./include -I/home/xiaonan/hbsun/distribute/Athena/deps/include -fsanitize=address  -o pstests/test_kv_app_multi_workers pstests/test_kv_app_multi_workers.cc build/libps.a -Wl,-rpath,/home/xiaonan/hbsun/distribute/Athena/deps/lib -L/home/xiaonan/hbsun/distribute/Athena/deps/lib -lprotobuf-lite -lzmq -pg  -fsanitize=address -pthread
g++ -std=c++0x -std=c++11 -msse2 -fPIC -O3 -ggdb  -Wall -finline-functions -I./pssrc -I./include -I/home/xiaonan/hbsun/distribute/Athena/deps/include -fsanitize=address  -MM -MT pstests/test_kv_app pstests/test_kv_app.cc >pstests/test_kv_app.d
g++ -std=c++0x -std=c++11 -msse2 -fPIC -O3 -ggdb  -Wall -finline-functions -I./pssrc -I./include -I/home/xiaonan/hbsun/distribute/Athena/deps/include -fsanitize=address  -o pstests/test_kv_app pstests/test_kv_app.cc build/libps.a -Wl,-rpath,/home/xiaonan/hbsun/distribute/Athena/deps/lib -L/home/xiaonan/hbsun/distribute/Athena/deps/lib -lprotobuf-lite -lzmq -pg  -fsanitize=address -pthread
g++ -std=c++11 -std=c++11 -msse2 -fPIC -O3 -ggdb  -Wall -finline-functions -I./pssrc -I./include -I/home/xiaonan/hbsun/distribute/Athena/deps/include -fsanitize=address  -MM -MT pslib/worker pslib/worker.cc >pslib/worker.d
g++ -std=c++11 -std=c++11 -msse2 -fPIC -O3 -ggdb  -Wall -finline-functions -I./pssrc -I./include -I/home/xiaonan/hbsun/distribute/Athena/deps/include -fsanitize=address  -shared pslib/worker.cc build/libps.a -o pslib/worker.so -Wl,-rpath,/home/xiaonan/hbsun/distribute/Athena/deps/lib -L/home/xiaonan/hbsun/distribute/Athena/deps/lib -lprotobuf-lite -lzmq -pg  -fsanitize=address -pthread
rm pssrc/meta.pb.h
```

**Comment by yugr** [comment]
Is the main executable file sanitized? If not, you'll need this entry from [FAQ](https://github.com/google/sanitizers/wiki/AddressSanitizer#faq) :
```
Q: I've built my shared library with ASan. Can I run it with unsanitized executable?
A: Yes! You'll need to build your library with dynamic version of ASan and then run executable with LD_PRELOAD=path/to/asan/runtime/lib.
```

**Comment by hbsun2113** [comment]
> Is the main executable file sanitized? If not, you'll need this entry from [FAQ](https://github.com/google/sanitizers/wiki/AddressSanitizer#faq) :
> 
> ```
> Q: I've built my shared library with ASan. Can I run it with unsanitized executable?
> A: Yes! You'll need to build your library with dynamic version of ASan and then run executable with LD_PRELOAD=path/to/asan/runtime/lib.
> ```

I use python to call a `.so` file which is generated from c++.  I only want the `.so` is sanitized. What should I set LD_PRELOAD to?

**Comment by mrichtarsky** [comment]
export LD_PRELOAD=`gcc -print-file-name=libasan.so`

Then run your Python script.

**Comment by hbsun2113** [comment]
> ```
> export LD_PRELOAD=`gcc -print-file-name=libasan.so`
> ```
> 
> Then run your Python script.

It seems that sanitizers tests the python program instead of my `worker.so`, how can I evaluate my .so file? :

```
=================================================================
==136066==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 1891200 byte(s) in 539 object(s) allocated from:
    #0 0x7fc4a72b679a in __interceptor_calloc (/usr/lib/gcc/x86_64-linux-gnu/5/libasan.so+0x9879a)
    #1 0x498e0c  (/usr/bin/python2.7+0x498e0c)

Direct leak of 439392 byte(s) in 43 object(s) allocated from:
    #0 0x7fc4a72b6602 in malloc (/usr/lib/gcc/x86_64-linux-gnu/5/libasan.so+0x98602)
    #1 0x49e442  (/usr/bin/python2.7+0x49e442)

Direct leak of 384824 byte(s) in 337 object(s) allocated from:
    #0 0x7fc4a72b6602 in malloc (/usr/lib/gcc/x86_64-linux-gnu/5/libasan.so+0x98602)
    #1 0x4a0041 in PyString_FromStringAndSize (/usr/bin/python2.7+0x4a0041)

Direct leak of 298664 byte(s) in 316 object(s) allocated from:
    #0 0x7fc4a72b6602 in malloc (/usr/lib/gcc/x86_64-linux-gnu/5/libasan.so+0x98602)
    #1 0x4992de in PyType_GenericAlloc (/usr/bin/python2.7+0x4992de)

Direct leak of 8704 byte(s) in 7 object(s) allocated from:
    #0 0x7fc4a72b679a in __interceptor_calloc (/usr/lib/gcc/x86_64-linux-gnu/5/libasan.so+0x9879a)
    #1 0x4fd708  (/usr/bin/python2.7+0x4fd708)

Direct leak of 7894 byte(s) in 6 object(s) allocated from:
    #0 0x7fc4a72b6602 in malloc (/usr/lib/gcc/x86_64-linux-gnu/5/libasan.so+0x98602)
    #1 0x494bba in PyString_FromString (/usr/bin/python2.7+0x494bba)

Direct leak of 6584 byte(s) in 12 object(s) allocated from:
    #0 0x7fc4a72b6602 in malloc (/usr/lib/gcc/x86_64-linux-gnu/5/libasan.so+0x98602)
    #1 0x418658 in _PyObject_GC_Malloc (/usr/bin/python2.7+0x418658)

Direct leak of 4904 byte(s) in 16 object(s) allocated from:
    #0 0x7fc4a72b6961 in realloc (/usr/lib/gcc/x86_64-linux-gnu/5/libasan.so+0x98961)
    #1 0x49528d  (/usr/bin/python2.7+0x49528d)

Direct leak of 4656 byte(s) in 127 object(s) allocated from:
    #0 0x7fc4a72b6961 in realloc (/usr/lib/gcc/x86_64-linux-gnu/5/libasan.so+0x98961)
    #1 0x49522b  (/usr/bin/python2.7+0x49522b)

Direct leak of 2560 byte(s) in 4 object(s) allocated from:
    #0 0x7fc4a72b6961 in realloc (/usr/lib/gcc/x86_64-linux-gnu/5/libasan.so+0x98961)
    #1 0x4ffd7f in _PyObject_GC_Resize (/usr/bin/python2.7+0x4ffd7f)

Direct leak of 1928 byte(s) in 44 object(s) allocated from:
    #0 0x7fc4a72b6602 in malloc (/usr/lib/gcc/x86_64-linux-gnu/5/libasan.so+0x98602)
    #1 0x493fce in PyList_New (/usr/bin/python2.7+0x493fce)

Direct leak of 1510 byte(s) in 61 object(s) allocated from:
    #0 0x7fc4a72b6602 in malloc (/usr/lib/gcc/x86_64-linux-gnu/5/libasan.so+0x98602)
    #1 0x7fc41715b590 in _ctypes_alloc_format_string (/usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so+0x17590)

Direct leak of 824 byte(s) in 23 object(s) allocated from:
    #0 0x7fc4a72b6602 in malloc (/usr/lib/gcc/x86_64-linux-gnu/5/libasan.so+0x98602)
    #1 0x7fc41714efa8 in PyCStructUnionType_update_stgdict (/usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so+0xafa8)

Direct leak of 672 byte(s) in 14 object(s) allocated from:
    #0 0x7fc4a72b6602 in malloc (/usr/lib/gcc/x86_64-linux-gnu/5/libasan.so+0x98602)
    #1 0x523c58  (/usr/bin/python2.7+0x523c58)

Direct leak of 536 byte(s) in 1 object(s) allocated from:
    #0 0x7fc4a72b6602 in malloc (/usr/lib/gcc/x86_64-linux-gnu/5/libasan.so+0x98602)
    #1 0x505615  (/usr/bin/python2.7+0x505615)

Direct leak of 192 byte(s) in 12 object(s) allocated from:
    #0 0x7fc4a72b6602 in malloc (/usr/lib/gcc/x86_64-linux-gnu/5/libasan.so+0x98602)
    #1 0x7fc4a345a810 in PyDataMem_NEW numpy/core/src/multiarray/alloc.c:229
    #2 0x7fc4a345a810 in _npy_alloc_cache numpy/core/src/multiarray/alloc.c:76
    #3 0x7fc4a345a810 in npy_alloc_cache numpy/core/src/multiarray/alloc.c:122

Direct leak of 192 byte(s) in 12 object(s) allocated from:
    #0 0x7fc4a72b6602 in malloc (/usr/lib/gcc/x86_64-linux-gnu/5/libasan.so+0x98602)
    #1 0x7fc4a345aadf in _npy_alloc_cache numpy/core/src/multiarray/alloc.c:76
    #2 0x7fc4a345aadf in npy_alloc_cache_dim numpy/core/src/multiarray/alloc.c:164

Direct leak of 149 byte(s) in 25 object(s) allocated from:
    #0 0x7fc4a72b6602 in malloc (/usr/lib/gcc/x86_64-linux-gnu/5/libasan.so+0x98602)
    #1 0x7fc41715b5d8 in _ctypes_alloc_format_string (/usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so+0x175d8)

Direct leak of 104 byte(s) in 3 object(s) allocated from:
    #0 0x7fc4a72b6602 in malloc (/usr/lib/gcc/x86_64-linux-gnu/5/libasan.so+0x98602)
    #1 0x7fc41714e6dc in PyCStructUnionType_update_stgdict (/usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so+0xa6dc)

Direct leak of 80 byte(s) in 1 object(s) allocated from:
    #0 0x7fc4a72b6961 in realloc (/usr/lib/gcc/x86_64-linux-gnu/5/libasan.so+0x98961)
    #1 0x49a51c  (/usr/bin/python2.7+0x49a51c)

Direct leak of 80 byte(s) in 1 object(s) allocated from:
    #0 0x7fc4a72b6961 in realloc (/usr/lib/gcc/x86_64-linux-gnu/5/libasan.so+0x98961)
    #1 0x50aeac  (/usr/bin/python2.7+0x50aeac)

Direct leak of 80 byte(s) in 10 object(s) allocated from:
    #0 0x7fc4a72b6602 in malloc (/usr/lib/gcc/x86_64-linux-gnu/5/libasan.so+0x98602)
    #1 0x7fc41715a811  (/usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so+0x16811)

Direct leak of 8 byte(s) in 1 object(s) allocated from:
    #0 0x7fc4a72b6602 in malloc (/usr/lib/gcc/x86_64-linux-gnu/5/libasan.so+0x98602)
    #1 0x7fc4a345a810 in PyDataMem_NEW numpy/core/src/multiarray/alloc.c:229
    #2 0x7fc4a345a810 in _npy_alloc_cache numpy/core/src/multiarray/alloc.c:76
    #3 0x7fc4a345a810 in npy_alloc_cache numpy/core/src/multiarray/alloc.c:122
    #4 0x7fc4161f36cf  (<unknown module>)

Direct leak of 1 byte(s) in 1 object(s) allocated from:
    #0 0x7fc4a72b6602 in malloc (/usr/lib/gcc/x86_64-linux-gnu/5/libasan.so+0x98602)
    #1 0x7fc4a345a810 in PyDataMem_NEW numpy/core/src/multiarray/alloc.c:229
    #2 0x7fc4a345a810 in _npy_alloc_cache numpy/core/src/multiarray/alloc.c:76
    #3 0x7fc4a345a810 in npy_alloc_cache numpy/core/src/multiarray/alloc.c:122
    #4 0x4a7ff6  (/usr/bin/python2.7+0x4a7ff6)
    #5 0x2b2f55bb0b5103ff  (<unknown module>)

Indirect leak of 120832 byte(s) in 128 object(s) allocated from:
    #0 0x7fc4a72b6602 in malloc (/usr/lib/gcc/x86_64-linux-gnu/5/libasan.so+0x98602)
    #1 0x4992de in PyType_GenericAlloc (/usr/bin/python2.7+0x4992de)

Indirect leak of 102358 byte(s) in 69 object(s) allocated from:
    #0 0x7fc4a72b6602 in malloc (/usr/lib/gcc/x86_64-linux-gnu/5/libasan.so+0x98602)
    #1 0x4ab197  (/usr/bin/python2.7+0x4ab197)

Indirect leak of 81884 byte(s) in 53 object(s) allocated from:
    #0 0x7fc4a72b6602 in malloc (/usr/lib/gcc/x86_64-linux-gnu/5/libasan.so+0x98602)
    #1 0x4a0041 in PyString_FromStringAndSize (/usr/bin/python2.7+0x4a0041)

Indirect leak of 11704 byte(s) in 13 object(s) allocated from:
    #0 0x7fc4a72b6602 in malloc (/usr/lib/gcc/x86_64-linux-gnu/5/libasan.so+0x98602)
    #1 0x494bba in PyString_FromString (/usr/bin/python2.7+0x494bba)

Indirect leak of 1053 byte(s) in 1 object(s) allocated from:
    #0 0x7fc4a72b6602 in malloc (/usr/lib/gcc/x86_64-linux-gnu/5/libasan.so+0x98602)
    #1 0x4de4fc in PyString_Concat (/usr/bin/python2.7+0x4de4fc)

Indirect leak of 624 byte(s) in 1 object(s) allocated from:
    #0 0x7fc4a72b6602 in malloc (/usr/lib/gcc/x86_64-linux-gnu/5/libasan.so+0x98602)
    #1 0x418658 in _PyObject_GC_Malloc (/usr/bin/python2.7+0x418658)

SUMMARY: AddressSanitizer: 3374193 byte(s) leaked in 1881 allocation(s).
```

**Comment by hbsun2113** [comment]
@kcc 
I run my python file by: ```python mnist_mlp_ps.py &```, and I call ```.so file``` by my python file:
![image](https://user-images.githubusercontent.com/27994442/69924235-50917e00-14e5-11ea-8818-938c98ed1de0.png)

It seems that sanitizers evaluate the python file not my ```.so file```. HOW can sanitizers evaluate my ```.so file```?
