### ISSUE TITLE
mmap address with the asan flag -fsanitize=address，can not access，how to sovle it？

### ISSUE THREAD

**Issue by shisuhao** [google/sanitizers#1209]
Recently，I try to use asan with my code, and I have some troubles.
code:
int main(void)
{
	uintptr_t Base = 0x100000000000;
    uintptr_t Size = 4096;
	errno = 0;
    void *addr = mmap((void *)Base, Size, PROT_READ | PROT_WRITE, MAP_ANONYMOUS | MAP_SHARED | MAP_FIXED, 0, 0);
	

    printf("address == %p,errno = %d\r\n", addr, errno);

    assert(addr == (void*)Base);

    uintptr_t Addr = Base + Size - 1;
    *(char*)Addr = 1;	
    return 0;
};
# gcc -Wall -g -fsanitize=address abcd.c -o abcd
# LD_PRELOAD=/usr/lib/gcc/aarch64-linux-gnu/7.3.0/libasan.so ./abcd 
then,I got an error:
address == 0x100000000000,errno = 0                                             
ASAN:DEADLYSIGNAL                                                               
=================================================================               
==12141==ERROR: AddressSanitizer: SEGV on unknown address 0x0210000001ff (pc 0x0
00000400b58 bp 0xfffff7141000 sp 0xfffff7141000 T0)                             
==12141==The signal is caused by a READ memory access.                          
    #0 0x400b57 in main /home/hss/abcd.c:32                                     
    #1 0xffffba66dadf in __libc_start_main (/lib64/libc.so.6+0x20adf)           
    #2 0x400933  (/home/hss/abcd+0x400933)                                      
                                                                                
AddressSanitizer can not provide additional info.                               
SUMMARY: AddressSanitizer: SEGV /home/hss/abcd.c:32 in main                     
==12141==ABORTING                                                               

I tried to found my machine asan memory map, follow:
[0x2000000000, 0x7fffffffff]  highmem    
[0x1400000000, 0x1fffffffff]  highshadow 
[0x1200000000, 0x13ffffffff]  shadowgap  
[0x1000000000, 0x11ffffffff]  lowshadow  
[0x0000000000, 0x0fffffffff]  lowmem     
I found the address 0x100000000000 is not in the map, and the mmap function return ok,I want to know how to sovle it? anthor question,what is asan shadow_gap?when mmap address conflict with Shadow gap, use protect_shadow_gap=0, Is access to shadow_gap allowed?
Looking forward to your answer！and do not care my poor english.

**Comment by shisuhao** [comment]
I found the right asan memory map by use debug=1:verbosity=3;
and the address 0x100000000000 are in the shadow, so i will close the issue
