### ISSUE TITLE
TSAN segfault

### ISSUE THREAD

**Issue by amandeepgautam** [google/sanitizers#1240]
I have a simple c++ program:
                                                    
```
#include <iostream>    
using namespace std;                                                            
                                                                                
int main() {                                                                               
  cout << "Hello, World!" << endl;                                              
  return 0;                                                                     
}                                                                               
```

I compile it using `g++ -fsanitize=thread tsan_test.cc`. The executable does not run at all. Here is an output from gdb:

```
$ gdb a.out 
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.3) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from a.out...(no debugging symbols found)...done.
(gdb) run
Starting program: /home/cohesity/workspace/tools/a.out 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007ffff71566a7 in ?? () from /usr/lib/x86_64-linux-gnu/libtsan.so.0
#2  0x00007ffff71327c6 in ?? () from /usr/lib/x86_64-linux-gnu/libtsan.so.0
#3  0x00007ffff71329da in ?? () from /usr/lib/x86_64-linux-gnu/libtsan.so.0
#4  0x00007ffff7132a4e in ?? () from /usr/lib/x86_64-linux-gnu/libtsan.so.0
#5  0x00007ffff71312af in ?? () from /usr/lib/x86_64-linux-gnu/libtsan.so.0
#6  0x00007ffff713147b in ?? () from /usr/lib/x86_64-linux-gnu/libtsan.so.0
#7  0x00007ffff70ee8e7 in calloc () from /usr/lib/x86_64-linux-gnu/libtsan.so.0
#8  0x00007ffff6594690 in _dlerror_run (operate=operate@entry=0x7ffff6594130 <dlsym_doit>, args=args@entry=0x7fffffffe1e0) at dlerror.c:141
#9  0x00007ffff6594198 in __dlsym (handle=<optimized out>, name=<optimized out>) at dlsym.c:70
#10 0x00007ffff7163615 in ?? () from /usr/lib/x86_64-linux-gnu/libtsan.so.0
#11 0x00007ffff7114b35 in ?? () from /usr/lib/x86_64-linux-gnu/libtsan.so.0
#12 0x00007ffff7138f28 in ?? () from /usr/lib/x86_64-linux-gnu/libtsan.so.0
#13 0x00007ffff70ed1a3 in ?? () from /usr/lib/x86_64-linux-gnu/libtsan.so.0
#14 0x00007ffff70ee446 in __interceptor___cxa_atexit () from /usr/lib/x86_64-linux-gnu/libtsan.so.0
#15 0x00007ffff6dec566 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#16 0x00007ffff7dea1da in call_init (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0x7fffffffe3e8, env=env@entry=0x7fffffffe3f8) at dl-init.c:78
#17 0x00007ffff7dea2c3 in call_init (env=<optimized out>, argv=<optimized out>, argc=<optimized out>, l=<optimized out>) at dl-init.c:36
#18 _dl_init (main_map=0x7ffff7ffe1c8, argc=1, argv=0x7fffffffe3e8, env=0x7fffffffe3f8) at dl-init.c:126
#19 0x00007ffff7ddb29a in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#20 0x0000000000000001 in ?? ()
#21 0x00007fffffffe650 in ?? ()
#22 0x0000000000000000 in ?? ()
```

I cannot identify the issue, but since the c++ program is simple and runs fine when I do not link tsan, I am hoping it must be the tsan lib or the env.

```
$ g++ --version
g++ (Ubuntu 7.5.0-3ubuntu1~14.04.1) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

ldd output:
```
$ /usr/bin/ldd ./a.out 
	linux-vdso.so.1 =>  (0x00007fff0b7f5000)
	libtsan.so.0 => /usr/lib/x86_64-linux-gnu/libtsan.so.0 (0x00007f6939477000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f693912d000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f6938f15000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6938b4b000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6938947000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f693873f000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6938520000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f693821a000)
	/lib64/ld-linux-x86-64.so.2 (0x00005618fd30d000)

```

**Comment by aditya7fb** [comment]
I'd check if libtsan and gcc versions are compatible.

**Comment by amandeepgautam** [comment]
@aditya7fb How would you do that? I did not specifically install tsan. It came with gcc and hence should be compatible.

**Comment by aditya7fb** [comment]
ok, i might be compatible then. Because the ubuntu version is quite old, i'm not sure how good tsan used to work that time.

**Comment by amandeepgautam** [comment]
hmm...
