### ISSUE TITLE
HWAddressSanitizer CHECK failed: hwasan.cpp:528 "((GetTagFromPointer(dst) == 0)) != (0)" (0x0, 0x0)

### ISSUE THREAD

**Issue by jiridanek** [google/sanitizers#1244]
Same usecase as in #1243, which means `-shared-asan`, uninstrumented Python/Ruby interpreter, and `LD_PRELOAD`. Using my own build of clang-11 from git.

```
ubuntu@ubuntu:~/repos/qpid-proton-0.31.0/clang/python$ /usr/bin/python3 "/home/ubuntu/repos/qpid-proton-0.31.0/scripts/env.py" "--" "PATH=/home/ubuntu/repos/qpid-proton-0.31.0/clang/c/tools:/home/ubuntu/repos/qpid-proton-0.31.0/clang/c:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin" "SASLPASSWD=CyrusSASL_Saslpasswd_EXECUTABLE-NOTFOUND" "SWIG=/usr/bin/swig4.0" "UBSAN_OPTIONS=suppressions=/home/ubuntu/repos/qpid-proton-0.31.0/tests/ubsan.supp" "LSAN_OPTIONS=suppressions=/home/ubuntu/repos/qpid-proton-0.31.0/tests/lsan.supp" "HWASAN_OPTIONS=external_symbolizer_path=/home/ubuntu/llvm/install/bin/llvm-symbolizer" "/home/ubuntu/repos/qpid-proton-0.31.0/tests/preload_asan.sh" "/home/ubuntu/repos/qpid-proton-0.31.0/clang/c/libqpid-proton-core.so.10.9.0" "/usr/bin/python3" "-m" "tox"
==115259==HWAddressSanitizer CHECK failed: /mnt/repos/llvm-project/compiler-rt/lib/hwasan/hwasan.cpp:528 "((GetTagFromPointer(dst) == 0)) != (0)" (0x0, 0x0)
==115259==HWAddressSanitizer CHECK failed: /mnt/repos/llvm-project/compiler-rt/lib/hwasan/hwasan.cpp:528 "((GetTagFromPointer(dst) == 0)) != (0)" (0x0, 0x0)
==115259==HWAddressSanitizer CHECK failed: /mnt/repos/llvm-project/compiler-rt/lib/hwasan/hwasan.cpp:528 "((GetTagFromPointer(dst) == 0)) != (0)" (0x0, 0x0)
==115259==HWAddressSanitizer CHECK failed: /mnt/repos/llvm-project/compiler-rt/lib/hwasan/hwasan.cpp:528 "((GetTagFromPointer(dst) == 0)) != (0)" (0x0, 0x0)
==115259==HWAddressSanitizer CHECK failed: /mnt/repos/llvm-project/compiler-rt/lib/hwasan/hwasan.cpp:528 "((GetTagFromPointer(dst) == 0)) != (0)" (0x0, 0x0)
==115259==HWAddressSanitizer CHECK failed: /mnt/repos/llvm-project/compiler-rt/lib/hwasan/hwasan.cpp:528 "((GetTagFromPointer(dst) == 0)) != (0)" (0x0, 0x0)
==115259==HWAddressSanitizer CHECK failed: /mnt/repos/llvm-project/compiler-rt/lib/hwasan/hwasan.cpp:528 "((GetTagFromPointer(dst) == 0)) != (0)" (0x0, 0x0)
==115259==HWAddressSanitizer CHECK failed: /mnt/repos/llvm-project/compiler-rt/lib/hwasan/hwasan.cpp:528 "((GetTagFromPointer(dst) == 0)) != (0)" (0x0, 0x0)
GLOB sdist-make: /home/ubuntu/repos/qpid-proton-0.31.0/clang/python/dist/setup.py
    #0 0xffff8838fa74 in __hwasan::HWAsanCheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /mnt/repos/llvm-project/compiler-rt/lib/hwasan/hwasan.cpp:133:3
    #0 0xffff8838fa74 in __hwasan::HWAsanCheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /mnt/repos/llvm-project/compiler-rt/lib/hwasan/hwasan.cpp:133:3
    #0 0xffff8838fa74 in __hwasan::HWAsanCheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /mnt/repos/llvm-project/compiler-rt/lib/hwasan/hwasan.cpp:133:3
    #0 0xffff8838fa74 in __hwasan::HWAsanCheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /mnt/repos/llvm-project/compiler-rt/lib/hwasan/hwasan.cpp:133:3
    #0 0xffff8838fa74 in __hwasan::HWAsanCheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /mnt/repos/llvm-project/compiler-rt/lib/hwasan/hwasan.cpp:133:3
    #0 0xffff8838fa74 in __hwasan::HWAsanCheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /mnt/repos/llvm-project/compiler-rt/lib/hwasan/hwasan.cpp:133:3
    #0 0xffff8838fa74 in __hwasan::HWAsanCheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /mnt/repos/llvm-project/compiler-rt/lib/hwasan/hwasan.cpp:133:3
    #1 0xffff883ad174 in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /mnt/repos/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_termination.cpp:78:24
    #2 0xffff88390760 in __hwasan_handle_longjmp /mnt/repos/llvm-project/compiler-rt/lib/hwasan/hwasan.cpp:528:3
    #3 0xffff88395de4 in InternalLongjmp /mnt/repos/llvm-project/compiler-rt/lib/hwasan/hwasan_interceptors.cpp:252:26
    #4 0xffff88395de4 in __libc_longjmp /mnt/repos/llvm-project/compiler-rt/lib/hwasan/hwasan_interceptors.cpp:296:18
    #1 0xffff883ad174 in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /mnt/repos/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_termination.cpp:78:24
    #1 0xffff883ad174 in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /mnt/repos/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_termination.cpp:78:24
    #1 0xffff883ad174 in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /mnt/repos/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_termination.cpp:78:24
    #1 0xffff883ad174 in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /mnt/repos/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_termination.cpp:78:24
    #0 0xffff8838fa74 in __hwasan::HWAsanCheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /mnt/repos/llvm-project/compiler-rt/lib/hwasan/hwasan.cpp:133:3
    #1 0xffff883ad174 in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /mnt/repos/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_termination.cpp:78:24
    #2 0xffff88390760 in __hwasan_handle_longjmp /mnt/repos/llvm-project/compiler-rt/lib/hwasan/hwasan.cpp:528:3
    #3 0xffff88395de4 in InternalLongjmp /mnt/repos/llvm-project/compiler-rt/lib/hwasan/hwasan_interceptors.cpp:252:26
    #4 0xffff88395de4 in __libc_longjmp /mnt/repos/llvm-project/compiler-rt/lib/hwasan/hwasan_interceptors.cpp:296:18
    #2 0xffff88390760 in __hwasan_handle_longjmp /mnt/repos/llvm-project/compiler-rt/lib/hwasan/hwasan.cpp:528:3
    #2 0xffff88390760 in __hwasan_handle_longjmp /mnt/repos/llvm-project/compiler-rt/lib/hwasan/hwasan.cpp:528:3
    #2 0xffff88390760 in __hwasan_handle_longjmp /mnt/repos/llvm-project/compiler-rt/lib/hwasan/hwasan.cpp:528:3
    #2 0xffff88390760 in __hwasan_handle_longjmp /mnt/repos/llvm-project/compiler-rt/lib/hwasan/hwasan.cpp:528:3
    #3 0xffff88395de4 in InternalLongjmp /mnt/repos/llvm-project/compiler-rt/lib/hwasan/hwasan_interceptors.cpp:252:26
    #4 0xffff88395de4 in __libc_longjmp /mnt/repos/llvm-project/compiler-rt/lib/hwasan/hwasan_interceptors.cpp:296:18
    #1 0xffff883ad174 in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /mnt/repos/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_termination.cpp:78:24
    #5 0xffff881fa800 in unwind_stop /build/glibc-w4ZToO/glibc-2.31/nptl/unwind.c:94:5
    #5 0xffff881fa800 in unwind_stop /build/glibc-w4ZToO/glibc-2.31/nptl/unwind.c:94:5
    #3 0xffff88395de4 in InternalLongjmp /mnt/repos/llvm-project/compiler-rt/lib/hwasan/hwasan_interceptors.cpp:252:26
    #4 0xffff88395de4 in __libc_longjmp /mnt/repos/llvm-project/compiler-rt/lib/hwasan/hwasan_interceptors.cpp:296:18
    #3 0xffff88395de4 in InternalLongjmp /mnt/repos/llvm-project/compiler-rt/lib/hwasan/hwasan_interceptors.cpp:252:26
    #4 0xffff88395de4 in __libc_longjmp /mnt/repos/llvm-project/compiler-rt/lib/hwasan/hwasan_interceptors.cpp:296:18
    #3 0xffff88395de4 in InternalLongjmp /mnt/repos/llvm-project/compiler-rt/lib/hwasan/hwasan_interceptors.cpp:252:26
    #4 0xffff88395de4 in __libc_longjmp /mnt/repos/llvm-project/compiler-rt/lib/hwasan/hwasan_interceptors.cpp:296:18
    #1 0xffff883ad174 in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /mnt/repos/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_termination.cpp:78:24
    #5 0xffff881fa800 in unwind_stop /build/glibc-w4ZToO/glibc-2.31/nptl/unwind.c:94:5
    #6 0xffff87ebaae8  (/lib/aarch64-linux-gnu/libgcc_s.so.1+0xdae8)
    #6 0xffff87ebaae8  (/lib/aarch64-linux-gnu/libgcc_s.so.1+0xdae8)
    #6 0xffff87ebaae8  (/lib/aarch64-linux-gnu/libgcc_s.so.1+0xdae8)
    #5 0xffff881fa800 in unwind_stop /build/glibc-w4ZToO/glibc-2.31/nptl/unwind.c:94:5
    #5 0xffff881fa800 in unwind_stop /build/glibc-w4ZToO/glibc-2.31/nptl/unwind.c:94:5
    #5 0xffff881fa800 in unwind_stop /build/glibc-w4ZToO/glibc-2.31/nptl/unwind.c:94:5
    #2 0xffff88390760 in __hwasan_handle_longjmp /mnt/repos/llvm-project/compiler-rt/lib/hwasan/hwasan.cpp:528:3
    #3 0xffff88395de4 in InternalLongjmp /mnt/repos/llvm-project/compiler-rt/lib/hwasan/hwasan_interceptors.cpp:252:26
    #7 0xffff87ebaeec in _Unwind_ForcedUnwind (/lib/aarch64-linux-gnu/libgcc_s.so.1+0xdeec)
    #4 0xffff88395de4 in __libc_longjmp /mnt/repos/llvm-project/compiler-rt/lib/hwasan/hwasan_interceptors.cpp:296:18
    #7 0xffff87ebaeec in _Unwind_ForcedUnwind (/lib/aarch64-linux-gnu/libgcc_s.so.1+0xdeec)
    #7 0xffff87ebaeec in _Unwind_ForcedUnwind (/lib/aarch64-linux-gnu/libgcc_s.so.1+0xdeec)
    #6 0xffff87ebaae8  (/lib/aarch64-linux-gnu/libgcc_s.so.1+0xdae8)
    #7 0xffff87ebaeec in _Unwind_ForcedUnwind (/lib/aarch64-linux-gnu/libgcc_s.so.1+0xdeec)
    #6 0xffff87ebaae8  (/lib/aarch64-linux-gnu/libgcc_s.so.1+0xdae8)
    #2 0xffff88390760 in __hwasan_handle_longjmp /mnt/repos/llvm-project/compiler-rt/lib/hwasan/hwasan.cpp:528:3
    #8 0xffff881fa880 in __pthread_unwind /build/glibc-w4ZToO/glibc-2.31/nptl/unwind.c:121:3
    #5 0xffff881fa800 in unwind_stop /build/glibc-w4ZToO/glibc-2.31/nptl/unwind.c:94:5
    #8 0xffff881fa880 in __pthread_unwind /build/glibc-w4ZToO/glibc-2.31/nptl/unwind.c:121:3
    #8 0xffff881fa880 in __pthread_unwind /build/glibc-w4ZToO/glibc-2.31/nptl/unwind.c:121:3
    #6 0xffff87ebaae8  (/lib/aarch64-linux-gnu/libgcc_s.so.1+0xdae8)
    #8 0xffff881fa880 in __pthread_unwind /build/glibc-w4ZToO/glibc-2.31/nptl/unwind.c:121:3
    #7 0xffff87ebaeec in _Unwind_ForcedUnwind (/lib/aarch64-linux-gnu/libgcc_s.so.1+0xdeec)
    #3 0xffff88395de4 in InternalLongjmp /mnt/repos/llvm-project/compiler-rt/lib/hwasan/hwasan_interceptors.cpp:252:26
    #4 0xffff88395de4 in __libc_longjmp /mnt/repos/llvm-project/compiler-rt/lib/hwasan/hwasan_interceptors.cpp:296:18
    #9 0xffff881f14c8 in __do_cancel /build/glibc-w4ZToO/glibc-2.31/nptl/pthreadP.h:309:3
    #10 0xffff881f14c8 in pthread_exit /build/glibc-w4ZToO/glibc-2.31/nptl/pthread_exit.c:28:3
    #6 0xffff87ebaae8  (/lib/aarch64-linux-gnu/libgcc_s.so.1+0xdae8)
    #9 0xffff881f14c8 in __do_cancel /build/glibc-w4ZToO/glibc-2.31/nptl/pthreadP.h:309:3
    #10 0xffff881f14c8 in pthread_exit /build/glibc-w4ZToO/glibc-2.31/nptl/pthread_exit.c:28:3
    #9 0xffff881f14c8 in __do_cancel /build/glibc-w4ZToO/glibc-2.31/nptl/pthreadP.h:309:3
    #7 0xffff87ebaeec in _Unwind_ForcedUnwind (/lib/aarch64-linux-gnu/libgcc_s.so.1+0xdeec)
    #10 0xffff881f14c8 in pthread_exit /build/glibc-w4ZToO/glibc-2.31/nptl/pthread_exit.c:28:3
    #9 0xffff881f14c8 in __do_cancel /build/glibc-w4ZToO/glibc-2.31/nptl/pthreadP.h:309:3
    #10 0xffff881f14c8 in pthread_exit /build/glibc-w4ZToO/glibc-2.31/nptl/pthread_exit.c:28:3
    #8 0xffff881fa880 in __pthread_unwind /build/glibc-w4ZToO/glibc-2.31/nptl/unwind.c:121:3
    #5 0xffff881fa800 in unwind_stop /build/glibc-w4ZToO/glibc-2.31/nptl/unwind.c:94:5
    #11 0xffff8828f2a4 in pthread_exit /build/glibc-w4ZToO/glibc-2.31/nptl/forward.c:141:1
    #7 0xffff87ebaeec in _Unwind_ForcedUnwind (/lib/aarch64-linux-gnu/libgcc_s.so.1+0xdeec)
    #11 0xffff8828f2a4 in pthread_exit /build/glibc-w4ZToO/glibc-2.31/nptl/forward.c:141:1
    #8 0xffff881fa880 in __pthread_unwind /build/glibc-w4ZToO/glibc-2.31/nptl/unwind.c:121:3
    #11 0xffff8828f2a4 in pthread_exit /build/glibc-w4ZToO/glibc-2.31/nptl/forward.c:141:1
    #9 0xffff881f14c8 in __do_cancel /build/glibc-w4ZToO/glibc-2.31/nptl/pthreadP.h:309:3
    #10 0xffff881f14c8 in pthread_exit /build/glibc-w4ZToO/glibc-2.31/nptl/pthread_exit.c:28:3
    #9 0xffff881f14c8 in __do_cancel /build/glibc-w4ZToO/glibc-2.31/nptl/pthreadP.h:309:3
    #10 0xffff881f14c8 in pthread_exit /build/glibc-w4ZToO/glibc-2.31/nptl/pthread_exit.c:28:3
    #6 0xffff87ebaae8  (/lib/aarch64-linux-gnu/libgcc_s.so.1+0xdae8)
    #12 0x6415b8 in PyThread_exit_thread (/usr/bin/python3.8+0x6415b8)
    #8 0xffff881fa880 in __pthread_unwind /build/glibc-w4ZToO/glibc-2.31/nptl/unwind.c:121:3
    #12 0x6415b8 in PyThread_exit_thread (/usr/bin/python3.8+0x6415b8)
    #11 0xffff8828f2a4 in pthread_exit /build/glibc-w4ZToO/glibc-2.31/nptl/forward.c:141:1
    #12 0x6415b8 in PyThread_exit_thread (/usr/bin/python3.8+0x6415b8)
    #11 0xffff8828f2a4 in pthread_exit /build/glibc-w4ZToO/glibc-2.31/nptl/forward.c:141:1
    #11 0xffff8828f2a4 in pthread_exit /build/glibc-w4ZToO/glibc-2.31/nptl/forward.c:141:1
    #7 0xffff87ebaeec in _Unwind_ForcedUnwind (/lib/aarch64-linux-gnu/libgcc_s.so.1+0xdeec)
    #8 0xffff881fa880 in __pthread_unwind /build/glibc-w4ZToO/glibc-2.31/nptl/unwind.c:121:3
    #9 0xffff881f14c8 in __do_cancel /build/glibc-w4ZToO/glibc-2.31/nptl/pthreadP.h:309:3
    #13 0x60fe10  (/usr/bin/python3.8+0x60fe10)
    #12 0x6415b8 in PyThread_exit_thread (/usr/bin/python3.8+0x6415b8)
    #10 0xffff881f14c8 in pthread_exit /build/glibc-w4ZToO/glibc-2.31/nptl/pthread_exit.c:28:3
    #13 0x60fe10  (/usr/bin/python3.8+0x60fe10)
    #14 0x640f88  (/usr/bin/python3.8+0x640f88)
    #15 0xffff881f04f8 in start_thread /build/glibc-w4ZToO/glibc-2.31/nptl/pthread_create.c:477:8
    #13 0x60fe10  (/usr/bin/python3.8+0x60fe10)
    #9 0xffff881f14c8 in __do_cancel /build/glibc-w4ZToO/glibc-2.31/nptl/pthreadP.h:309:3
    #10 0xffff881f14c8 in pthread_exit /build/glibc-w4ZToO/glibc-2.31/nptl/pthread_exit.c:28:3
    #14 0x640f88  (/usr/bin/python3.8+0x640f88)
    #15 0xffff881f04f8 in start_thread /build/glibc-w4ZToO/glibc-2.31/nptl/pthread_create.c:477:8
    #11 0xffff8828f2a4 in pthread_exit /build/glibc-w4ZToO/glibc-2.31/nptl/forward.c:141:1
    #12 0x6415b8 in PyThread_exit_thread (/usr/bin/python3.8+0x6415b8)
    #12 0x6415b8 in PyThread_exit_thread (/usr/bin/python3.8+0x6415b8)
    #16 0xffff882ebf28  /build/glibc-w4ZToO/glibc-2.31/misc/../sysdeps/unix/sysv/linux/aarch64/clone.S:78
```

**Comment by jiridanek** [comment]
```
$ /usr/bin/python3 "/home/ubuntu/repos/qpid-proton-0.31.0/scripts/env.py" "--" "PATH=/home/ubuntu/repos/qpid-proton-0.31.0/clang/c/tools:/home/ubuntu/repos/qpid-proton-0.31.0/clang/c:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/ubuntu/llvm/install/bin" "SASLPASSWD=/usr/sbin/saslpasswd2" "SWIG=/usr/bin/swig4.0" "UBSAN_OPTIONS=suppressions=/home/ubuntu/repos/qpid-proton-0.31.0/tests/ubsan.supp" "LSAN_OPTIONS=suppressions=/home/ubuntu/repos/qpid-proton-0.31.0/tests/lsan.supp" "/home/ubuntu/repos/qpid-proton-0.31.0/tests/preload_asan.sh" "/home/ubuntu/repos/qpid-proton-0.31.0/clang/c/libqpid-proton-core.so.10.9.0" lldb-10 -- "/usr/bin/python3" "-m" "tox"

[...]

(lldb) breakpoint set --file hwasan.cpp --line 528 -c "((GetTagFromPointer(dst) == 0)) == (0)"
Breakpoint 1: no locations (pending).
WARNING:  Unable to resolve breakpoint to any actual locations.
(lldb) run

[...]

Process 125693 stopped
* thread #2, name = 'python3', stop reason = breakpoint 1.1
    frame #0: 0x0000fffff761f6f4 libclang_rt.hwasan-aarch64.so`::__hwasan_handle_longjmp(sp_dst=0x44e5a2abfe4cfb5c) at hwasan.cpp:528:3
(lldb) l
(lldb) l
(lldb) source list
(lldb) frame variable
(const void *) sp_dst = 0x44e5a2abfe4cfb5c
(__sanitizer::uptr) dst = 4964553023835405148
(__sanitizer::uptr) sp = <variable not available>

(__sanitizer::u64) v1 = <extracting data from value failed>

(lldb) bt
* thread #2, name = 'python3', stop reason = breakpoint 1.1
  * frame #0: 0x0000fffff761f6f4 libclang_rt.hwasan-aarch64.so`::__hwasan_handle_longjmp(sp_dst=0x44e5a2abfe4cfb5c) at hwasan.cpp:528:3
    frame #1: 0x0000fffff7624de8 libclang_rt.hwasan-aarch64.so`::__interceptor___libc_longjmp(__hw_jmp_buf_struct *, int) at hwasan_interceptors.cpp:252:26
    frame #2: 0x0000fffff7624de4 libclang_rt.hwasan-aarch64.so`::__interceptor___libc_longjmp(env=0x0000fffff59519b0, val=1) at hwasan_interceptors.cpp:296
    frame #3: 0x0000fffff7489804 libpthread.so.0`unwind_stop(version=<unavailable>, actions=<unavailable>, exc_class=<unavailable>, exc_obj=<unavailable>, context=0x0000fffff5951540, stop_parameter=0x0000fffff59519b0) at unwind.c:94:5
    frame #4: 0x0000fffff7149aec libgcc_s.so.1`___lldb_unnamed_symbol27$$libgcc_s.so.1 + 60
    frame #5: 0x0000fffff7149ef0 libgcc_s.so.1`_Unwind_ForcedUnwind + 128
    frame #6: 0x0000fffff7489884 libpthread.so.0`__GI___pthread_unwind(buf=0x0000fffff5952600) at unwind.c:121:3
    frame #7: 0x0000fffff74804cc libpthread.so.0`__pthread_exit at pthreadP.h:309:3
    frame #8: 0x0000fffff74804a4 libpthread.so.0`__pthread_exit(value=<unavailable>) at pthread_exit.c:28
    frame #9: 0x0000fffff751e2a8 libc.so.6`pthread_exit + 48
    frame #10: 0x00000000006415bc python3`PyThread_exit_thread at thread_pthread.h:369:5
    frame #11: 0x000000000060fe14 python3`t_bootstrap(boot_raw=0x0000fffff597a5a0) at _threadmodule.c:1021:5
    frame #12: 0x0000000000640f8c python3`pythread_wrapper(arg=<unavailable>) at thread_pthread.h:237:5
    frame #13: 0x0000fffff747f4fc libpthread.so.0`start_thread(arg=0x0000ffffffffd53f) at pthread_create.c:477:8
    frame #14: 0x0000fffff757af2c libc.so.6`___lldb_unnamed_symbol635$$libc.so.6 + 12
(lldb) list
(lldb) s
Process 125693 stopped
* thread #2, name = 'python3', stop reason = step in
    frame #0: 0x0000fffff761f6f8 libclang_rt.hwasan-aarch64.so`::__hwasan_handle_longjmp(sp_dst=0x44e5a2abfe4cfb5c) at hwasan.cpp:525:50
(lldb) frame variable
(const void *) sp_dst = 0x44e5a2abfe4cfb5c
(__sanitizer::uptr) dst = 4964553023835405148
(__sanitizer::uptr) sp = <variable not available>

(lldb) s
Process 125693 stopped
* thread #2, name = 'python3', stop reason = step in
    frame #0: 0x0000fffff761f6fc libclang_rt.hwasan-aarch64.so`::__hwasan_handle_longjmp(sp_dst=0x44e5a2abfe4cfb5c) at hwasan.cpp:528:3
(lldb) bt
* thread #2, name = 'python3', stop reason = step in
  * frame #0: 0x0000fffff761f6fc libclang_rt.hwasan-aarch64.so`::__hwasan_handle_longjmp(sp_dst=0x44e5a2abfe4cfb5c) at hwasan.cpp:528:3
    frame #1: 0x0000fffff7624de8 libclang_rt.hwasan-aarch64.so`::__interceptor___libc_longjmp(__hw_jmp_buf_struct *, int) at hwasan_interceptors.cpp:252:26
    frame #2: 0x0000fffff7624de4 libclang_rt.hwasan-aarch64.so`::__interceptor___libc_longjmp(env=0x0000fffff59519b0, val=1) at hwasan_interceptors.cpp:296
    frame #3: 0x0000fffff7489804 libpthread.so.0`unwind_stop(version=<unavailable>, actions=<unavailable>, exc_class=<unavailable>, exc_obj=<unavailable>, context=0x0000fffff5951540, stop_parameter=0x0000fffff59519b0) at unwind.c:94:5
    frame #4: 0x0000fffff7149aec libgcc_s.so.1`___lldb_unnamed_symbol27$$libgcc_s.so.1 + 60
    frame #5: 0x0000fffff7149ef0 libgcc_s.so.1`_Unwind_ForcedUnwind + 128
    frame #6: 0x0000fffff7489884 libpthread.so.0`__GI___pthread_unwind(buf=0x0000fffff5952600) at unwind.c:121:3
    frame #7: 0x0000fffff74804cc libpthread.so.0`__pthread_exit at pthreadP.h:309:3
    frame #8: 0x0000fffff74804a4 libpthread.so.0`__pthread_exit(value=<unavailable>) at pthread_exit.c:28
    frame #9: 0x0000fffff751e2a8 libc.so.6`pthread_exit + 48
    frame #10: 0x00000000006415bc python3`PyThread_exit_thread at thread_pthread.h:369:5
    frame #11: 0x000000000060fe14 python3`t_bootstrap(boot_raw=0x0000fffff597a5a0) at _threadmodule.c:1021:5
    frame #12: 0x0000000000640f8c python3`pythread_wrapper(arg=<unavailable>) at thread_pthread.h:237:5
    frame #13: 0x0000fffff747f4fc libpthread.so.0`start_thread(arg=0x0000ffffffffd53f) at pthread_create.c:477:8
    frame #14: 0x0000fffff757af2c libc.so.6`___lldb_unnamed_symbol635$$libc.so.6 + 12
(lldb) frame variable
(const void *) sp_dst = 0x44e5a2abfe4cfb5c
(__sanitizer::uptr) dst = 4964553023835405148
(__sanitizer::uptr) sp = <variable not available>

(__sanitizer::u64) v1 = <extracting data from value failed>

(lldb) s
Process 125693 stopped
* thread #2, name = 'python3', stop reason = step in
    frame #0: 0x0000fffff763c120 libclang_rt.hwasan-aarch64.so`__sanitizer::CheckFailed(file="/mnt/repos/llvm-project/compiler-rt/lib/hwasan/hwasan.cpp", line=528, cond="((GetTagFromPointer(dst) == 0)) != (0)", v1=0, v2=0) at sanitizer_termination.cpp:72
(lldb) bt
* thread #2, name = 'python3', stop reason = step in
  * frame #0: 0x0000fffff763c120 libclang_rt.hwasan-aarch64.so`__sanitizer::CheckFailed(file="/mnt/repos/llvm-project/compiler-rt/lib/hwasan/hwasan.cpp", line=528, cond="((GetTagFromPointer(dst) == 0)) != (0)", v1=0, v2=0) at sanitizer_termination.cpp:72
    frame #1: 0x0000fffff761f764 libclang_rt.hwasan-aarch64.so`::__hwasan_handle_longjmp(sp_dst=<unavailable>) at hwasan.cpp:528:3
    frame #2: 0x0000fffff7624de8 libclang_rt.hwasan-aarch64.so`::__interceptor___libc_longjmp(__hw_jmp_buf_struct *, int) at hwasan_interceptors.cpp:252:26
    frame #3: 0x0000fffff7624de4 libclang_rt.hwasan-aarch64.so`::__interceptor___libc_longjmp(env=0x0000fffff59519b0, val=1) at hwasan_interceptors.cpp:296
    frame #4: 0x0000fffff7489804 libpthread.so.0`unwind_stop(version=<unavailable>, actions=<unavailable>, exc_class=<unavailable>, exc_obj=<unavailable>, context=0x0000fffff5951540, stop_parameter=0x0000fffff59519b0) at unwind.c:94:5
    frame #5: 0x0000fffff7149aec libgcc_s.so.1`___lldb_unnamed_symbol27$$libgcc_s.so.1 + 60
    frame #6: 0x0000fffff7149ef0 libgcc_s.so.1`_Unwind_ForcedUnwind + 128
    frame #7: 0x0000fffff7489884 libpthread.so.0`__GI___pthread_unwind(buf=0x0000fffff5952600) at unwind.c:121:3
    frame #8: 0x0000fffff74804cc libpthread.so.0`__pthread_exit at pthreadP.h:309:3
    frame #9: 0x0000fffff74804a4 libpthread.so.0`__pthread_exit(value=<unavailable>) at pthread_exit.c:28
    frame #10: 0x0000fffff751e2a8 libc.so.6`pthread_exit + 48
    frame #11: 0x00000000006415bc python3`PyThread_exit_thread at thread_pthread.h:369:5
    frame #12: 0x000000000060fe14 python3`t_bootstrap(boot_raw=0x0000fffff597a5a0) at _threadmodule.c:1021:5
    frame #13: 0x0000000000640f8c python3`pythread_wrapper(arg=<unavailable>) at thread_pthread.h:237:5
    frame #14: 0x0000fffff747f4fc libpthread.so.0`start_thread(arg=0x0000ffffffffd53f) at pthread_create.c:477:8
    frame #15: 0x0000fffff757af2c libc.so.6`___lldb_unnamed_symbol635$$libc.so.6 + 12
(lldb) frame variable
(const char *) file = 0x0000fffff764dea0 "/mnt/repos/llvm-project/compiler-rt/lib/hwasan/hwasan.cpp"
(int) line = 528
(const char *) cond = 0x0000fffff764df60 "((GetTagFromPointer(dst) == 0)) != (0)"
(__sanitizer::u64) v1 = 0
(__sanitizer::u64) v2 = 0
```

**Comment by eugenis** [comment]
```
/build/glibc-oCLvUT/glibc-2.29/csu/../csu/libc-start.c:295
   26b69:       48 8d 7c 24 20          lea    0x20(%rsp),%rdi
   26b6e:       e8 3d 30 01 00          callq  39bb0 <_setjmp@@GLIBC_2.2.5>
```
That's a non-plt call from __libc_start_main to _setjmp that can not be intercepted.
Longjmp interceptor then sees the actual libc __jmpbuf instead of __hw_jmp_buf.
```
(const void *) sp_dst = 0x44e5a2abfe4cfb5c
```
Ouch.
It looks like the whole approach to intercepting longjmp on linux does not work. Or, maybe, there could be a targeted fix, but I don't see it yet.

**Comment by eugenis** [comment]
original change: https://reviews.llvm.org/D69045
