### ISSUE TITLE
Spurious use-of-uninitialized-value on thread_local storage in loaded library

### ISSUE THREAD

**Issue by krockot** [google/sanitizers#1265]
MSan complains about the use of an uninitialized value when accessing a thread_local static within a dynamically loaded library, but the memory is clearly initialized.

Repro [example](https://gist.github.com/krockot/de3c87c13dcfb001cb4686ebac55c40a)

**Comment by tanderson-google** [comment]
We're encountering this issue in Chromium when upgrading our CI bots from Ubuntu 16.04 and 18.04 to 20.04.  The issue appears to be caused by the kernel upgrade.

Ubuntu 16.04 libraries on 4.4 kernel: issue is not present
Ubuntu 16.04 libraries on 4.4 kernel: issue is not present
Ubuntu 16.04 libraries on 4.4 kernel: issue is not present

**Comment by tanderson-google** [comment]
We're encountering this issue in Chromium when upgrading our CI bots from Ubuntu 18.04 to 20.04.  The issue appears to be caused by the kernel upgrade.

Ubuntu 18.04 libraries on 4.15 kernel: issue is not present
Ubuntu 18.04 libraries on 5.4 kernel: issue is present
Ubuntu 20.04 libraries on 5.4 kernel: issue is present

**Comment by thurstond** [comment]
"Fix tls_get_addr handling for glibc >=2.25" (https://reviews.llvm.org/D147459) landed in LLVM upstream this morning. I tested that it passes krockot's repro example (very useful, thanks! :-) from comment 1:

Before:
```
thurston@sesamestreet:/tmp/de3c87c13dcfb001cb4686ebac55c40a-91509a59236b8c0603324bc7240c4d6973467136$ make
clang++ -std=c++11 -fsanitize=memory -g -fno-omit-frame-pointer -fPIC -shared tls_test_lib.cc -olibtls_test.so
clang++ -std=c++11 -fsanitize=memory -g -fno-omit-frame-pointer tls_test.cc -ldl -otls_test
thurston@sesamestreet:/tmp/de3c87c13dcfb001cb4686ebac55c40a-91509a59236b8c0603324bc7240c4d6973467136$ ./tls_test
AAA
BBB
CCC
Uninitialized bytes in __interceptor_write at offset 0 inside [0x701000000000, 4)
==885751==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7fb0390321cf in go /tmp/de3c87c13dcfb001cb4686ebac55c40a-91509a59236b8c0603324bc7240c4d6973467136/tls_test_lib.cc:14:9
    #1 0x558301fad4ce in main /tmp/de3c87c13dcfb001cb4686ebac55c40a-91509a59236b8c0603324bc7240c4d6973467136/tls_test.cc:11:3
    #2 0x7fb038b67189 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #3 0x7fb038b67244 in __libc_start_main csu/../csu/libc-start.c:381:3
    #4 0x558301f252a0 in _start (/tmp/de3c87c13dcfb001cb4686ebac55c40a-91509a59236b8c0603324bc7240c4d6973467136/tls_test+0x222a0) (BuildId: 8501789aa71f6f29d4c098d647eea5441ac8bd25)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /tmp/de3c87c13dcfb001cb4686ebac55c40a-91509a59236b8c0603324bc7240c4d6973467136/tls_test_lib.cc:14:9 in go
Exiting
```

After:
```
de3c87c13dcfb001cb4686ebac55c40a-91509a59236b8c0603324bc7240c4d6973467136$ export PATH=~/llvm-projectD/build/bin:$PATH
thurston@sesamestreet:/tmp/de3c87c13dcfb001cb4686ebac55c40a-91509a59236b8c0603324bc7240c4d6973467136$ make clean
rm -f tls_test libtls_test.so
thurston@sesamestreet:/tmp/de3c87c13dcfb001cb4686ebac55c40a-91509a59236b8c0603324bc7240c4d6973467136$ make
clang++ -std=c++11 -fsanitize=memory -g -fno-omit-frame-pointer -fPIC -shared tls_test_lib.cc -olibtls_test.so
.clang++ -std=c++11 -fsanitize=memory -g -fno-omit-frame-pointer tls_test.cc -ldl -otls_test
/tlsthurston@sesamestreet:/tmp/de3c87c13dcfb001cb4686ebac55c40a-91509a59236b8c0603324bc7240c4d6973467136$ ./tls_test 
AAA
BBB
CCC
thurston@sesamestreet:/tmp/de3c87c13dcfb001cb4686ebac55c40a-91509a59236b8c0603324bc7240c4d6973467136$ 
```
