### ISSUE TITLE
AddressSanitizer failed to allocate 0x7d7d7d7d7d7d3000 bytes

### ISSUE THREAD

**Issue by magicsupery** [google/sanitizers#1317]
i write a lua c module test.so, which static link grpc.a, i build the test.so with asan, but not build it with grpc. when i run my lua script,i got this error, do i need to build the grpc.a with asan static?

i am sure that the version with no asan malloc  size is not that big!

here is the full info
============
==1896==WARNING: AddressSanitizer failed to allocate 0x7d7d7d7d7d7d3000 bytes
==1896==AddressSanitizer's allocator is terminating the process instead of returning 0
==1896==If you don't like this behavior set allocator_may_return_null=1
==1896==AddressSanitizer CHECK failed: ../../../../libsanitizer/sanitizer_common/sanitizer_allocator.cc:218 "((0)) != (0)" (0x0, 0x0)
    #0 0x7fb492caf952  (/lib64/libasan.so.4+0xe9952)
    #1 0x7fb492cce2e5 in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) (/lib64/libasan.so.4+0x1082e5)
    #2 0x7fb492cb5092  (/lib64/libasan.so.4+0xef092)
    #3 0x7fb492bedb96  (/lib64/libasan.so.4+0x27b96)
    #4 0x7fb492ca486a in malloc (/lib64/libasan.so.4+0xde86a)
    #5 0x7fb48d8d6dec in gpr_malloc /data/work/phonest_core/3rdparty/source/grpc/src/core/lib/gpr/alloc.cc:32
    #6 0x7fb48d76842b in grpc::CoreCodegen::gpr_malloc(unsigned long) /data/work/phonest_core/3rdparty/source/grpc/src/cpp/common/core_codegen.cc:77
    #7 0x7fb48cd240f5 in grpc::internal::FillMetadataArray(std::multimap<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, unsigned long*, std::string const&) /data/work/phonest_core/3rdparty/install/include/grpcpp/impl/codegen/call_op_set.h:62
    #8 0x7fb48cd24d7d in grpc::internal::CallOpSendInitialMetadata::AddOp(grpc_op*, unsigned long*) /data/work/phonest_core/3rdparty/install/include/grpcpp/impl/codegen/call_op_set.h:243

============================================

**Comment by ramosian-glider** [comment]
You may want to take a look at https://github.com/grpc/grpc/issues/21838

**Comment by magicsupery** [comment]
> You may want to take a look at [grpc/grpc#21838](https://github.com/grpc/grpc/issues/21838)

thanks a lot!! i will rebuild grpc with sanitize=address

**Comment by wxzcyy** [comment]
> > You may want to take a look at [grpc/grpc#21838](https://github.com/grpc/grpc/issues/21838)
> 
> thanks a lot!! i will rebuild grpc with sanitize=address

Do you solve the problem? I had the same problem and I rebuild grpc with santize=address. However, it doest't work.
