### ISSUE TITLE
LSAN hangs after call to __lsan_do_leak_check when attempting to acquire mutex

### ISSUE THREAD

**Issue by ppettina** [google/sanitizers#1330]
We have a set of tests that works fine almost all the time, however, sporadically (about 1% of the time) they hang at exit when built with LSAN support. Process list (during the hang) is as follows:

```
$ ps ax
  PID TTY      STAT   TIME COMMAND
...
 2774 pts/0    tl+    0:00 /path/to/test/binary   # <-- tracee, note `t` in the STAT column
 3445 pts/0    Z+     0:00 [llvm-symbolizer] <defunct>
 3466 pts/0    S+     0:00 /path/to/test/binary   # <-- tracer
... 
```

Attaching with GDB to the "tracer" process yields **consistently** the following backtrace:
```
(gdb) bt
#0  0x0000562b84df099e in __sanitizer::BlockingMutex::Lock() () at /path/to/test/source
#1  0x0000562b84dd74d3 in __asan::AppendToErrorMessageBuffer(char const*) () at /path/to/test/source
#2  0x0000562b84df34ba in __sanitizer::SharedPrintfCode(bool, char const*, __va_list_tag*) () at /path/to/test/source
#3  0x0000562b84df3634 in __sanitizer::Report(char const*, ...) () at /path/to/test/source
#4  0x0000562b84dffd81 in __lsan::CheckForLeaksCallback(__sanitizer::SuspendedThreadsList const&, void*) () at /path/to/test/source
#5  0x0000562b84dfc426 in __sanitizer::TracerThread(void*) () at /path/to/test/source
#6  0x0000562b84df1500 in __sanitizer::internal_clone(int (*)(void*), void*, int, void*, int*, void*, int*) () at /path/to/test/source
#7  0x0000000000000000 in ?? ()
```

This is the only thread running in the "tracer" process.
Attaching to the "tracee" is impossible.
by using `disas` and sysdig I can tell the "tracer" is probably stuck in the futex loop as of the linux implementation of [BlockingMutex::Lock()](https://github.com/llvm/llvm-project/blob/7ce4dfb4dd2ca431f17b62ef563cc3b2737c677e/compiler-rt/lib/sanitizer_common/sanitizer_linux.cpp#L661)

A non-expert look at the lsan code tells me that this kind of deadlock is impossible (I hope I am wrong) so this is thoroughly puzzling for me.

Additional information:

We use the following options:
```
  export LSAN_OPTIONS="verbosity=1 log_threads=1 suppressions=/path/to/lsan_suppress.txt"
  export ASAN_OPTIONS="symbolize=1 fast_unwind_on_malloc=1"
```

These tests use the GTest framework, which is wrapped around in something like:
```
[[noreturn]] static inline void safe_exit(int ret)
{
  __lsan_do_leak_check();
  // quick_exit as we use a lot of multithreaded modules that don't terminate cleanly.
  std::quick_exit(ret);
}

...
safe_exit(RUN_ALL_TESTS());
```

`RUN_ALL_TESTS` returns an int which is then propagated as the exit code.

The tests run in a docker container and are built with clang. We have seen the issue with container images based on:
- Ubuntu Xenial (running Clang 5.0)
- Ubuntu Bionic (running Clang 10.0)

Our build machines are running CoreOS and FCOS, respectively using kernel 4.19 and 5.8.
We have seen the issue on:
- VMs provisioned on OpenStack (QEMU backend)
- VMs provisioned on VMWare VSphere
- Bare-metal machines

Please advise if I can add useful information, or where to look for further clues.

**Comment by ppettina** [comment]
Further to this, manually unlocking the mutex in gdb after attaching to the tracer:
```
set *(int*)$rdi = 0
cont
```
makes it continue till it terminates successfully.
