### ISSUE TITLE
Unsigned Integer Overflow when comparing strings (|s1|<|s2|)

### ISSUE THREAD

**Issue by jerryc05** [google/sanitizers#1346]
Sample code:
```cpp
bool b = std::string() < "1";
```
produced output: (`clang 11, -std=c++20`)
```
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/basic_string.h:403:51: runtime error: unsigned integer overflow: 0 - 1 cannot be represented in type 'unsigned long'
    #0 0x428a8e in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_compare(unsigned long, unsigned long) /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/basic_string.h:403:51
    #1 0x42870c in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/basic_string.tcc:1429:8
    #2 0x4273b7 in decltype(__detail::__char_traits_cmp_cat<std::char_traits<char> >(0)) std::operator<=><char, std::char_traits<char>, std::allocator<char> >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*) /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/basic_string.h:6216:61
    #3 0x4271f5 in main ***
    #4 0x7f13e917dcc9 in __libc_start_main csu/../csu/libc-start.c:308:16

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/basic_string.h:403:51 in 
```

**Comment by dvyukov** [comment]
This is a bug in libstdc++, right? Please report it to libstdc++.

**Comment by jwakely** [comment]
No, it's not a bug in libstdc++. The code relies on the behaviour that the C++ standard specifies. Diagnosing it as UB is the bug.

**Comment by jwakely** [comment]
Is there a way for libstdc++ to globally disable this stupid sanitizer? I never want to get another "unsigned integer overflow" "bug" report.

**Comment by dvyukov** [comment]
I agree this is not UB. SUMMARY is imprecisely worded.
