### ISSUE TITLE
ASAN_OPTIONS=allocator_may_return_null=1 is ignored

### ISSUE THREAD

**Issue by nolden** [google/sanitizers#1377]
I did set ASAN_OPTIONS=allocator_may_return_null=1 but I still get this output:

==72449==ERROR: AddressSanitizer: allocator is out of memory trying to allocate 0x7f09ece28d01 bytes
    #0 0x7f09f51d8bb7 in operator new(unsigned long) (/lib64/libasan.so.6+0xacbb7)
    #1 0x7f09f47fd371 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (/lib64/libstdc++.so.6+0x141371)
    #2 0x7f09ece28cff  (/home/nolden/Qt/5.15.2/gcc_64/lib/libQt5WebEngineCore.so.5+0xddacff)

==72449==HINT: if you don't care about these errors you may set allocator_may_return_null=1
SUMMARY: AddressSanitizer: out-of-memory (/lib64/libasan.so.6+0xacbb7) in operator new(unsigned long)
==72449==ABORTING

**Comment by hbsun2113** [comment]
I met the same issue

**Comment by Mem2019** [comment]
For my case, it seems that this option is ignored when `new []` is used for allocation.

**Comment by nsmithtt** [comment]
+1

**Comment by shiyu-ren** [comment]
+1. Did you solve this problem?
