### ISSUE TITLE
ASan doesn't allow passing local variable as address in thread?

### ISSUE THREAD

**Issue by espelancer** [google/sanitizers#1399]
I got the following error message from ASan if I pass a local variable as address and assign value in another static function in a thread. The message shows when running pthread_join.
```
=================================================================
==2409421==AddressSanitizer CHECK failed: /home/engshare/third-party2/llvm-fb/9.0.0/src/llvm/compiler-rt/lib/asan/asan_thread.cc:371 "((ptr[0] == kCurrentStackFrameMagic)) != (0)" (0x0, 0x0)
    #0 0x4c6fc7 in __asan::AsanCheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) (/data/users/espelancer/ovrsource/a.out+0x4c6fc7)
    #1 0x4defc6 in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) (/data/users/espelancer/ovrsource/a.out+0x4defc6)
    #2 0x4cbaec in __asan::AsanThread::GetStackFrameAccessByAddr(unsigned long, __asan::AsanThread::StackFrameAccess*) (/data/users/espelancer/ovrsource/a.out+0x4cbaec)
    #3 0x42db17 in __asan::AddressDescription::AddressDescription(unsigned long, unsigned long, bool) (/data/users/espelancer/ovrsource/a.out+0x42db17)
    #4 0x430121 in __asan::ErrorGeneric::ErrorGeneric(unsigned int, unsigned long, unsigned long, unsigned long, unsigned long, bool, unsigned long) (/data/users/espelancer/ovrsource/a.out+0x430121)
    #5 0x4c6adb in __asan::ReportGenericError(unsigned long, unsigned long, unsigned long, unsigned long, bool, unsigned long, unsigned int, bool) (/data/users/espelancer/ovrsource/a.out+0x4c6adb)
    #6 0x496926 in __interceptor_sigaltstack.part.0 (/data/users/espelancer/ovrsource/a.out+0x496926)
    #7 0x4e0ce9 in __sanitizer::UnsetAlternateSignalStack() (/data/users/espelancer/ovrsource/a.out+0x4e0ce9)
    #8 0x4cb0dc in __asan::AsanThread::Destroy() (/data/users/espelancer/ovrsource/a.out+0x4cb0dc)
    #9 0x7f4f445ed3d0 in __nptl_deallocate_tsd.part.8 (/lib64/libpthread.so.0+0x73d0)
    #10 0x7f4f445ee16a in start_thread (/lib64/libpthread.so.0+0x816a)
    #11 0x7f4f43977db2 in clone (/lib64/libc.so.6+0xfcdb2)
```

Here is my minimal test code 
```
#include <unistd.h>
#include <stdio.h>
#include <pthread.h>

static void tempOtherFunction(long *const pxListWasEmpty)
{
    *pxListWasEmpty = 0L;
}

static void *prvTimerTaskInline(void *pvParameters)
{
    long xListWasEmpty;
    (void)pvParameters;

    tempOtherFunction(&xListWasEmpty);

    while (1)
    {
        sleep(100);
    }
    return NULL;
}

int main(int argc, char **argv)
{
    pthread_t pthread;
    pthread_attr_t xThreadAttributes;

    pthread_attr_init(&xThreadAttributes);

    pthread_create(&pthread, &xThreadAttributes, prvTimerTaskInline, NULL);

    pthread_cancel(pthread);
    pthread_join(pthread, NULL);
}
```

The commend I use is 
```
clang  -O1 -g -fsanitize=address -fno-omit-frame-pointer asan_test.cpp
```
My clang version is
```
clang version 9.0.20190721 
Target: x86_64-unknown-linux-gnu
Thread model: posix
```

If I copy the content of `tempOtherFunction` into `prvTimerTaskInline`, or move xListWasEmpty to heap, ASan will not complain anymore. I wonder is there an issue of the existing code, or it is a bug in ASan?

**Comment by vitalybuka** [comment]
With noinline it's reproducible on HEAD (0e6f934cc3a70ecc40179869457c826ea4dcb4e2) as well 

```
#include <unistd.h>
#include <stdio.h>
#include <pthread.h>

__attribute__((noinline)) 
static void tempOtherFunction(long *const pxListWasEmpty)
{
    *pxListWasEmpty = 0L;
}

__attribute__((noinline)) 
static void *prvTimerTaskInline(void *pvParameters)
{
    long xListWasEmpty;
    (void)pvParameters;

    tempOtherFunction(&xListWasEmpty);

    while (1)
    {
        sleep(100);
    }
    return NULL;
}

int main(int argc, char **argv)
{
    pthread_t pthread;
    pthread_attr_t xThreadAttributes;

    pthread_attr_init(&xThreadAttributes);

    pthread_create(&pthread, &xThreadAttributes, prvTimerTaskInline, NULL);

    pthread_cancel(pthread);
    pthread_join(pthread, NULL);
}
```

```
[341/341] Linking CXX shared library lib/clang/13.0.0/lib/linux/libclang_rt.asan-i386.so
=================================================================
==4056989==ERROR: AddressSanitizer: stack-buffer-underflow on address 0x7f787dffedf0 at pc 0x0000004791bf bp 0x7f787dffedc0 sp 0x7f787dffe588
WRITE of size 24 at 0x7f787dffedf0 thread T16777215
    #0 0x4791be in sigaltstack /usr/local/google/home/vitalybuka/src/llvm.git/llvm-project/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:9986:5
    #1 0x4b73ac in __sanitizer::UnsetAlternateSignalStack() /usr/local/google/home/vitalybuka/src/llvm.git/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_posix_libcdep.cpp:191:3
    #2 0x4a3884 in __asan::AsanThread::Destroy() /usr/local/google/home/vitalybuka/src/llvm.git/llvm-project/compiler-rt/lib/asan/asan_thread.cpp:110:7
    #3 0x7f78818eacd0 in __nptl_deallocate_tsd nptl/pthread_create.c:301:8
    #4 0x7f78818eacd0 in __nptl_deallocate_tsd nptl/pthread_create.c:250:1
    #5 0x7f78818eaeb9 in start_thread nptl/pthread_create.c:488:3
    #6 0x7f78816abdee in clone misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Address 0x7f787dffedf0 is a wild pointer.
SUMMARY: AddressSanitizer: stack-buffer-underflow /usr/local/google/home/vitalybuka/src/llvm.git/llvm-project/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:9986:5 in sigaltstack
Shadow bytes around the buggy address:
  0x0fef8fbf7d60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fef8fbf7d70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fef8fbf7d80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fef8fbf7d90: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fef8fbf7da0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0fef8fbf7db0: 00 00 00 00 00 00 00 00 00 00 00 00 f1 f1[f1]f1
  0x0fef8fbf7dc0: 00 f3 f3 f3 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fef8fbf7dd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fef8fbf7de0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fef8fbf7df0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fef8fbf7e00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==4056989==ABORTING

```

**Comment by vitalybuka** [comment]
I believe it's a bug in Asan we handle pthread_cancel incorrectly.

**Comment by pobrn** [comment]
I think I have run into the same (or at least very similar) issue:

The following code:

```c
#include <stdio.h>
#include <pthread.h>
#include <unistd.h>

__attribute__((noinline))
static void cleanup(void *)
{
	printf("HELLO WORLD\n");
}

__attribute__((noinline))
static void some_stuff(void)
{
	char buffer[4096];
	read(STDIN_FILENO, buffer, sizeof(buffer));
}

static void *thread_func(void *)
{
	pthread_cleanup_push(cleanup, NULL);
	some_stuff();
	pthread_cleanup_pop(0);

	return NULL;
}

int main()
{
	pthread_t t;
	pthread_create(&t, NULL, thread_func, NULL);
	sleep(1);
	pthread_cancel(t);
	sleep(1);
	pthread_join(t, NULL);
}
```

compiled with:

```
gcc -Og -ggdb3 -fsanitize=address,undefined test.c -pthread
```

generates the following output:

```
HELLO WORLD
=================================================================
==2070321==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7f39743fec50 at pc 0x7f39769eb3cb bp 0x7f39743fec20 sp 0x7f39743fe3d8
WRITE of size 24 at 0x7f39743fec50 thread T1
    #0 0x7f39769eb3ca in __interceptor_sigaltstack /usr/src/debug/gcc/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:10168
    #1 0x7f3976a55ac4 in __asan::PlatformUnpoisonStacks() /usr/src/debug/gcc/libsanitizer/asan/asan_posix.cpp:44
    #2 0x7f3976a5cd3d in __asan_handle_no_return /usr/src/debug/gcc/libsanitizer/asan/asan_rtl.cpp:606
    #3 0x5640a6df94dd in thread_func test.c:20
    #4 0x7f39761d954c  (/usr/lib/libc.so.6+0x8c54c)
    #5 0x7f397625eb13 in clone (/usr/lib/libc.so.6+0x111b13)

Address 0x7f39743fec50 is located in stack of thread T1 at offset 4192 in frame
    #0 0x5640a6df929d in some_stuff test.c:13

  This frame has 1 object(s):
    [32, 4128) 'buffer' (line 14) <== Memory access at offset 4192 overflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
Thread T1 created by T0 here:
    #0 0x7f39769f5207 in __interceptor_pthread_create /usr/src/debug/gcc/libsanitizer/asan/asan_interceptors.cpp:207
    #1 0x5640a6df95b4 in main test.c:30

SUMMARY: AddressSanitizer: stack-buffer-overflow /usr/src/debug/gcc/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:10168 in __interceptor_sigaltstack
Shadow bytes around the buggy address:
  0x0fe7ae877d30: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe7ae877d40: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe7ae877d50: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe7ae877d60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe7ae877d70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0fe7ae877d80: 00 00 f3 f3 f3 f3 f3 f3 f3 f3[f3]f3 f3 f3 f3 f3
  0x0fe7ae877d90: f3 f3 00 00 00 00 00 00 00 00 00 00 00 00 f1 f1
  0x0fe7ae877da0: f1 f1 f1 f1 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe7ae877db0: 00 f3 f3 f3 f3 f3 00 00 00 00 00 00 00 00 00 00
  0x0fe7ae877dc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe7ae877dd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==2070321==ABORTING
```

The `__asan_handle_no_return` handle call is being inserted before the `__pthread_unwind_next()` call. This is what `thread_func` looks like after the preprocessor:
```c
static void *thread_func(void *)
{
	do {
		__pthread_unwind_buf_t __cancel_buf;
		void (*__cancel_routine) (void *) = (cleanup);
		void *__cancel_arg = (((void *)0));
		int __not_first_call = __sigsetjmp_cancel (__cancel_buf.__cancel_jmp_buf, 0);
		if (__builtin_expect ((__not_first_call), 0)) {
			__cancel_routine (__cancel_arg);
			__pthread_unwind_next (&__cancel_buf);
		}
		__pthread_register_cancel (&__cancel_buf);
		
		do {
 			some_stuff();
			
			do { } while (0);
		} while (0);
		
		__pthread_unregister_cancel (&__cancel_buf);
		if (0)
			__cancel_routine (__cancel_arg);
	} while (0);
 	
	 return ((void *)0);
}
```

```x86asm
    14d4:       e8 a0 fd ff ff          call   1279 <cleanup>
    14d9:       e8 02 fc ff ff          call   10e0 <__asan_handle_no_return@plt>
    14de:       48 8b 7c 24 08          mov    rdi,QWORD PTR [rsp+0x8]
    14e3:       48 81 ef b0 00 00 00    sub    rdi,0xb0
    14ea:       e8 51 fb ff ff          call   1040 <__pthread_unwind_next@plt>
```

**Comment by Enna1** [comment]
I can not reproduce this on latest clang, it seems we have fixed this?
https://godbolt.org/z/bo7bPTxhY
