### ISSUE TITLE
Failure when executing LeakSanitizer in a QEMU environment

### ISSUE THREAD

**Issue by fetzerch** [google/sanitizers#1413]
I'm encountering an issue when I try to run a cross compiled binary with *LeakSanitizer* enabled through *qemu-user*.

Minimal example that shows the issue:

```
$ cat memory-leak.c
#include <stdlib.h>
void *p;
int main() {
    p = malloc(7);
    p = 0; // The memory is leaked here.
    return 0;
}
```

```
$ /opt/sysroots/x86_64-pokysdk-linux/usr/bin/clang \
        -fuse-ld=lld \
        --target=aarch64-poky-linux \
        --sysroot=/opt/sysroots/aarch64-poky-linux \
        -fsanitize=address \
        memory-leak.c
```

```
$ QEMU_STRACE=1 ASAN_OPTIONS=detect_leaks=1 qemu-aarch64 ./a.out

....
82 mmap(NULL,2101248,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANONYMOUS,-1,0) = 0x0000005504b9f000
82 mprotect(0x0000005504b9f000,4096,PROT_NONE) = 0
82 rt_sigprocmask(SIG_BLOCK,0x00000000004ada30,0x00000000004adab0) = 0
82 clone(CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_UNTRACED,child_stack=0x0000005504d9fff0,parent_tidptr=0x0000000000000000,tls=0x0000000000000000,child_tidptr=0x0000000000000000) = -1 errno=22 (Invalid argument)
82 rt_sigprocmask(SIG_SETMASK,0x00000000004adab0,NULL) = 0
82 munmap(0x0000005504b9f000,2101248) = 0
82 getpid() = 82
==82==LeakSanitizer has encountered a fatal error.
82 write(2,0x7feae0,51) = 51
82 mmap(NULL,65536,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANONYMOUS,-1,0) = 0x0000005504da0000
82 getpid() = 82
==82==HINT: For debugging, try setting environment variable LSAN_OPTIONS=verbosity=1:log_threads=1
82 write(2,0x7feae0,99) = 99
82 getpid() = 82
==82==HINT: LeakSanitizer does not work under ptrace (strace, gdb, etc)
82 write(2,0x7feae0,72) = 72
82 exit_group(1)
```

Digging a bit deeper, it seems that this is caused by the call to [`clone(... | CLONE_UNTRACED)` in `StopTheWorld()`](https://github.com/llvm/llvm-project/blob/d480f968ad8b56d3ee4a6b6df5532d485b0ad01e/compiler-rt/lib/sanitizer_common/sanitizer_stoptheworld_linux_libcdep.cpp#L433).
I found [this QEMU bug report from 2017](https://bugs.launchpad.net/qemu/+bug/1727737/comments/4) where the QEMU team claimed that they cannot support `CLONE_UNTRACED`.

I'm wondering if there's anything which can be done in the *LeakSanitizer* to avoid this problem and thus would allow to run *LeakSanitizer* with QEMU. This would really help in situations where we don't have an easy access to target hardware, such as in CI.

Note that *AddressSanitizer* itself is not affected and disabling *LeakSanitizer* with `ASAN_OPTIONS=detect_leaks=0` will allow to run the binary - but it won't detect the memory leak any more.

**Comment by vitalybuka** [comment]
Have you tried to run without CLONE_UNTRACED, does this work?

@ramosian-glider How important to have CLONE_UNTRACED here? Existing tests do not care.

Unrelated, but last time I tried qemu-user crashed on asan process with uncontrolled grows of RSS.

**Comment by kanje** [comment]
Removing `CLONE_UNTRACED` does not help. However, based on [this note](https://github.com/qemu/qemu/blob/master/linux-user/syscall.c#L149-L154) I have applied this patch and the "fatal error" went away:

```
diff --git a/compiler-rt/lib/sanitizer_common/sanitizer_stoptheworld_linux_libcdep.cpp b/compiler-rt/lib/sanitizer_common/sanitizer_stoptheworld_linux_libcdep.cpp
index 651d5056dd9d..e0a96b603715 100644
--- a/compiler-rt/lib/sanitizer_common/sanitizer_stoptheworld_linux_libcdep.cpp
+++ b/compiler-rt/lib/sanitizer_common/sanitizer_stoptheworld_linux_libcdep.cpp
@@ -430,7 +430,7 @@ void StopTheWorld(StopTheWorldCallback callback, void *argument) {
   CHECK_EQ(rv, 0);
   uptr tracer_pid = internal_clone(
       TracerThread, tracer_stack.Bottom(),
-      CLONE_VM | CLONE_FS | CLONE_FILES | CLONE_UNTRACED,
+      CLONE_VM | CLONE_FS | CLONE_FILES | CLONE_SIGHAND | CLONE_THREAD | CLONE_SYSVSEM,
       &tracer_thread_argument, nullptr /* parent_tidptr */,
       nullptr /* newtls */, nullptr /* child_tidptr */);
   internal_sigprocmask(SIG_SETMASK, &old_sigset, 0);
```

However, even though it runs, it does not detect any memory leaks. For example, here is the output difference between aarch64 (via qemu) and x86_64:

```
==14465==Installed the sigaction for signal 11
==14465==Installed the sigaction for signal 7
==14465==Installed the sigaction for signal 8
```

```
==14450==Installed the sigaction for signal 11
==14450==Installed the sigaction for signal 7
==14450==Installed the sigaction for signal 8
==14451==Processing thread 14450.
==14451==Stack at 0x7fff3191f000-0x7fff3211f000 (SP = 0x7fff3211c928).
==14451==TLS at 0x7f95f6a27000-0x7f95f6a35cc0.

=================================================================
==14450==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 7 byte(s) in 1 object(s) allocated from:
    #0 0x4c232f in malloc (/home/.../a.out+0x4c232f)
    #1 0x4fc488 in main /home/.../ml.cc:18:9
    #2 0x7ff0098deb74 in __libc_start_main (/lib64/libc.so.6+0x27b74)
```

Any idea what might be wrong?

P.S. _AddressSanitizer_ works fine in both cases.

**Comment by Trass3r** [comment]
@kanje did you ever find a solution?
