### ISSUE TITLE
Unknown READ in MSAN

### ISSUE THREAD

**Issue by catenacyber** [google/sanitizers#1416]
Cf https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=35328

The stack trace is the following
```

MemorySanitizer:DEADLYSIGNAL
--
&nbsp; | ==7994==ERROR: MemorySanitizer: SEGV on unknown address 0x7fb0516cf994 (pc 0x0000004ae358 bp 0x000000000005 sp 0x7ffcd8d303f0 T7994)
&nbsp; | ==7994==The signal is caused by a READ memory access.
&nbsp; | #0 0x4ae358 in eq /src/llvm-project/compiler-rt/lib/msan/msan_chained_origin_depot.cpp:32:20
&nbsp; | #1 0x4ae358 in find /src/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_stackdepotbase.h:68:12
&nbsp; | #2 0x4ae358 in __sanitizer::StackDepotBase&lt;__msan::ChainedOriginDepotNode, 4, 20&gt;::Put(__msan::ChainedOriginDepotDesc, bool*) /src/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_stackdepotbase.h:109:16
&nbsp; | #3 0x4ae2a1 in __msan::ChainedOriginDepotPut(unsigned int, unsigned int, unsigned int*) /src/llvm-project/compiler-rt/lib/msan/msan_chained_origin_depot.cpp:111:57
&nbsp; | #4 0x4a9527 in __msan::Origin::CreateChainedOrigin(__msan::Origin, __sanitizer::StackTrace*) /src/llvm-project/compiler-rt/lib/msan/msan_origin.h:131:21
&nbsp; | #5 0x50407c in __msan::CopyOrigin(void const*, void const*, unsigned long, __sanitizer::StackTrace*) /src/llvm-project/compiler-rt/lib/msan/msan_poisoning.cpp:86:19
&nbsp; | #6 0x4ae99a in __msan_memcpy /src/llvm-project/compiler-rt/lib/msan/msan_interceptors.cpp:1560:3
&nbsp; | #7 0x46c0bc in fuzzer::MutationDispatcher::InsertPartOf(unsigned char const*, unsigned long, unsigned char*, unsigned long, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMutate.cpp:328:5
&nbsp; | #8 0x46d164 in fuzzer::MutationDispatcher::MutateImpl(unsigned char*, unsigned long, unsigned long, std::__Fuzzer::vector&lt;fuzzer::MutationDispatcher::Mutator, fuzzer::fuzzer_allocator&lt;fuzzer::MutationDispatcher::Mutator&gt; &gt;&amp;) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMutate.cpp:532:22
&nbsp; | #9 0x45a883 in fuzzer::Fuzzer::MutateAndTestOne() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:737:20
&nbsp; | #10 0x45b3f5 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector&lt;fuzzer::SizedFile, fuzzer::fuzzer_allocator&lt;fuzzer::SizedFile&gt; &gt;&amp;) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:883:5
&nbsp; | #11 0x44aac4 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:906:6
&nbsp; | #12 0x473912 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
&nbsp; | #13 0x7f306084383f in __libc_start_main /build/glibc-e6zv40/glibc-2.23/csu/libc-start.c:291
&nbsp; | #14 0x4205f8 in _start
```

So, did MSAN overflow ?

**Comment by jonathanmetzman** [comment]
CC @morehouse
