### ISSUE TITLE
when asan doesn't report anything when link with 3rd party .o and library??

### ISSUE THREAD

**Issue by incity** [google/sanitizers#1420]
1. i write a test.cpp as follow, and compile it with -fsanitize=address -fno-omit-frame-pointer -O0

```
#include <stdio.h>
#include <stdlib.h>
int main(int, char**) {
    char* buf = (char*)malloc(10);
    buf[0] = 40;
    printf("%s\n", buf);
    return 0;
}
```

and get the follow report :
```

ASAN:SIGSEGV
=================================================================
==24476==ERROR: AddressSanitizer: SEGV on unknown address 0x000000613a08 (pc 0x7f13d30decc2 bp 0x7ffecad1d900 sp 0x7ffecad1d8f0 T0)
    #0 0x7f13d30decc1 in std::__atomic_base<int>::operator++() /usr/include/c++/5/bits/atomic_base.h:296
    #1 0x7f13d311ae23 in java::lang::Object_Value::incRefCount() external/lvgl/javolution/src/share/classes/java/lang/Object.cpp:38
    #2 0x7f13d30d416c in java::lang::Object::Object(java::lang::Object const&) external/lvgl/javolution/src/share/classes/java/lang/Object.h:136
    #3 0x7f13d30d41a1 in java::lang::Object::operator=(java::lang::Object const&) external/lvgl/javolution/src/share/classes/java/lang/Object.h:199
    #4 0x7f13d30debbe in java::lang::Comparable<java::lang::String>::operator=(java::lang::Comparable<java::lang::String> const&) external/lvgl/javolution/src/share/classes/java/lang/Comparable.h:23
    #5 0x7f13d30dec03 in java::lang::String::operator=(java::lang::String const&) external/lvgl/javolution/src/share/classes/java/lang/String.h:36
    #6 0x7f13d30ee917 in java::net::Inet4Address::Value::Value(java::lang::String const&, int) external/lvgl/javolution/src/share/classes/java/net/Inet4Address.h:98
    #7 0x7f13d30ee63f in __static_initialization_and_destruction_0 external/lvgl/javolution/src/share/classes/java/net/InetAddress.cpp:15
    #8 0x7f13d30ee7ce in _GLOBAL__sub_I_InetAddress.cpp external/lvgl/javolution/src/share/classes/java/net/InetAddress.cpp:39
    #9 0x7f13d43a56f9  (/lib64/ld-linux-x86-64.so.2+0x106f9)
    #10 0x7f13d43a580a  (/lib64/ld-linux-x86-64.so.2+0x1080a)
    #11 0x7f13d4395c69  (/lib64/ld-linux-x86-64.so.2+0xc69)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /usr/include/c++/5/bits/atomic_base.h:296 std::__atomic_base<int>::operator++()
==24476==ABORTING

```

for now everything is right. but when i link it with a 3rd-party .o and a 3rd-party library, the asan doesn't report the error anymore.

first, i compile the test.cpp to test.o :

`/usr/bin/g++  -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--gc-sections -Bdynamic -Wl,-z,nocopyreloc -pie -Lout/target/product/x86/obj/lib -Wl,-rpath-link=out/target/product/x86/obj/lib -Wl,-rpath,\$ORIGIN/../lib  test.o             -Wl,--whole-archive   -Wl,--no-whole-archive     -ljavolution -lsqlite  -o a.out    -fsanitize=address -fno-omit-frame-pointer     -ldl -lpthread -lm`

and then link it with a 3rd-party .o and a 3rd-party .so

`/usr/bin/g++  -Lout/target/product/x86/obj/lib  -Wl,-rpath,\$ORIGIN/../lib    out/target/product/x86/obj/EXECUTABLES/thirdparty_demo_intermediates/thirdparty_demo.o  test.o -lthirdpartylib -lsqlite  -o test    -fsanitize=address -fno-omit-frame-pointer     -ldl -lpthread -lm`

and i run the test, the asan doesn't have the memory leak report.

[output.zip](https://github.com/google/sanitizers/files/6726332/output.zip)

**Comment by vitalybuka** [comment]
This SEGV has nothing to do with main() from example?

**Comment by incity** [comment]
i pasted wrong output. i has modified it. @vitalybuka

**Comment by incity** [comment]
@vitalybuka did you find any problem?

**Comment by vitalybuka** [comment]
lsan can't guaranty finding all leaks. Probably pointer is still alive somewhere on the stack.
It's very likely if program leaks in main() just before leak checker invoked.
In general, the farther from main(), the higher probability to detect.

**Comment by incity** [comment]
but if i didn't link with 3rd-party .o and 3rd-party .so,  the leak can be detected. why the 3rd-party library can affect this?
i still not call any function in the library. i tested for the same simple code

```
#include <stdio.h>
#include <stdlib.h>
int main(int, char**) {
    char* buf = (char*)malloc(10);
    buf[0] = 40;
    buf[1] = 0;
    printf("%s\n", buf);
    return 0;
}
```

**Comment by vitalybuka** [comment]
you can try to add more leaks into the program assigning into the same var.
If it still does not detect then maybe 3rd party lib disables asan.
E.g.

int main(int, char**) {
char* buf = (char*)malloc(10);
  buf[0] = 40;
  buf[1] = 0;
  printf("%s\n", buf);
buf = (char*)malloc(20);
  buf[0] = 41;
  buf[1] = 0;
  printf("%s\n", buf);
buf = (char*)malloc(30);
  buf[0] = 42;
  buf[1] = 0;
  printf("%s\n", buf);
