### ISSUE TITLE
MemorySanitizer reports use-of-uninitialized-value with fstat and `if` 

### ISSUE THREAD

**Issue by Yardanico** [google/sanitizers#1475]
Hello. I don't really know C well, and was trying out MemorySanitizer with Nim when it triggered on some code from the stdlib. After some minimization it came down to this:

```c
#include <stdio.h>
#include <stdlib.h>
#include <sys/stat.h>

int main(void)
{
  struct stat res;
  FILE *p = fopen("test", "w");
  if (p == NULL)
  {
    perror("fopen");
    abort();
  }
  int fd = fileno(p);
  if (fd < 0)
  {
    perror("fileno");
    abort();
  }
  int fstatRes = fstat(fd, &res);
  if (fstatRes < 0)
  {
    perror("fstat");
    abort();
  }
  if (res.st_mode) // this line specifically - checking the result of fstat with some if condition triggers the bug
  {
    printf("ok!\n");
  }
  return 0;
}
```

If I compile it with `clang -fsanitize=memory -fsanitize-memory-track-origins -g test.c -o testbin`, create the test file with `touch file`, and run the binary, I get this:
```
==26687==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x55df933e76a5 in main /home/dian/Projects/NimExperiments/maze_bench_nim/test.c:26:7
    #1 0x7fe483927b24 in __libc_start_main (/usr/lib/libc.so.6+0x27b24)
    #2 0x55df9336517d in _start (/home/dian/Projects/NimExperiments/maze_bench_nim/testbin+0x2017d)

  Uninitialized value was created by an allocation of 'res' in the stack frame of function 'main'
    #0 0x55df933e7070 in main /home/dian/Projects/NimExperiments/maze_bench_nim/test.c:6

SUMMARY: MemorySanitizer: use-of-uninitialized-value /home/dian/Projects/NimExperiments/maze_bench_nim/test.c:26:7 in main
Exiting
```

Is this a sanitizer bug or is the code wrong in some way?

My clang version is `clang version 13.0.0` from the official Arch repos.

**Comment by Yardanico** [comment]
Closing as a duplicate of https://github.com/google/sanitizers/issues/1452
