### ISSUE TITLE
Sanitizers won't trigger when compiling from llvm's bitcode

### ISSUE THREAD

**Issue by giladreich** [google/sanitizers#1476]
Can someone kindly clarify why the sanitizers won't trigger when compiling from llvm's bitcode? See below for steps to reproduce.

Given the following code:
```c
#include <stdlib.h>
int main() {
    char * p = malloc(5);
    p[5] = 0x3;
    return 0;
}
```

```sh
/usr/local/opt/llvm/bin/clang-13 -v -O0 -g -emit-llvm -c main.c -o main.bc
/usr/local/opt/llvm/bin/clang-13 -v -O0 -g -fsanitize=address -x ir -c main.bc -o main.o
/usr/local/opt/llvm/bin/clang-13 -v -O0 -g main.o -o main \
  /usr/local/opt/llvm/lib/clang/13.0.0/lib/darwin/libclang_rt.asan_osx_dynamic.dylib \
  -rpath /usr/local/opt/llvm/lib/clang/13.0.0/lib/darwin/libclang_rt.asan_osx_dynamic.dylib
./main
```

Nothing is printed / triggered, even though I can see that the ASAN sanitizer indeed injected the code for the runtime:
```sh
❯ /usr/local/opt/llvm/bin/llvm-nm -g main
                 U ___asan_init
                 U ___asan_version_mismatch_check_v8
0000000100000000 T __mh_execute_header
0000000100003f30 T _main
                 U _malloc
                 U dyld_stub_binder
```

However, when enabling ASAN in the emit bitcode stage, it does work as expected:
```sh
/usr/local/opt/llvm/bin/clang-13 -v -O0 -g -fsanitize=address -emit-llvm -c main.c -o main.bc
/usr/local/opt/llvm/bin/clang-13 -v -O0 -g -x ir -c main.bc -o main.o
/usr/local/opt/llvm/bin/clang-13 -v -O0 -g main.o -o main \
  /usr/local/opt/llvm/lib/clang/13.0.0/lib/darwin/libclang_rt.asan_osx_dynamic.dylib \
  -rpath /usr/local/opt/llvm/lib/clang/13.0.0/lib/darwin/libclang_rt.asan_osx_dynamic.dylib
./main
```

Output:
```
=================================================================
==92756==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020000000f5 at pc 0x00010a83df33 bp 0x7ffee53c4ee0 sp 0x7ffee53c4ed8
WRITE of size 1 at 0x6020000000f5 thread T0
    #0 0x10a83df32 in main main.c:4
    #1 0x7fff20485f3c in start+0x0 (libdyld.dylib:x86_64+0x15f3c)

0x6020000000f5 is located 0 bytes to the right of 5-byte region [0x6020000000f0,0x6020000000f5)
allocated by thread T0 here:
    #0 0x10a88e750 in wrap_malloc+0xa0 (libclang_rt.asan_osx_dynamic.dylib:x86_64+0x44750)
    #1 0x10a83dee8 in main main.c:3
    #2 0x7fff20485f3c in start+0x0 (libdyld.dylib:x86_64+0x15f3c)

SUMMARY: AddressSanitizer: heap-buffer-overflow main.c:4 in main
Shadow bytes around the buggy address:
  0x1c03ffffffc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1c03ffffffd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1c03ffffffe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1c03fffffff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1c0400000000: fa fa fd fd fa fa 00 00 fa fa 00 05 fa fa 00 fa
=>0x1c0400000010: fa fa 00 04 fa fa 00 00 fa fa 00 06 fa fa[05]fa
  0x1c0400000020: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c0400000030: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c0400000040: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c0400000050: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c0400000060: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==92756==ABORTING
[1]    92756 abort      ./main
```

And in the symbols I can see an additional export from ASAN (`___asan_report_store1`):
```sh
❯ /usr/local/opt/llvm/bin/llvm-nm -g main
                 U ___asan_init
                 U ___asan_report_store1
                 U ___asan_version_mismatch_check_v8
0000000100000000 T __mh_execute_header
0000000100003ed0 T _main
                 U _malloc
                 U dyld_stub_binder
```

Note that I attempted the same steps above even with older llvm installations and experienced the same issue. Is this a bug? or am I missing something?

Many thanks!

**Comment by dvyukov** [comment]
Asan pass only instruments functions that have sanitize_address attribute:
https://github.com/llvm/llvm-project/blob/main/llvm/test/Instrumentation/AddressSanitizer/byval-args.ll#L9
It's added to functions only when -fsanitize=address is specified. So if you split processing, you may need to it manually somehow.

**Comment by giladreich** [comment]
> Asan pass only instruments functions that have sanitize_address attribute:
> https://github.com/llvm/llvm-project/blob/main/llvm/test/Instrumentation/AddressSanitizer/byval-args.ll#L9
> It's added to functions only when -fsanitize=address is specified. So if you split processing, you may need to it manually somehow.

Thanks to your guidance, I was able to find a way to inject these attributes through a very simple [ModulePass](https://llvm.org/docs/WritingAnLLVMPass.html#the-modulepass-class) that the optimizer will invoke and inject these attributes at the bitcode stage before compiling to object. e.g. I get all the functions within the module and on each function I invoke `Function::addFnAttr(llvm::Attribute::SanitizeAddress);`, which results to the sanitizer being triggered and can also be seen in the IR:
```sh
❯ /usr/local/opt/llvm/bin/opt main2.bc -S | grep sanitize
; Function Attrs: noinline nounwind optnone sanitize_address ssp uwtable
```

Although I wish it was not needed and work out of the box. I guess I can simulate the same behavior by checking if the given function has the attribute `__attribute__((no_sanitize_address))` defined, and if true, to not inject these attributes.

Open to thoughts and curious to hear what you think, e.g. if there are better ways to approach this than what I mentioned above.

**Comment by xiaobaozidi** [comment]
Thanks @giladreich , your solution is very helpful

**Comment by Vancir** [comment]
Thanks @giladreich, it also works for me!

**Comment by ramosian-glider** [comment]
Resolving this, as there is a proposed solution.
