### ISSUE TITLE
LeakSanitizer: unknown bytes leaked

### ISSUE THREAD

**Issue by qyxtim** [google/sanitizers#1501]
I am running on `Mac M1` with `clang version 13.0.1`.

When I run the leak sanitizer for example code shown in the [Clang 13 documentation](https://releases.llvm.org/13.0.0/tools/clang/docs/index.html),

```c
$ cat memory-leak.c 
#include <stdlib.h>

void *p;

int main() {
  p = malloc(7);
  p = 0; // The memory is leaked here.
  return 0;
}
$ clang -fsanitize=address -g memory-leak.c ; ASAN_OPTIONS=detect_leaks=1 ./a.out
```

the output shows that "4071 byte(s) leaked in 128 allocation(s)", with many of the leaked bytes coming from objects in the `<unknown module>`.

I also tested it against the code shown below:

```c
$ cat memory-leak.c 
int main()
{
  return 0;
}
$ clang -fsanitize=address -g memory-leak.c ; ASAN_OPTIONS=detect_leaks=1 ./a.out
```

It shows that "4064 byte(s) leaked in 127 allocation(s)".

It appears that by default, there are 4064 bytes leaked. The complete output of the second program is shown below.

```
==72058==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 1856 byte(s) in 58 object(s) allocated from:
    #0 0x1030c7a2c in wrap_calloc+0x94 (libclang_rt.asan_osx_dynamic.dylib:arm64+0x3fa2c)
    #1 0x19a4be484 in realizeClassWithoutSwift(objc_class*, objc_class*)+0x8c (libobjc.A.dylib:arm64+0x5484)
    #2 0x315b00019a4be608  (<unknown module>)
    #3 0x7c1280019a4bc61c  (<unknown module>)
    #4 0x7a3000019a4baf40  (<unknown module>)
    #5 0xf74c000102ce7948  (<unknown module>)
    #6 0x311e800102ce2988  (<unknown module>)
    #7 0x749800102ce780c  (<unknown module>)
    #8 0xb511000102cfc800  (<unknown module>)
    #9 0x3c5580019a4bae04  (<unknown module>)
    #10 0x301b00019a4754e0  (<unknown module>)
    #11 0xe4880019a484cbc  (<unknown module>)
    #12 0x6e148001a51806a4  (<unknown module>)
    #13 0xa842800102cedd8c  (<unknown module>)
    #14 0x732800102d1717c  (<unknown module>)
    #15 0x194c800102d0dbc8  (<unknown module>)
    #16 0x9221800102cd9f94  (<unknown module>)
    #17 0x2d1d000102d0d970  (<unknown module>)
    #18 0x307a000102d16bcc  (<unknown module>)
    #19 0x957f800102cedccc  (<unknown module>)
    #20 0x5f22000102cf47c8  (<unknown module>)
    #21 0x1325800102d02fe8  (<unknown module>)
    #22 0x431b800102cdddb4  (<unknown module>)
    #23 0xfc30000102cdd064  (<unknown module>)
    #24 0x4737ffffffffffc  (<unknown module>)

Direct leak of 1856 byte(s) in 58 object(s) allocated from:
    #0 0x1030c7a2c in wrap_calloc+0x94 (libclang_rt.asan_osx_dynamic.dylib:arm64+0x3fa2c)
    #1 0x19a4be484 in realizeClassWithoutSwift(objc_class*, objc_class*)+0x8c (libobjc.A.dylib:arm64+0x5484)
    #2 0x7c1280019a4bc61c  (<unknown module>)
    #3 0x7a3000019a4baf40  (<unknown module>)
    #4 0xf74c000102ce7948  (<unknown module>)
    #5 0x311e800102ce2988  (<unknown module>)
    #6 0x749800102ce780c  (<unknown module>)
    #7 0xb511000102cfc800  (<unknown module>)
    #8 0x3c5580019a4bae04  (<unknown module>)
    #9 0x301b00019a4754e0  (<unknown module>)
    #10 0xe4880019a484cbc  (<unknown module>)
    #11 0x6e148001a51806a4  (<unknown module>)
    #12 0xa842800102cedd8c  (<unknown module>)
    #13 0x732800102d1717c  (<unknown module>)
    #14 0x194c800102d0dbc8  (<unknown module>)
    #15 0x9221800102cd9f94  (<unknown module>)
    #16 0x2d1d000102d0d970  (<unknown module>)
    #17 0x307a000102d16bcc  (<unknown module>)
    #18 0x957f800102cedccc  (<unknown module>)
    #19 0x5f22000102cf47c8  (<unknown module>)
    #20 0x1325800102d02fe8  (<unknown module>)
    #21 0x431b800102cdddb4  (<unknown module>)
    #22 0xfc30000102cdd064  (<unknown module>)
    #23 0x4737ffffffffffc  (<unknown module>)

Direct leak of 160 byte(s) in 5 object(s) allocated from:
    #0 0x1030c7a2c in wrap_calloc+0x94 (libclang_rt.asan_osx_dynamic.dylib:arm64+0x3fa2c)
    #1 0x19a4be484 in realizeClassWithoutSwift(objc_class*, objc_class*)+0x8c (libobjc.A.dylib:arm64+0x5484)
    #2 0xa15f80019a4be5f0  (<unknown module>)
    #3 0x7c1280019a4bc61c  (<unknown module>)
    #4 0x7a3000019a4baf40  (<unknown module>)
    #5 0xf74c000102ce7948  (<unknown module>)
    #6 0x311e800102ce2988  (<unknown module>)
    #7 0x749800102ce780c  (<unknown module>)
    #8 0xb511000102cfc800  (<unknown module>)
    #9 0x3c5580019a4bae04  (<unknown module>)
    #10 0x301b00019a4754e0  (<unknown module>)
    #11 0xe4880019a484cbc  (<unknown module>)
    #12 0x6e148001a51806a4  (<unknown module>)
    #13 0xa842800102cedd8c  (<unknown module>)
    #14 0x732800102d1717c  (<unknown module>)
    #15 0x194c800102d0dbc8  (<unknown module>)
    #16 0x9221800102cd9f94  (<unknown module>)
    #17 0x2d1d000102d0d970  (<unknown module>)
    #18 0x307a000102d16bcc  (<unknown module>)
    #19 0x957f800102cedccc  (<unknown module>)
    #20 0x5f22000102cf47c8  (<unknown module>)
    #21 0x1325800102d02fe8  (<unknown module>)
    #22 0x431b800102cdddb4  (<unknown module>)
    #23 0xfc30000102cdd064  (<unknown module>)
    #24 0x4737ffffffffffc  (<unknown module>)

Direct leak of 128 byte(s) in 4 object(s) allocated from:
    #0 0x1030c7a2c in wrap_calloc+0x94 (libclang_rt.asan_osx_dynamic.dylib:arm64+0x3fa2c)
    #1 0x19a4be484 in realizeClassWithoutSwift(objc_class*, objc_class*)+0x8c (libobjc.A.dylib:arm64+0x5484)
    #2 0x566380019a4be608  (<unknown module>)
    #3 0xa15f80019a4be5f0  (<unknown module>)
    #4 0x7c1280019a4bc61c  (<unknown module>)
    #5 0x7a3000019a4baf40  (<unknown module>)
    #6 0xf74c000102ce7948  (<unknown module>)
    #7 0x311e800102ce2988  (<unknown module>)
    #8 0x749800102ce780c  (<unknown module>)
    #9 0xb511000102cfc800  (<unknown module>)
    #10 0x3c5580019a4bae04  (<unknown module>)
    #11 0x301b00019a4754e0  (<unknown module>)
    #12 0xe4880019a484cbc  (<unknown module>)
    #13 0x6e148001a51806a4  (<unknown module>)
    #14 0xa842800102cedd8c  (<unknown module>)
    #15 0x732800102d1717c  (<unknown module>)
    #16 0x194c800102d0dbc8  (<unknown module>)
    #17 0x9221800102cd9f94  (<unknown module>)
    #18 0x2d1d000102d0d970  (<unknown module>)
    #19 0x307a000102d16bcc  (<unknown module>)
    #20 0x957f800102cedccc  (<unknown module>)
    #21 0x5f22000102cf47c8  (<unknown module>)
    #22 0x1325800102d02fe8  (<unknown module>)
    #23 0x431b800102cdddb4  (<unknown module>)
    #24 0xfc30000102cdd064  (<unknown module>)
    #25 0x4737ffffffffffc  (<unknown module>)

Direct leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x1030c7a2c in wrap_calloc+0x94 (libclang_rt.asan_osx_dynamic.dylib:arm64+0x3fa2c)
    #1 0x19a4be484 in realizeClassWithoutSwift(objc_class*, objc_class*)+0x8c (libobjc.A.dylib:arm64+0x5484)
    #2 0xaa7f80019a4be5f0  (<unknown module>)
    #3 0xa15f80019a4be5f0  (<unknown module>)
    #4 0x7c1280019a4bc61c  (<unknown module>)
    #5 0x7a3000019a4baf40  (<unknown module>)
    #6 0xf74c000102ce7948  (<unknown module>)
    #7 0x311e800102ce2988  (<unknown module>)
    #8 0x749800102ce780c  (<unknown module>)
    #9 0xb511000102cfc800  (<unknown module>)
    #10 0x3c5580019a4bae04  (<unknown module>)
    #11 0x301b00019a4754e0  (<unknown module>)
    #12 0xe4880019a484cbc  (<unknown module>)
    #13 0x6e148001a51806a4  (<unknown module>)
    #14 0xa842800102cedd8c  (<unknown module>)
    #15 0x732800102d1717c  (<unknown module>)
    #16 0x194c800102d0dbc8  (<unknown module>)
    #17 0x9221800102cd9f94  (<unknown module>)
    #18 0x2d1d000102d0d970  (<unknown module>)
    #19 0x307a000102d16bcc  (<unknown module>)
    #20 0x957f800102cedccc  (<unknown module>)
    #21 0x5f22000102cf47c8  (<unknown module>)
    #22 0x1325800102d02fe8  (<unknown module>)
    #23 0x431b800102cdddb4  (<unknown module>)
    #24 0xfc30000102cdd064  (<unknown module>)
    #25 0x4737ffffffffffc  (<unknown module>)

Direct leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x1030c7a2c in wrap_calloc+0x94 (libclang_rt.asan_osx_dynamic.dylib:arm64+0x3fa2c)
    #1 0x19a4be484 in realizeClassWithoutSwift(objc_class*, objc_class*)+0x8c (libobjc.A.dylib:arm64+0x5484)
    #2 0xfa5b00019a4be608  (<unknown module>)
    #3 0xaa7f80019a4be5f0  (<unknown module>)
    #4 0xa15f80019a4be5f0  (<unknown module>)
    #5 0x7c1280019a4bc61c  (<unknown module>)
    #6 0x7a3000019a4baf40  (<unknown module>)
    #7 0xf74c000102ce7948  (<unknown module>)
    #8 0x311e800102ce2988  (<unknown module>)
    #9 0x749800102ce780c  (<unknown module>)
    #10 0xb511000102cfc800  (<unknown module>)
    #11 0x3c5580019a4bae04  (<unknown module>)
    #12 0x301b00019a4754e0  (<unknown module>)
    #13 0xe4880019a484cbc  (<unknown module>)
    #14 0x6e148001a51806a4  (<unknown module>)
    #15 0xa842800102cedd8c  (<unknown module>)
    #16 0x732800102d1717c  (<unknown module>)
    #17 0x194c800102d0dbc8  (<unknown module>)
    #18 0x9221800102cd9f94  (<unknown module>)
    #19 0x2d1d000102d0d970  (<unknown module>)
    #20 0x307a000102d16bcc  (<unknown module>)
    #21 0x957f800102cedccc  (<unknown module>)
    #22 0x5f22000102cf47c8  (<unknown module>)
    #23 0x1325800102d02fe8  (<unknown module>)
    #24 0x431b800102cdddb4  (<unknown module>)
    #25 0xfc30000102cdd064  (<unknown module>)
    #26 0x4737ffffffffffc  (<unknown module>)

SUMMARY: AddressSanitizer: 4064 byte(s) leaked in 127 allocation(s).
```

**Comment by jokalode** [comment]
I can add a little more info to the stack trace. I am running on Intel, but I guess it doesn't make that much of a difference in this case. Looks like the dynamic library loader is allocating some memory before dispatching to the application. Not sure it that is an error on the part of the leak sanitizer.

[leaks.txt](https://github.com/google/sanitizers/files/8489369/leaks.txt)

**Comment by willmcpherson2** [comment]
For any googlers: you can tell LeakSanitizer to suppress leaks.

[Suppressing memory leaks](https://clang.llvm.org/docs/AddressSanitizer.html#id14)

For example, create a file `lsan.supp` with

```
leak:realizeClassWithoutSwift
```

And then use it:

```
LSAN_OPTIONS=suppressions=lsan.supp
```

**Comment by miguno** [comment]
Thanks @yuxqiu for reporting and thanks @willmcpherson2 for the solution. This solved the same problem for me on macOS Ventura 13.1 with Homebrew clang version 15.0.6.

**Comment by deardeng** [comment]
> LSAN_OPTIONS=suppressions=lsan.supp

sad, it's still not work.
m1 chip
clang 15.0.5

<img width="1374" alt="image" src="https://github.com/google/sanitizers/assets/3887565/74146720-9d78-44f2-8f73-c44a91824262">

**Comment by tanis2000** [comment]
@yuxqiu how did you manage to get this running on an M1? 
Running your same example on mine gives this error:

==98137==AddressSanitizer: detect_leaks is not supported on this platform.

**Comment by yuxqiu** [comment]
> @yuxqiu how did you manage to get this running on an M1? Running your same example on mine gives this error:
> 
> ==98137==AddressSanitizer: detect_leaks is not supported on this platform.

As far as I recalled, I used `clang` shipped with the official `llvm`. You can install it via `brew install llvm`.

**Comment by tanis2000** [comment]
@yuxqiu thank you. I went the same route but I had to set the location of the libraries and headers manually in the command line to make it compile correctly:

```
/opt/homebrew/opt/llvm/bin/clang -fsanitize=address -I/opt/homebrew/opt/llvm/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -L/opt/homebrew/opt/llvm/lib -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib -g leak.c ; ASAN_OPTIONS=detect_leaks=1 ./a.out
```

**Comment by szhorvat** [comment]
@willmcpherson2 It is not always possible to use suppressions to work around this issue.

For example, here's a false positive I get from one of the tests in igraph's test suite:

```
Direct leak of 6964 byte(s) in 1 object(s) allocated from:
    #0 0x102fc019c in wrap_malloc+0x88 (libclang_rt.asan_osx_dynamic.dylib:arm64+0x5019c) (BuildId: 7f28487348363def83d523cf4a8af7ae32000000200000000100000000000b00)
    #1 0x1a85e1fe0  (<unknown module>)
    #2 0x211d8001a8933ec8  (<unknown module>)
    #3 0x677600010400b3a8  (<unknown module>)
    #4 0x102b3fd54 in main dqueue.c:112
    #5 0x1a85d3f24  (<unknown module>)
    #6 0x49447ffffffffffc  (<unknown module>)

-----------------------------------------------------
Suppressions used:
  count      bytes template
      4        152 libobjc.A.dylib
      3        148 libsystem_c.dylib
-----------------------------------------------------

SUMMARY: AddressSanitizer: 6964 byte(s) leaked in 1 allocation(s).
```

As you can see, I already suppressed leaks from system libraries, and what remains is `<unknown module>` only.

All code was built with `-fsanitizer=address` with no external dependencies, see:

```
$ otool -L src/libigraph.dylib
src/libigraph.dylib:
	@rpath/libigraph.3.dylib (compatibility version 3.0.0, current version 3.1.1)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1500.65.0)
	@rpath/libclang_rt.asan_osx_dynamic.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.100.3)
```

This is with open-source Clang 16.0.6. With Clanf 15.0.7, there are many more false positives, and with Clang 14.0.6, programs just hang when LSan is enabled.

I just asked about this here: https://discourse.llvm.org/t/does-leaksanitizer-not-work-on-macos-13-apple-silicon/73148

Does LSan not support Apple Silicon?
