### ISSUE TITLE
TSAN segmentation fault in __sanitizer::CombinedAllocator

### ISSUE THREAD

**Issue by liangjs** [google/sanitizers#1506]
When I run a program compiled with TSAN under AFL++, it crashes in __sanitizer::CombinedAllocator.
But it works fine without AFL++.

stack trace
```
#0  0x000055555557ca5a in __sanitizer::CombinedAllocator<__sanitizer::SizeClassAllocator32<__sanitizer::AP32>, __sanitizer::LargeMmapAllocatorPtrArrayStatic>::Allocate(__sanitizer::SizeClassAllocator32LocalCache<__sanitizer::SizeClassAllocator32<__sanitizer::AP32> >*, unsigned long, unsigned long) ()
#1  0x000055555557afb0 in __sanitizer::InternalAlloc(unsigned long, __sanitizer::SizeClassAllocator32LocalCache<__sanitizer::SizeClassAllocator32<__sanitizer::AP32> >*, unsigned long) ()
#2  0x0000555555632634 in __tsan::PrintCurrentStackSlow(unsigned long) ()
#3  0x000055555561bd7f in __tsan::CheckUnwind() ()
#4  0x000055555558e77e in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) ()
#5  0x0000555555616747 in __tsan::InitializeAllocator() ()
#6  0x000055555561d61c in __tsan::Initialize(__tsan::ThreadState*) ()
#7  0x00007ffff7fcc01e in _dl_init () from /lib64/ld-linux-x86-64.so.2
#8  0x00007ffff7fe396a in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
```

registers
```
rax            0x18                24
rbx            0xdb88              56200
rcx            0x9                 9
rdx            0x1d                29
rsi            0xdb88              56200
rdi            0x5555556d4700      93824993806080
rbp            0x7fffffffd940      0x7fffffffd940
rsp            0x7fffffffd8a0      0x7fffffffd8a0
r8             0x5555557154c0      93824994071744
r9             0x57                87
r10            0x7fffffffd4d8      140737488344280
r11            0x202               514
r12            0x8                 8
r13            0x1d                29
r14            0x5555556d4700      93824993806080
r15            0x14f88             85896
rip            0x55555557ca5a      0x55555557ca5a <__sanitizer::CombinedAllocator<__sanitizer::SizeClassAllocator32<__sanitizer::AP32>, __sanitizer::LargeMmapAllocatorPtrArrayStatic>::Allocate(__sanitizer::SizeClassAllocator32LocalCache<__sanitizer::SizeClassAllocator32<__sanitizer::AP32> >*, unsigned long, unsigned long)+170>
eflags         0x10206             [ PF IF RF ]
```

disassemble
```
   0x000055555557c9b0 <+0>:     endbr64
   0x000055555557c9b4 <+4>:     push   r15
   0x000055555557c9b6 <+6>:     mov    rax,rcx
   0x000055555557c9b9 <+9>:     push   r14
   0x000055555557c9bb <+11>:    push   r13
   0x000055555557c9bd <+13>:    mov    r13d,0x1
   0x000055555557c9c3 <+19>:    push   r12
   0x000055555557c9c5 <+21>:    mov    r12,rcx
   0x000055555557c9c8 <+24>:    push   rbp
   0x000055555557c9c9 <+25>:    push   rbx
   0x000055555557c9ca <+26>:    sub    rsp,0x18
   0x000055555557c9ce <+30>:    test   rdx,rdx
   0x000055555557c9d1 <+33>:    cmovne r13,rdx
   0x000055555557c9d5 <+37>:    add    rax,r13
   0x000055555557c9d8 <+40>:    jb     0x55555557ce7d <_ZN11__sanitizer17CombinedAllocatorINS_20SizeClassAllocator32INS_4AP32EEENS_32LargeMmapAllocatorPtrArrayStaticEE8AllocateEPNS_30SizeClassAllocator32LocalCacheIS3_EEmm+1229>
   0x000055555557c9de <+46>:    mov    r14,rdi
   0x000055555557c9e1 <+49>:    mov    rbx,rsi
   0x000055555557c9e4 <+52>:    cmp    rcx,0x8
   0x000055555557c9e8 <+56>:    ja     0x55555557cc68 <_ZN11__sanitizer17CombinedAllocatorINS_20SizeClassAllocator32INS_4AP32EEENS_32LargeMmapAllocatorPtrArrayStaticEE8AllocateEPNS_30SizeClassAllocator32LocalCacheIS3_EEmm+696>
   0x000055555557c9ee <+62>:    cmp    rdx,0x20000
   0x000055555557c9f5 <+69>:    ja     0x55555557cac8 <_ZN11__sanitizer17CombinedAllocatorINS_20SizeClassAllocator32INS_4AP32EEENS_32LargeMmapAllocatorPtrArrayStaticEE8AllocateEPNS_30SizeClassAllocator32LocalCacheIS3_EEmm+280>
   0x000055555557c9fb <+75>:    cmp    r13,0x100
   0x000055555557ca02 <+82>:    jbe    0x55555557cca7 <_ZN11__sanitizer17CombinedAllocatorINS_20SizeClassAllocator32INS_4AP32EEENS_32LargeMmapAllocatorPtrArrayStaticEE8AllocateEPNS_30SizeClassAllocator32LocalCacheIS3_EEmm+759>
   0x000055555557ca08 <+88>:    bsr    rdx,r13
   0x000055555557ca0c <+92>:    mov    ecx,0x3d
   0x000055555557ca11 <+97>:    mov    eax,0x3f
   0x000055555557ca16 <+102>:   xor    rdx,0x3f
   0x000055555557ca1a <+106>:   sub    ecx,edx
   0x000055555557ca1c <+108>:   sub    eax,edx
   0x000055555557ca1e <+110>:   mov    rdx,r13
   0x000055555557ca21 <+113>:   shr    rdx,cl
   0x000055555557ca24 <+116>:   cdqe
   0x000055555557ca26 <+118>:   and    edx,0x3
   0x000055555557ca29 <+121>:   lea    rdx,[rdx+rax*4-0x10]
   0x000055555557ca2e <+126>:   mov    eax,0x1
   0x000055555557ca33 <+131>:   shl    eax,cl
   0x000055555557ca35 <+133>:   sub    eax,0x1
   0x000055555557ca38 <+136>:   and    rax,r13
   0x000055555557ca3b <+139>:   cmp    rax,0x1
   0x000055555557ca3f <+143>:   sbb    rdx,0xffffffffffffffff
   0x000055555557ca43 <+147>:   mov    r13,rdx
   0x000055555557ca46 <+150>:   cmp    rdx,0x35
   0x000055555557ca4a <+154>:   ja     0x55555557ccf0 <_ZN11__sanitizer17CombinedAllocatorINS_20SizeClassAllocator32INS_4AP32EEENS_32LargeMmapAllocatorPtrArrayStaticEE8AllocateEPNS_30SizeClassAllocator32LocalCacheIS3_EEmm+832>
   0x000055555557ca50 <+160>:   mov    r15,r13
   0x000055555557ca53 <+163>:   shl    r15,0xa
   0x000055555557ca57 <+167>:   add    r15,rbx
=> 0x000055555557ca5a <+170>:   mov    rdx,QWORD PTR [r15]
   0x000055555557ca5d <+173>:   test   rdx,rdx
   0x000055555557ca60 <+176>:   je     0x55555557cd60 <_ZN11__sanitizer17CombinedAllocatorINS_20SizeClassAllocator32INS_4AP32EEENS_32LargeMmapAllocatorPtrArrayStaticEE8AllocateEPNS_30SizeClassAllocator32LocalCacheIS3_EEmm+944>
   0x000055555557ca66 <+182>:   mov    rcx,r13
   0x000055555557ca69 <+185>:   lea    rax,[rdx-0x1]
   0x000055555557ca6d <+189>:   shl    rcx,0x7
   0x000055555557ca71 <+193>:   mov    QWORD PTR [r15],rax
   0x000055555557ca74 <+196>:   lea    rdx,[rdx+rcx*1+0x2]
   0x000055555557ca79 <+201>:   lea    rax,[rax+rcx*1+0x4]
   0x000055555557ca7e <+206>:   mov    rax,QWORD PTR [rbx+rax*8]
   0x000055555557ca82 <+210>:   mov    rdx,QWORD PTR [rbx+rdx*8]
   0x000055555557ca86 <+214>:   prefetchnta BYTE PTR [rdx]
   0x000055555557ca89 <+217>:   shl    r13,0xa
   0x000055555557ca8d <+221>:   mov    rdx,QWORD PTR [rbx+0xd810]
   0x000055555557ca94 <+228>:   add    rdx,QWORD PTR [rbx+r13*1+0x10]
   0x000055555557ca99 <+233>:   mov    QWORD PTR [rbx+0xd810],rdx
   0x000055555557caa0 <+240>:   cmp    r12,0x8
   0x000055555557caa4 <+244>:   jbe    0x55555557cab4 <_ZN11__sanitizer17CombinedAllocatorINS_20SizeClassAllocator32INS_4AP32EEENS_32LargeMmapAllocatorPtrArrayStaticEE8AllocateEPNS_30SizeClassAllocator32LocalCacheIS3_EEmm+260>
   0x000055555557caa6 <+246>:   lea    rcx,[r12-0x1]
   0x000055555557caab <+251>:   and    rcx,rax
   0x000055555557caae <+254>:   jne    0x55555557cd80 <_ZN11__sanitizer17CombinedAllocatorINS_20SizeClassAllocator32INS_4AP32EEENS_32LargeMmapAllocatorPtrArrayStaticEE8AllocateEPNS_30SizeClassAllocator32LocalCacheIS3_EEmm+976>
   0x000055555557cab4 <+260>:   add    rsp,0x18
   0x000055555557cab8 <+264>:   pop    rbx
   0x000055555557cab9 <+265>:   pop    rbp
   0x000055555557caba <+266>:   pop    r12
   0x000055555557cabc <+268>:   pop    r13
   0x000055555557cabe <+270>:   pop    r14
   0x000055555557cac0 <+272>:   pop    r15
   0x000055555557cac2 <+274>:   ret
```

**Comment by liangjs** [comment]
The above compiler is clang 13.0.1.

If switching to gcc 11.2.0, it crashes in another memory allocating function.

```
#0  0x00007ffff74d700e in __sanitizer::SizeClassAllocator32LocalCache<__sanitizer::SizeClassAllocator32<__sanitizer::AP32> >::Allocate (class_id=29, allocator=0x7ffff76fc980 <__sanitizer::internal_alloc_placeholder>, this=0xdb88) at /usr/src/debug/gcc/libsanitizer/sanitizer_common/sanitizer_allocator_local_cache.h:156
#1  __sanitizer::CombinedAllocator<__sanitizer::SizeClassAllocator32<__sanitizer::AP32>, __sanitizer::LargeMmapAllocatorPtrArrayStatic>::Allocate (this=0x7ffff76fc980 <__sanitizer::internal_alloc_placeholder>, cache=cache@entry=0xdb88, size=<optimized out>, size@entry=2080, alignment=alignment@entry=8) at /usr/src/debug/gcc/libsanitizer/sanitizer_common/sanitizer_allocator_combined.h:69
#2  0x00007ffff74d68d3 in __sanitizer::RawInternalAlloc (alignment=8, cache=0xdb88, size=2080) at /usr/src/debug/gcc/libsanitizer/sanitizer_common/sanitizer_allocator.cpp:116
#3  __sanitizer::InternalAlloc (size=size@entry=2072, cache=0xdb88, alignment=alignment@entry=0) at /usr/src/debug/gcc/libsanitizer/sanitizer_common/sanitizer_allocator.cpp:159
#4  0x00007ffff74b6aa3 in __tsan::internal_alloc (typ=typ@entry=__tsan::MBlockStackTrace, sz=sz@entry=2072) at /usr/src/debug/gcc/libsanitizer/tsan/tsan_mman.cpp:348
#5  0x00007ffff74cf720 in __tsan::PrintCurrentStackSlow (pc=140737342404365) at /usr/src/debug/gcc/libsanitizer/tsan/tsan_rtl_report.cpp:729
#6  __tsan::TsanCheckFailed (file=<optimized out>, line=<optimized out>, cond=<optimized out>, v1=<optimized out>, v2=<optimized out>) at /usr/src/debug/gcc/libsanitizer/tsan/tsan_rtl_report.cpp:47
#7  0x00007ffff74f03af in __sanitizer::CheckFailed (file=file@entry=0x7ffff750e058 "/build/gcc/src/gcc/libsanitizer/sanitizer_common/sanitizer_allocator_primary64.h", line=line@entry=76, cond=cond@entry=0x7ffff750dff8 "((kSpaceBeg)) == ((address_range.Init(TotalSpaceSize, PrimaryAllocatorName, kSpaceBeg)))", v1=v1@entry=135239930216448, v2=18446744073709551604) at /usr/src/debug/gcc/libsanitizer/sanitizer_common/sanitizer_termination.cpp:78
#8  0x00007ffff74b663f in __sanitizer::SizeClassAllocator64<__tsan::AP64>::Init (release_to_os_interval_ms=5000, this=0x7ffff756dc80 <__tsan::allocator_placeholder>) at /usr/src/debug/gcc/libsanitizer/sanitizer_common/sanitizer_allocator_primary64.h:76
#9  __sanitizer::CombinedAllocator<__sanitizer::SizeClassAllocator64<__tsan::AP64>, __sanitizer::LargeMmapAllocatorPtrArrayDynamic>::Init (release_to_os_interval_ms=5000, this=0x7ffff756dc80 <__tsan::allocator_placeholder>) at /usr/src/debug/gcc/libsanitizer/sanitizer_common/sanitizer_allocator_combined.h:40
#10 __tsan::InitializeAllocator () at /usr/src/debug/gcc/libsanitizer/tsan/tsan_mman.cpp:121
#11 0x00007ffff74c01af in __tsan::Initialize (thr=0x7ffff6eaf7c0) at /usr/src/debug/gcc/libsanitizer/tsan/tsan_rtl.cpp:380
#12 0x00007ffff7fcc01e in _dl_init () from /lib64/ld-linux-x86-64.so.2
#13 0x00007ffff7fe396a in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
```

**Comment by JodiTheTigger** [comment]
I had a similar issue running on windows 11 WSL - ubuntu 22.04, with clang 15,17 and 18. Found out it was because I was linking using the mold linker (1.0.3) - using the gold linker instead and it worked fine (binutils: 2.38, gold v 1.16)
