### ISSUE TITLE
False positive in ASan/pointer-compare when using together with UBSan on clang -O1

### ISSUE THREAD

**Issue by real-or-random** [google/sanitizers#1508]
This program does not even use pointer comparisons. Maybe ASan finds a bug in UBSan here?

```
$ cat test.c
typedef struct {
    char bar[10];
} S;

int main(void) {
    S foo;
    foo.bar[4] = 0;
}
```

```
$ clang -fsanitize=undefined,address,pointer-compare -O1 test.c
$ ASAN_OPTIONS="detect_invalid_pointer_pairs=1"  ./a.out
=================================================================
==77173==ERROR: AddressSanitizer: invalid-pointer-pair: 0x7ffe1e90c6c0 0xfffffffffffffffb
    #0 0x563fb73b35e2 in main (/tmp/clang-bug/a.out+0x1045e2)
    #1 0x7f09480ca30f in __libc_start_call_main libc-start.c
    #2 0x7f09480ca3c0 in __libc_start_main@GLIBC_2.2.5 (/usr/lib/libc.so.6+0x2d3c0)
    #3 0x563fb72cf144 in _start (/tmp/clang-bug/a.out+0x20144)

Address 0x7ffe1e90c6c0 is located in stack of thread T0 at offset 32 in frame
    #0 0x563fb73b353f in main (/tmp/clang-bug/a.out+0x10453f)

  This frame has 1 object(s):
    [32, 42) 'foo' <== Memory access at offset 32 is inside this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
Address 0xfffffffffffffffb is a wild pointer inside of access range of size 0x000000000001.
SUMMARY: AddressSanitizer: invalid-pointer-pair (/tmp/clang-bug/a.out+0x1045e2) in main
==77173==ABORTING
```

If you change the `4` in the code, then `0xfffffffffffffffb` (`== 0xffffffffffffffff - 4`) changes accordingly. 

<details>
<summary>clang details</summary>

```
$ clang -v
clang version 13.0.1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-pc-linux-gnu/11.2.0
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-pc-linux-gnu/8.5.0
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-pc-linux-gnu/9.4.0
Found candidate GCC installation: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/11.2.0
Found candidate GCC installation: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/8.5.0
Found candidate GCC installation: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.4.0
Selected GCC installation: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/11.2.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
```

</details>

**Comment by wizeman** [comment]
I'm running into a similar issue, although slightly different: it happens to me while initializing a struct with zeros.
Unfortunately I haven't had time to create a minimized example for my exact issue yet.

However, I tried to reproduce the above example and I was able to do it, even when compiling with `-O2`:
```C
$ cat test.c
int main(void) {
    char bar[10];
    bar[4] = 0;
}
```
```bash
$ clang -fsanitize=undefined,address,pointer-compare -O2 test.c
$ env ASAN_OPTIONS="detect_invalid_pointer_pairs=1" ./a.out
=================================================================
==1758494==ERROR: AddressSanitizer: invalid-pointer-pair: 0x7ffecba6ee40 0xfffffffffffffffb
    #0 0x518ddf in main (/backup/wizeman/progs/bpc/a.out+0x518ddf)
    #1 0x7f3d5244378f in __libc_start_main (/nix/store/l2rla465772451kbjbjhlggx31mbi65r-glibc-2.33-123/lib/libc.so.6+0x2778f) (BuildId: 5f1f6cdb15057b4ee855b65cc6d144bf7295c2af)
    #2 0x41f399 in _start /build/glibc-2.33/csu/../sysdeps/x86_64/start.S:120

Address 0x7ffecba6ee40 is located in stack of thread T0 at offset 32 in frame
    #0 0x518d4f in main (/backup/wizeman/progs/bpc/a.out+0x518d4f)

  This frame has 1 object(s):
    [32, 42) 'bar' <== Memory access at offset 32 is inside this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
Address 0xfffffffffffffffb is a wild pointer inside of access range of size 0x000000000001.
SUMMARY: AddressSanitizer: invalid-pointer-pair (/backup/wizeman/progs/bpc/a.out+0x518ddf) in main
==1758494==ABORTING
```

```
$ clang -v
clang version 14.0.0
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /nix/store/blpq7i2493vl8is1g1s7f25q0zxkxvg1-clang-14.0.0-rc1/bin
```

**Comment by wizeman** [comment]
BTW, the above issue (as well as my issue with initializing a struct) doesn't seem to occur with gcc:

```bash
$ gcc -fsanitize=undefined,address,pointer-compare -O1 test.c
$ env ASAN_OPTIONS="detect_invalid_pointer_pairs=1" ./a.out
$ gcc -fsanitize=undefined,address,pointer-compare -O2 test.c
$ env ASAN_OPTIONS="detect_invalid_pointer_pairs=1" ./a.out
```
```bash
$ gcc -v
Using built-in specs.
COLLECT_GCC=/nix/store/zjfn4pzsylsry1h7kjd33218a1hvfadz-gcc-11.2.0/bin/gcc
COLLECT_LTO_WRAPPER=/nix/store/zjfn4pzsylsry1h7kjd33218a1hvfadz-gcc-11.2.0/libexec/gcc/x86_64-unknown-linux-gnu/11.2.0/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with:
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 11.2.0 (GCC)
```
