### ISSUE TITLE
MSan: missing interceptor for lstat() on linux

### ISSUE THREAD

**Issue by seanm** [google/sanitizers#1510]
This simple test case:

```C
#include <stdio.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>

int main(int argc, char** argv)
{
    struct stat lst;
    if (lstat("/usr/local", &lst) < 0)
       return 1;

    if (S_IFLNK == (lst.st_mode & S_IFMT)) {
       return 2;
    }

    return 3;
}
```

Results in:

```
==810078==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x49a498 in main /home/smcbride/external/test.c:17:1
    #1 0x7fcdfb890fcf in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #2 0x7fcdfb89107c in __libc_start_main csu/../csu/libc-start.c:409:3
    #3 0x41c224 in _start (/home/smcbride/external/a.out+0x41c224)

  Uninitialized value was created by an allocation of 'lst' in the stack frame of function 'main'
    #0 0x49a350 in main /home/smcbride/external/test.c:7

SUMMARY: MemorySanitizer: use-of-uninitialized-value /home/smcbride/external/test.c:17:1 in main
```

This is a false positive, as the code checks for an error result from `lstat`.

From my very limited understanding of how MSan works, what's missing is an interceptor for `lstat`, on linux at least.

**Comment by vitalybuka** [comment]
Which glibc do you have?
And which glibc was used to build llvm?

**Comment by seanm** [comment]
I've updated some software:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy

$ uname -a
Linux benzene 5.15.0-30-generic #31-Ubuntu SMP Thu May 5 10:00:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

$ clang --version
Ubuntu clang version 14.0.0-1ubuntu1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

$ ldd --version
ldd (Ubuntu GLIBC 2.35-0ubuntu3) 2.35
```

and the issue seems to be fixed...
