### ISSUE TITLE
malloc in static 

### ISSUE THREAD

**Issue by 0x34d** [google/sanitizers#1518]
Code:
```
#include <stdio.h>
#include <stdlib.h>

static char* ping;

int main(){
	ping = malloc(1024*1024);
	char *non_ping = malloc(1024*1024);
	return 0;
}

```
#
Compile
```
gcc -g -O0 -fsanitize=address,undefined ping.c -o ping
clang -g -O0 -fsanitize=address,undefined ping.c -o ping

```
#
Output

```
=================================================================
==1309343==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 1048576 byte(s) in 1 object(s) allocated from:
    #0 0x4c3d67 in __interceptor_malloc (/home/0x34d/Desktop/ping+0x4c3d67)
    #1 0x4fc41a in main /home/0x34d/Desktop/ping.c:8:19
    #2 0x7f5ede17d55f in __libc_start_call_main (/lib64/libc.so.6+0x2d55f)

SUMMARY: AddressSanitizer: 1048576 byte(s) leaked in 1 allocation(s).
```

#
Note: Only one leak was detected.
```
clang version 13.0.0 (Fedora 13.0.0-3.fc35)
gcc (GCC) 11.2.1 20220127 (Red Hat 11.2.1-9)
```

**Comment by kcc** [comment]
the result of the second call is unused, and was optimized away by the compiler.

**Comment by eugenis** [comment]
The static pointer is not a leak because it is always reachable. This is a
common code pattern to avoid deallocation of memory that is only allocated
once.
