### ISSUE TITLE
Error: myapp.node: undefined symbol: __asan_option_detect_stack_use_after_return

### ISSUE THREAD

**Issue by naveedkhan8067** [google/sanitizers#1527]
I have enabled AddressSanitizer for my Node Addon but it fails before running the typescript based tests. The build was successful but it fails with following error before executing the tests

internal/modules/cjs/loader.js:1122
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /mnt/d/imodel02WSL/output/Linux/myapp.node: undefined symbol: __asan_option_detect_stack_use_after_return
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at loadLocalBuildOfAddon

I am not sure, what exactly is the problem. I have enable `-fsanitize-address` for both linker and compiler for clang++. I also tried removing flags `-Wl,--no-undefined` which was previously present but still i see the same issue. Can you help me to resolve this issue?

**Comment by Thaddeus5555555** [comment]
view
