### ISSUE TITLE
Memory sanitizer fails to detect use of uninitialized member variable?

### ISSUE THREAD

**Issue by bjodah-public-pull** [google/sanitizers#1575]
Forgive me if I miss something obvious, but the example from the documentation (`umr.cc`) works fine for me (clang++ 15.0.1, libc++ 15.0.1 compiled with ` -DLLVM_USE_SANITIZER=MemoryWithOrigins`):
<details>
<summary>shell session with umr.cc showing expected behavior</summary>

```shell-session
$ cat umr.cc
#include <stdio.h>

int main(int argc, char** argv) {
    int* a = new int[10];
    a[5] = 0;
    if (a[argc])
        printf("xx\n");
    return 0;
}
$ clang++ -fsanitize=memory -fsanitize-memory-track-origins=2 -fno-omit-frame-pointer -fno-optimize-sibling-calls -fsized-deallocation -stdlib=libc++ -nostdinc++ -I/tmp/build/build-msan/include/c++/v1 -g -O2 -o umr umr.cc -Wl,-rpath,/tmp/build/build-msan/lib -L/tmp/build/build-msan/lib -lc++abi
$ ./umr
==14150==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x55fa16c4eef1 in main /tmp/build/build-msan/umr.cc:6:9
    #1 0x7fda52c42554 in __libc_start_main (/lib64/libc.so.6+0x22554) (BuildId: 9470e279388f7f9cb2ed3b2872d0c2095b191ff4)
    #2 0x55fa16bc73f9 in _start (/tmp/build/build-msan/umr+0x1e3f9)

  Uninitialized value was created by a heap allocation
    #0 0x55fa16c4ce49 in operator new[](unsigned long) /build/llvm-project-llvmorg-15.0.1/compiler-rt/lib/msan/msan_new_delete.cpp:47:37
    #1 0x55fa16c4ee47 in main /tmp/build/build-msan/umr.cc:4:14
    #2 0x7fda52c42554 in __libc_start_main (/lib64/libc.so.6+0x22554) (BuildId: 9470e279388f7f9cb2ed3b2872d0c2095b191ff4)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /tmp/build/build-msan/umr.cc:6:9 in main
Exiting

```
</details>

but for some reason this trivial c++ program does not trigger a MSAN error, is this expected? (is #534 related?)

```shell-session
$ cat a.cpp
#include <iostream>

class A {
    int m_a, m_b;
public:
    A(int a) : m_a(a) {}
    int a_plus_b() {
        return m_a + m_b;
    }
};

int main() {
    std::cout << "a + b = " << A(3).a_plus_b() << std::endl;
    return 0;
}
$ clang++ -fsanitize=memory -fsanitize-memory-track-origins=2 -fno-omit-frame-pointer -fno-optimize-sibling-calls -fsized-deallocation -stdlib=libc++ -nostdinc++ -I/tmp/build/build-msan/include/c++/v1 -g -O2 -o a.out a.cpp -Wl,-rpath,/tmp/build/build-msan/lib -L/tmp/build/build-msan/lib -lc++abi
$ ./a.out
a + b = 1453758248
```
Note that the command here is the same as the one used with the umr.cc example, except for the `-o a.out a.cpp` part.

The program is clearly reading the uninitialized `m_b`. Compiling the same program without any sanitizer flags, and running under valgrind reports uninitialized memory.

**Comment by vitalybuka** [comment]
my default detects branching on uninitialized values
try stricter mode with -fsanitize-memory-param-retval
Clang 16 is expected to have this flag enabled by default.

**Comment by bjodah-public-pull** [comment]
Thank you @vitalybuka, that does indeed make memory sanitizer report a use-of-uninitialized-value. Much appreciated!
