### ISSUE TITLE
signed-integer-overflow sanitizer bug

### ISSUE THREAD

**Issue by 0x34d** [google/sanitizers#1580]
#### Code:
```
#include <stdio.h>
#include <stdint.h>

int main(){
    uint16_t data0 = 65313;
    uint32_t data1 = data0 * data0; //4265787969

    printf("%u \n",data0);
    printf("%u \n",data1);
    return 0;
}

```

#### Compile:
```
clang version 14.0.5 (Fedora 14.0.5-1.fc36)

clang -Wall -Werror -fsanitize=signed-integer-overflow file.c
```

#### Run log
```
file.c:6:28: runtime error: signed integer overflow: 65313 * 65313 cannot be represented in type 'int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior file.c:6:28 in 
65313 
4265787969 
```

### But if anything changes like:

- `sanitizer`

```
clang -Wall -Werror -fsanitize=unsigned-integer-overflow file.c
```

or 
- `code`

```
uint32_t data0 = 65313;
```

runtime error is gone.

Real world issues : https://github.com/google/oss-fuzz/issues/8715

**Comment by 0x34d** [comment]
The main origen of bug  https://github.com/ntpsec/gpsd/blob/master/gpsd/packet.c#L2649-L2650

```
gpsd-3.24.1~dev/gpsd/packet.c:2650:55: runtime error: signed integer overflow: 65313 * 65313 cannot be represented in type 'int'
--
  | #0 0x4c48a1 in packet_parse gpsd/gpsd-3.24.1~dev/gpsd/packet.c:2650:55
  | #1 0x4c1643 in LLVMFuzzerTestOneInput gpsd/fuzzer/FuzzPacket.c:47:9
  | #2 0x4274e3 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
  | #3 0x412c42 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324:6
  | #4 0x4184ec in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:860:9
  | #5 0x441a22 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
  | #6 0x7fae099f30b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/libc-start.c:308:16
  | #7 0x408e0d in _start
```

**Comment by 0x34d** [comment]
#### My Problem is:

- Why `-fsanitize=signed-integer-overflow` is reading `uint32_t` as `int32_t`
- What is the problem with `uint16_t uint32_t` one after other, why they result in an error.
