### ISSUE TITLE
MSAN: False positive reported by MSAN?

### ISSUE THREAD

**Issue by alex-lt-kong** [google/sanitizers#1623]
I created the below minimal reproducible example:
* `clang++ --version`:
```
Debian clang version 11.0.1-2
Target: x86_64-pc-linux-gnu
Thread model: posix
``` 
* `main.cpp`:
```C++
#include <string>
#include <iostream>

using namespace std;

int main() {
    string s0 = to_string(1);
    cout << "s0: " << s0 << endl;
    string s1 = to_string(1) + to_string(2);
    cout << "s1: " << s1 << endl;
    return 0;
}
```
* `Makefile`:
```
main:
	clang++ -fsanitize=memory -fsanitize-memory-track-origins -fPIE -pie -fno-omit-frame-pointer -g -O2 main.cpp -o main-msan.out
	clang++ -O2 main.cpp -o main.out

.PHONY: clean
clean:
	rm *.out
```
Running `main.out` is fine (as MemorySanitizer is not enabled), running `main-msan.out` shows:
```
./main-msan.out 
s0: 1
==122092==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x55a7354e5cf7 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, std::char_traits<char>, std::allocator<char> >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&) /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/basic_string.h:6123:34
    #1 0x55a7354e5cf7 in main <my_directory>/msan/main.cpp:9:30
    #2 0x7f201f6edd09 in __libc_start_main csu/../csu/libc-start.c:308:16
    #3 0x55a735468349 in _start (<my_directory>/msan/main-msan.out+0x21349)

  Uninitialized value was created by an allocation of 'ref.tmp' in the stack frame of function 'main'
    #0 0x55a7354e4d90 in main <my_directory>/msan/main.cpp:6

SUMMARY: MemorySanitizer: use-of-uninitialized-value /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/basic_string.h:6123:34 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, std::char_traits<char>, std::allocator<char> >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)
Exiting
```

Any idea?

**Comment by alex-lt-kong** [comment]
it is sad that my issue is marked as closed without letting me make a further query. Perhaps extra questions are not welcomed.

**Comment by vitalybuka** [comment]
> it is sad that my issue is marked as closed without letting me make a further query. Perhaps extra questions are not welcomed.

The thread is not locked, you can add more questions. It's just the "issue" you described is not a valid issue.
