### ISSUE TITLE
AddressSanitizer: SEGV on unknown address(libasan.so error)

### ISSUE THREAD

**Issue by zhchaozhang** [google/sanitizers#1636]
When use AddressSanitizer to test app, an error reported that occur in libasan.so

2021:18:18:979_ASAN:SIGSEGV
2021:18:18:979_ASAN:SIGSEGV
2021:18:19:216_=================================================================
2021:18:19:354_==24068==AddressSanitizer: while reporting a bug found another one.Ignoring.
2021:18:19:369_==24068==ERROR: AddressSanitizer: SEGV on unknown address 0x63600000 (pc 0x76a58970 sp 0x7127acc8 bp 0x7127ada8 T9)
2021:18:19:485_    #0 0x76a5896f (/usr/lib/arm-linux-gnueabihf/libasan.so.1+0x1b96f)
2021:18:19:485_    #1 0x76a57393 (/usr/lib/arm-linux-gnueabihf/libasan.so.1+0x1a393)
2021:18:19:485_    #2 0x76a57c4f (/usr/lib/arm-linux-gnueabihf/libasan.so.1+0x1ac4f)
2021:18:19:485_    #3 0x76a9447b in __interceptor_calloc (/usr/lib/arm-linux-gnueabihf/libasan.so.1+0x5747b)
2021:18:19:485_
2021:18:19:485_AddressSanitizer can not provide additional info.
2021:18:19:485_SUMMARY: AddressSanitizer: SEGV ??:0 ??
2021:18:19:516_Thread T9 (Conn_Thread) created by T0 here:
2021:18:19:516_    #0 0x76a5cf93 in __interceptor_pthread_create (/usr/lib/arm-linux-gnueabihf/libasan.so.1+0x1ff93)
2021:18:19:516_    #1 0xc787f in thread_new_sized OsInterface/Common/thread.cc:103
2021:18:19:516_    #2 0xba84d in qesl_ap_create_service_thread(qesl_ap_esl_service_config_t*) ApCore/service/qesl_ap_service_init.cpp:490
2021:18:19:516_    #3 0x19aa9 in qesl_ap_internal_init() ApCore/apps/qesl_ap_main.cpp:329
2021:18:19:516_    #4 0x3c41b in main /local/mnt/workspace/AP_daemon_build/bthost_proc/out/LIN.BT.ARM/qesl/qesl-ap/LinuxMain.cpp:293
2021:18:19:516_    #5 0x76751717 in __libc_start_main (/lib/arm-linux-gnueabihf/libc.so.6+0x17717)
2021:18:19:516_
2021:18:19:516_==24068==ABORTING

**Comment by zhchaozhang** [comment]
May I ask if anyone else has encountered similar problems? I hope you can help me
