### ISSUE TITLE
ASAN missed a global-buffer-overflow

### ISSUE THREAD

**Issue by shao-hua-li** [google/sanitizers#1639]
For the following code, `clang -fsanitize=address -O1` reports nothing for the clear global-buffer-overflow in `a[i]` and `a[x]`.

gcc's Asan can detect it at all optimization levels.

Compiler explorer: https://godbolt.org/z/5eoW48fjf

```shell
$cat a.c
int a[5];
int foo(int x) {
    for (int i=5;i<6;i++)
        a[i]++;
    return a[x];
}
int main(){
    __builtin_printf("foo = %d\n", foo(5));
}
$
$ clang-tk -fsanitize=address -w -O1 a.c; ./a.out
foo = 1
$ clang-tk -fsanitize=address -w -O0 a.c; ./a.out
=================================================================
==1==ERROR: AddressSanitizer: global-buffer-overflow on address 0x55fbf467a5b4 at pc 0x55fbf3af083c bp 0x7ffeaa2a2540 sp 0x7ffeaa2a2538
READ of size 4 at 0x55fbf467a5b4 thread T0
    #0 0x55fbf3af083b in foo /a.c:5:13
    #1 0x55fbf3af08bd in main /a.c:10:36
    #2 0x7fbaddc0c082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)
    #3 0x55fbf3a1d7fd in _start (/app/output.s+0x1d7fd)
...
$
```

**Comment by ramosian-glider** [comment]
According to the above godbolt link, ASan correctly detects the bug with -O1 at the latest trunk.
