### ISSUE TITLE
Large nofile limit cause StartSubprocess stucking

### ISSUE THREAD

**Issue by zu1k** [google/sanitizers#1662]
As described in https://github.com/google/sanitizers/issues/1477 , launching `llvm-symbolizer` via `fork` and then `execve` requires closing previously opened file descriptors. `compiler-rt` uses a crude approach, which causes child processes to get stuck and fill up the CPU when the maximum file descriptor limit is too large.

https://github.com/llvm/llvm-project/blob/f9d0bf06319203a8cbb47d89c2f39d2c782f3887/compiler-rt/lib/sanitizer_common/sanitizer_posix_libcdep.cpp#L465

_Originally posted by @zu1k in https://github.com/google/sanitizers/issues/1477#issuecomment-1590349135_

**Comment by zu1k** [comment]
It is better to close only the actual open file descriptors rather than traversing the entire potential range.

```c
void close_file_descriptors() {
    DIR *dir;
    struct dirent *entry;
    int fd;

    dir = opendir("/proc/self/fd/");
    if (dir == NULL) {
        perror("opendir failed");
        return;
    }

    while ((entry = readdir(dir)) != NULL) {
        fd = atoi(entry->d_name);

        if (fd >= 3) {
            close(fd);
        }
    }

    closedir(dir);
}
```

**Comment by dvyukov** [comment]
Another option is to use `close_range` if available. It's just `close_range(3, -1, 0)`.

**Comment by zu1k** [comment]
> Another option is to use `close_range` if available.

- `close_range` since Linux kernel 5.9, also available on BSD
- `closefrom` since FreeBSD 8.0, link `libbsd` if on Linux.

Neither of these are POSIX specifications, but should be used here I think.

**Comment by velichkov** [comment]
I believe I just hit the same problem, here is the backtrack.

```
Program received signal SIGINT, Interrupt.
0x0000564dac43dc4a in __sanitizer::internal_close(int) ()
(gdb) bt
#0  0x0000564dac43dc4a in __sanitizer::internal_close(int) ()
#1  0x0000564dac449517 in __sanitizer::StartSubprocess(char const*, char const* const*, char const* const*, int, int, int) ()
#2  0x0000564dac45302b in __sanitizer::SymbolizerProcess::StartSymbolizerSubprocess() ()
#3  0x0000564dac4525d8 in __sanitizer::SymbolizerProcess::SendCommand(char const*) ()
#4  0x0000564dac45209f in __sanitizer::LLVMSymbolizer::SymbolizePC(unsigned long, __sanitizer::SymbolizedStack*) ()
#5  0x0000564dac450e2b in __sanitizer::Symbolizer::SymbolizePC(unsigned long) ()
#6  0x0000564dac4562f0 in __lsan::CheckForLeaks() ()
#7  0x0000564dac455efe in __lsan::DoLeakCheck() ()
#8  0x00007f561df84a56 in __cxa_finalize (d=0x564dad1ab948) at ./stdlib/cxa_finalize.c:83
#9  0x0000564dac3a1c67 in __do_global_dtors_aux ()
#10 0x00007ffffed62650 in ?? ()
#11 0x00007f561ea4e24e in _dl_fini () at ./elf/dl-fini.c:142
```
and the `strace` output
```
close(743583457)                        = -1 EBADF (Bad file descriptor)
close(743583456)                        = -1 EBADF (Bad file descriptor)
close(743583455)                        = -1 EBADF (Bad file descriptor)
close(743583454)                        = -1 EBADF (Bad file descriptor)
```
