### ISSUE TITLE
TSAN crash while creating a vulkan device with no stack trace on linux

### ISSUE THREAD

**Issue by cenomla** [google/sanitizers#1678]
My program crashes (`SIGSEGV`) on a memory read inside of  `libnvidia-glcore.so` when calling `vkCreateDevice`, even when using a suppressions file that tries to ignore calls from that lib

Stack trace:
```
#0  0x00007ffff6e90456 in __sanitizer::SizeClassAllocator64LocalCache<__sanitizer::SizeClassAllocator64<__tsan::AP64> >::Allocate (class_id=4, allocator=0x7ffff6f55c00 <__tsan::allocator_placeholder>, this=0x8)
    at /usr/src/debug/gcc/gcc/libsanitizer/sanitizer_common/sanitizer_allocator_local_cache.h:38
#1  __sanitizer::CombinedAllocator<__sanitizer::SizeClassAllocator64<__tsan::AP64>, __sanitizer::LargeMmapAllocatorPtrArrayDynamic>::Allocate (this=this@entry=0x7ffff6f55c00 <__tsan::allocator_placeholder>, cache=0x8, 
    size=<optimized out>, size@entry=56, alignment=alignment@entry=16) at /usr/src/debug/gcc/gcc/libsanitizer/sanitizer_common/sanitizer_allocator_combined.h:69
#2  0x00007ffff6e8dad2 in __tsan::user_alloc_internal (thr=thr@entry=0x7fef60179f00, pc=140737335538724, sz=sz@entry=56, align=align@entry=16, signal=signal@entry=true) at /usr/src/debug/gcc/gcc/libsanitizer/tsan/tsan_rtl.h:216
#3  0x00007ffff6e8dd4e in __tsan::user_calloc (thr=thr@entry=0x7fef60179f00, pc=<optimized out>, size=size@entry=1, n=n@entry=56) at /usr/src/debug/gcc/gcc/libsanitizer/tsan/tsan_mman.cpp:230
#4  0x00007ffff6e4342a in __interceptor_calloc (size=1, n=56) at /usr/src/debug/gcc/gcc/libsanitizer/tsan/tsan_interceptors_posix.cpp:702
#5  0x00007fefaa0f7aae in ?? () from /usr/lib/libnvidia-glcore.so.535.54.03
#6  0x00007fefaa11335a in ?? () from /usr/lib/libnvidia-glcore.so.535.54.03
#7  0x00007fefaa11218e in ?? () from /usr/lib/libnvidia-glcore.so.535.54.03
#8  0x00007ffff6c9d44b in ?? () from /usr/lib/libc.so.6
#9  0x00007ffff6d20e40 in ?? () from /usr/lib/libc.so.6
```

Suppressions file:
```
called_from_lib:libnvidia-tls.so
called_from_lib:libGLX_nvidia.so
called_from_lib:libnvidia-glcore.so.535.54.03
called_from_lib:libnvidia-glsi.so
called_from_lib:libnvidia-glvkspriv.so
called_from_lib:libvulkan.so
called_from_lib:libVkLayer_khronos_validation.so
```

My program runs fine under ASAN

**Comment by dvyukov** [comment]
The intention is that sanitizers runtimes are initialized before any other code. IIRC on linux we should try to initialize from .preinit_array. Not sure why glcore.so should run earlier, I would assume it's not doing anything this low-level.

**Comment by mkorenchan** [comment]
Hello, I'm an NVIDIA engineer investigating this bug.

The issue arises because `malloc/calloc/free` calls in the driver are correctly intercepted by TSAN but `pthread_*` calls are not. The NVIDIA driver is built with older glibc headers, which we need in order to maintain support for older linux distributions. Because of this, the driver picks up old versions of libpthread that TSAN does not interpose. Conversely `malloc/calloc/free` only have one version, so interposition is unhindered. When a pthread created without TSAN's `pthread_create` interceptor enters TSAN's calloc interceptor, that `ThreadState` struct mentioned above is uninitialized, resulting in the segfault.
 
I'm wondering what can be done on the TSAN side to account for this.

**Comment by vitalybuka** [comment]
CC @thurstond

**Comment by rgriebl** [comment]
Any update on this? TSAN is pretty much unusable for any application using OpenGL or Vulkan on NVIDIA right now.

**Comment by thurstond** [comment]
@michaelkorenchan

> The issue arises because malloc/calloc/free calls in the driver are correctly intercepted by TSAN but pthread_* calls are not. The NVIDIA driver is built with older glibc headers, which we need in order to maintain support for older linux distributions. Because of this, the driver picks up old versions of libpthread that TSAN does not interpose. Conversely malloc/calloc/free only have one version, so interposition is unhindered. When a pthread created without TSAN's pthread_create interceptor enters TSAN's calloc interceptor, that ThreadState struct mentioned above is uninitialized, resulting in the segfault.
>
> I'm wondering what can be done on the TSAN side to account for this.

Thanks for the investigation! That's a clear and concise explanation.

Even if TSan were updated to correctly intercept all the legacy `pthread_*` calls, it could still fail to observe some synchronization primitives such as inlined atomics. TSan in general isn't guaranteed to play nicely with uninstrumented libraries (i.e., libraries that haven't been recompiled with TSan). [1] 

Rather than fixing TSan to intercept the legacy `pthread_*` calls - which is only a partial fix - would it be feasible for NVIDIA to ship Vulkan libraries that are compiled with TSan (and the latest version of glibc)?

----

[1] https://github.com/google/sanitizers/wiki/ThreadSanitizerCppManual
'ThreadSanitizer generally requires all code to be compiled with -fsanitize=thread. If some code (e.g. dynamic libraries) is not compiled with the flag, it can lead to false positive race reports, false negative race reports and/or missed stack frames in reports depending on the nature of non-instrumented code. ...
There are some precedents of making ThreadSanitizer work with non-instrumented libraries. Success of this highly depends on what exactly these libraries are doing.'

**Comment by teleprint-me** [comment]
I'm experiencing what I believe is a false positive memory leak reported by **AddressSanitizer (ASAN)** when using **Vulkan Validation Layers**. This issue arises specifically during program **exit**, not runtime.

---

### **Reproducible Scenario**  
- **Environment**:
   - GPU: AMD
   - Vulkan Validation Layers: Latest version (as of `1.3.296.0-1`)
   - Compiler: GCC `14.2.1`
   - AddressSanitizer: Enabled with `-fsanitize=address` during compilation

- **Observation**:
   - ASAN reports a **128-byte leak** during program teardown.
   - Leak originates from calls involving `pthread_once` and `realloc`, both of which are used internally by Vulkan Validation Layers or their dependencies (e.g., ICU).

- **Behavior**:
   - The leak occurs **after `main()` exits successfully**.
   - Valgrind, on the other hand, reports **no issues**. This strongly suggests a **false positive** in ASAN.

---

### **Key Findings**
1. **Similar Issue**:  
   - This seems like a related problem reported here.
     While I use ASAN and AMD instead of TSAN and NVIDIA, the symptoms appear similar:
     - Sanitizers struggle to intercept certain calls (`pthread_once`, `malloc`, etc.) in **non-instrumented libraries** like Vulkan drivers and validation layers.

2. **Root Cause**:
   - **Sanitizers** (ASAN/TSAN) assume that all code is instrumented.
   - When **external libraries** are prebuilt without sanitizer instrumentation:
     - Calls to memory allocators (`malloc`, `realloc`) are intercepted.
     - Calls to threading primitives (`pthread_once`, etc.) are **not** properly intercepted.
   - This mismatch leaves sanitizers unable to safely track cleanup, resulting in false positives.

3. **Validation**:
   - Disabling Vulkan validation layers removes the leak report.
   - Valgrind confirms the program is clean, with **no memory leaks**.

---

### **Steps Taken**
- Suppressed the false positives using `LSAN_OPTIONS`:
   ```plaintext
   leak:*pthread_once
   leak:*realloc
   ```
- Confirmed that the leak only appears with AddressSanitizer enabled.
- Valgrind remains a reliable tool for verification.

---

This appears to be a limitation in how ASAN handles **thread-safe initializers** (`pthread_once`) and **non-instrumented external libraries**.

---

The issue is not with the application code or Vulkan itself but rather with **AddressSanitizer’s limitations** in handling external, non-instrumented libraries. For now, suppressing the false positives and using Valgrind as a secondary verification tool has proven effective.

**Comment by dfaure-kdab** [comment]
@teleprint-me please create a separate report for your ASAN issue. This report is about TSAN.

**Comment by rossant** [comment]
Any news on this? Any workaround to use TSAN on Vulkan-dependent C code?
