### ISSUE TITLE
TSAN init cause Segmentation fault

### ISSUE THREAD

**Issue by lhsoft** [google/sanitizers#1681]
The stack:
`
#0  0x000056184242a0eb in __tsan::TraceSwitchPart(__tsan::ThreadState*) ()  
#1  0x000056184242c612 in __tsan::TraceRestartFuncEntry(__tsan::ThreadState*, unsigned long) (). 
#2  0x0000561844b35be2 in calloc (). 
#3  0x00007fe975ba2a45 in _dlerror_run (operate=operate@entry=0x7fe975ba2390 <dlsym_doit>, args=args@entry=0x7ffca9481090) at dlerror.c:148. 
#4  0x00007fe975ba240f in __dlsym (handle=<optimized out>, name=<optimized out>) at dlsym.c:70. 
#5  0x000056184238e964 in __interception::InterceptFunction(char const*, unsigned long*, unsigned long, unsigned long) (). 
#6  0x00005618423ba142 in __sanitizer::InitializeMemintrinsicInterceptors() (). 
#7  0x00005618423fe042 in InitializeCommonInterceptors() (). 
#8  0x00005618423fcfea in __tsan::InitializeInterceptors() (). 
#9  0x0000561842429247 in __tsan::Initialize(__tsan::ThreadState*) (). 
#10 0x00007fe975d9e4d6 in _dl_init (main_map=0x7fe975db8190, argc=1, argv=0x7ffca94811e8, env=0x7ffca94811f8) at dl-init.c:104. 
#11 0x00007fe975d900ca in _dl_start_user () from /lib64/ld-linux-x86-64.so.2. 
#12 0x0000000000000001 in ?? (). 
#13 0x00007ffca948245b in ?? (). 
#14 0x0000000000000000 in ?? (). 
`

**Comment by rsniezek** [comment]
I had similar issue with application that was linked to an library built with tsan.
I added the sanitizer flags to the app as well but it was crashing because the tsan link flags were in the wrong place: either after the linked library or before it - don't remember now.

If you have similar sitiation, you could check if reordering your link flags helps.
