### ISSUE TITLE
NS_IsMainThread hits "heap-buffer-overflow read of size 4" that is "located 0 bytes inside of 4-byte region"

### ISSUE THREAD

**Issue by ramosian-glider** [google/sanitizers#204]
Originally reported on Google Code with ID 204
```
What steps will reproduce the problem?
1. https://developer.mozilla.org/en-US/docs/Developer_Guide/Build_Instructions/Linux_Prerequisites
2. hg clone -r c5ce065936fa https://hg.mozilla.org/mozilla-central/
3. MOZCONFIG=mozconfig-asan make -f client.mk
4. Try to run Firefox

What is the expected output? What do you see instead?

==21415==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200001cdb0 at
pc 0x7f16c7c39a3d bp 0x7fff8884cc60 sp 0x7fff8884cc58
READ of size 4 at 0x60200001cdb0 thread T0
    #0 0x7f16c7c39a3c in _Z15NS_IsMainThreadv /home/jruderman/trees/mozilla-central/obj-firefox-asan/xpcom/ds/../../dist/include/nsThreadUtils.h:104
...
[callers vary from run to run]
...
0x60200001cdb0 is located 0 bytes inside of 4-byte region [0x60200001cdb0,0x60200001cdb4)
allocated by thread T0 here:
    #0 0x441f5b in __interceptor_memalign _asan_rtl_
    #1 0x7f16d34a1364 in allocate_and_init /build/buildd/eglibc-2.15/elf/dl-tls.c:526

=>0x0c047fffb9b0: fa fa 00 04 fa fa[04]fa fa fa 00 fa fa fa 00 fa

What version of the product are you using? On what operating system?

LLVM r185246 on Ubuntu Linux in a Mozilla datacenter

Please provide any additional information below.

decoder hit a similar problem when he tried to apply the patch from http://code.google.com/p/address-sanitizer/issues/detail?id=193
to the 3.3 branch.

NS_IsMainThread compares a value in thread-local storage to an enum value:

http://mxr.mozilla.org/mozilla-central/source/xpcom/glue/nsThreadUtils.h#102
http://mxr.mozilla.org/mozilla-central/source/xpcom/glue/nsThreadIDs.h

If I build Firefox debug, I hit this in NS_IsCycleCollectorThread instead of NS_IsMainThread.
```

Reported by `jruderman` on 2013-06-29 14:33:24

<hr>
 * *Attachment: [asan-output.txt](https://storage.googleapis.com/google-code-attachments/address-sanitizer/issue-204/comment-0/asan-output.txt)*
 * *Attachment: [mozconfig-asan](https://storage.googleapis.com/google-code-attachments/address-sanitizer/issue-204/comment-0/mozconfig-asan)*

**Comment by kcc** [comment]
Looks like this is fixed, closing. Please file a separate bug if there is still a problem.

**Comment by ramosian-glider** [comment]
Actually closing.
