### ISSUE TITLE
report circular dependencies in leaked circular references

### ISSUE THREAD

**Issue by ramosian-glider** [google/sanitizers#212]
Originally reported on Google Code with ID 212
```
% cat circular_leak.cc 
void foo() {
  void **x = new void *[10];
  void **y = new void *[20];
  x[0] = y;
  y[0] = x;
}

int main() {
  foo();
}
% clang -g  -O1  -fsanitize=address circular_leak.cc; ASAN_OPTIONS=detect_leaks=1 ./a.out


=================================================================
==27597==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 160 byte(s) in 1 object(s) allocated from:
    #0 0x42a071 in operator new[](unsigned long) 
    #1 0x43d167 in foo() circular_leak.cc:3

Indirect leak of 80 byte(s) in 1 object(s) allocated from:
    #0 0x42a071 in operator new[](unsigned long)
    #1 0x43d15a in foo() circular_leak.cc:2

SUMMARY: LeakSanitizer: 240 byte(s) leaked in 2 allocation(s).
% 

It would be great to report that these "Indirect" leaks have circular dependency between
each other. 
```

Reported by `konstantin.s.serebryany` on 2013-08-08 07:34:49

**Comment by kcc** [comment]
Not working on this.
