### ISSUE TITLE
cannot use ASAN w/shared-library code (JVM, JNI)

### ISSUE THREAD

**Issue by ramosian-glider** [google/sanitizers#271]
Originally reported on Google Code with ID 271
```
What steps will reproduce the problem?
1. Compile so w/-fsanitize=address
2. Run code under JVM 
3.

What is the expected output? What do you see instead?
Expected it to work ;-)  What I got instead is:

Exception in thread "main" java.lang.UnsatisfiedLinkError: /home/btorpey/install/bustalk/0.0.0/abim/lib/libnsbjni.so.0.0.0:
/home/btorpey/install/Transact/lib/mama/libTrAdapter.so.0: undefined symbol: __asan_option_detect_stack_use_after_return
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1803)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1728)
	at java.lang.Runtime.loadLibrary0(Runtime.java:823)
	at java.lang.System.loadLibrary(System.java:1028)
	at NSBInterface.<clinit>(NSBInterface.java:82)
	at Route.main(Route.java:227)
[Loaded java.lang.Shutdown from /home/btorpey/jdk1.6.0_21/jre/lib/rt.jar]
[Loaded java.lang.Shutdown$Lock from /home/btorpey/jdk1.6.0_21/jre/lib/rt.jar]
/home/btorpey/btlogs/abim $ 


What version of the product are you using? On what operating system?
clang 3.4, CentOS 6.5


Please provide any additional information below.
Would like to know how to inject ASAN code at runtime.  Rebuilding the JVM is not really
feasible.


```

Reported by `wtorpey` on 2014-02-27 21:56:37

**Comment by ramosian-glider** [comment]
Cool, closing then.
