### ISSUE TITLE
Attempting double-free on IOS with SDL

### ISSUE THREAD

**Issue by ramosian-glider** [google/sanitizers#272]
Originally reported on Google Code with ID 272
```
Hi , 

I am not sure if this issue is with the address-sanitizer or with the SDL lib itself.
But I would appreciate any help.

I have compiled latest llvm and clang from the svn repository under OSX 10.9 .
All the address-sanitizer tests ran correctly. I tried the sanitizer with an IOS app
that I am making. It is IOS 7.0 with SDL lib. 

I have compiled the app with -fsanitize=address for the simulator architecture x86
.
When I do the asan_symbolize.py / < log | c++filt
I got this:

=================================================================
==11907==ERROR: AddressSanitizer: attempting double-free on 0x0ab7aef0 in thread T0:

    #0 0x11e035 in wrap_free _asan_rtl_
    #1 0x5f764 in SDL_DestroySemaphore SDL_syssem.c:119
    #2 0x5f1a0 in SDL_CreateThread SDL_thread.c:382
    #3 0x5fd62 in SDL_TimerInit SDL_timer.c:233
    #4 0xef2e in SDL_InitSubSystem SDL.c:158
    #5 0x2d2f in Game::init Game.cpp:15
    #6 0x5a9d in SDL_main main.cpp:26
    #7 0x95e80 in -[SDLUIKitDelegate postFinishLaunch] SDL_uikitappdelegate.m:189
    #8 0xa3512b in __NSFireDelayedPerform (in Foundation) + 371
    #9 0x29dcbd5 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ (in CoreFoundation)
+ 21
    #10 0x29dc5bc in __CFRunLoopDoTimer (in CoreFoundation) + 1180
    #11 0x29c4627 in __CFRunLoopRun (in CoreFoundation) + 1815
    #12 0x29c3ac2 in CFRunLoopRunSpecific (in CoreFoundation) + 466
    #13 0x29c38da in CFRunLoopRunInMode (in CoreFoundation) + 122
    #14 0x45d19e1 in GSEventRunModal (in GraphicsServices) + 191
    #15 0x45d1808 in GSEventRun (in GraphicsServices) + 103
    #16 0xe0fd3a in UIApplicationMain (in UIKit) + 1224
    #17 0x959aa in main SDL_uikitappdelegate.m:59
    #18 0x2fa770c in start (in libdyld.dylib) + 0
    #19 0x0 in 0x0

0x0ab7aef0 is located 0 bytes inside of 28-byte region [0x0ab7aef0,0x0ab7af0c)
freed by thread T0 here:
==11907==AddressSanitizer CHECK failed: /Users/sabotage3d/DEV/libs/llvm/projects/compiler-unsigned
short restrict/lib/asan/asan_allocator2.cc:237 "((id)) != (0)" (0x0, 0x0)

    #0 0x126de7 in __asan::AsanCheckFailed _asan_rtl_
    #1 0x12ac21 in __sanitizer::CheckFailed sanitizer_common.cc:76


Any ideas ?

Thanks in advance,

Alex

```

Reported by `sabotage3d` on 2014-03-08 21:04:03

**Comment by ramosian-glider** [comment]
According to http://forums.libsdl.org/viewtopic.php?t=10112&sid=e7efecbaea510015c43f17994bc1b5d6 this doesn't look like a problem with ASan.
Closing.
