### ISSUE TITLE
AddressSanitizer should support -MTd/-MDd runtimes

### ISSUE THREAD

**Issue by ramosian-glider** [google/sanitizers#328]
Originally reported on Google Code with ID 328

```
$ cat foo.cpp
#include <stdlib.h>
int f() {
 calloc(1, 1);
 return 1;
}

$ clang-cl -fsanitize=address -c foo.cpp -MTd

$ clang-cl -fsanitize=address foo.obj -LD
libcmtd.lib(dbgheap.obj) : error LNK2005: __calloc_dbg already defined in clang_rt.asan_dll_thunk-i386.lib(asan_dll_thunk.obj)
libcmtd.lib(dbgheap.obj) : error LNK2005: __expand already defined in clang_rt.asan_dll_thunk-i386.lib(asan_dll_thunk.obj)
libcmtd.lib(dbgheap.obj) : error LNK2005: __expand_dbg already defined in clang_rt.asan_dll_thunk-i386.lib(asan_dll_thunk.obj)
libcmtd.lib(dbgheap.obj) : error LNK2005: __free_dbg already defined in clang_rt.asan_dll_thunk-i386.lib(asan_dll_thunk.obj)
libcmtd.lib(dbgheap.obj) : error LNK2005: __malloc_dbg already defined in clang_rt.asan_dll_thunk-i386.lib(asan_dll_thunk.obj)
libcmtd.lib(dbgheap.obj) : error LNK2005: __msize already defined in clang_rt.asan_dll_thunk-i386.lib(asan_dll_thunk.obj)
libcmtd.lib(dbgheap.obj) : error LNK2005: __realloc_dbg already defined in clang_rt.asan_dll_thunk-i386.lib(asan_dll_thunk.obj)
libcmtd.lib(dbgheap.obj) : error LNK2005: __recalloc already defined in clang_rt.asan_dll_thunk-i386.lib(asan_dll_thunk.obj)
LINK : warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library
foo.dll : fatal error LNK1169: one or more multiply defined symbols found
clang-cl.exe: error: linker command failed with exit code 1169 (use -v to see invocation)

$ clang-cl -fsanitize=address foo.obj
libcmtd.lib(dbgheap.obj) : error LNK2005: __calloc_dbg already defined in clang_rt.asan-i386.lib(asan_malloc_win.obj)
libcmtd.lib(dbgheap.obj) : error LNK2005: __expand already defined in clang_rt.asan-i386.lib(asan_malloc_win.obj)
libcmtd.lib(dbgheap.obj) : error LNK2005: __expand_dbg already defined in clang_rt.asan-i386.lib(asan_malloc_win.obj)
libcmtd.lib(dbgheap.obj) : error LNK2005: __free_dbg already defined in clang_rt.asan-i386.lib(asan_malloc_win.obj)
libcmtd.lib(dbgheap.obj) : error LNK2005: __malloc_dbg already defined in clang_rt.asan-i386.lib(asan_malloc_win.obj)
libcmtd.lib(dbgheap.obj) : error LNK2005: __msize already defined in clang_rt.asan-i386.lib(asan_malloc_win.obj)
libcmtd.lib(dbgheap.obj) : error LNK2005: __realloc_dbg already defined in clang_rt.asan-i386.lib(asan_malloc_win.obj)
libcmtd.lib(dbgheap.obj) : error LNK2005: __recalloc already defined in clang_rt.asan-i386.lib(asan_malloc_win.obj)
   Creating library foo.lib and object foo.exp
LINK : fatal error LNK1561: entry point must be defined
clang-cl.exe: error: linker command failed with exit code 1561 (use -v to see invocation)
```

Reported by `ehsan.akhgari` on 2014-07-26 17:44:21

**Comment by rnk** [comment]
This is still important, it's really annoying for users. Typically you want to run ASan builds with normal application assertions enabled. Windows applications often put those checks behind the _DEBUG macro. The _DEBUG macro is used by the CRT headers to determine if the debug or release CRTs are being used.

So, we really should deal with this eventually.

**Comment by morehouse** [comment]
@rnk:  What difficulties do we have adding support for `-MTd` and `-MDd` now that `-MD` is supported?

**Comment by mcgov** [comment]
I have some work coming for this work item, just as a heads up.

**Comment by hofst** [comment]
@rnk is there an update on this? We would really like to use ASAN with /MTd in our project

**Comment by rnk** [comment]
No, there is no update. Windows ASan is not supported by anyone full time at the moment.

**Comment by mcgov** [comment]
I'm working on a fix for this and it's still early in the development phase, but work is happening.

**Comment by hofst** [comment]
@mcgov great, thank you! I'm happy to test it in our CI/CD pipeline if you could ping when it is ready :)

**Comment by lo1ol** [comment]
Hi there, I found that clang-cl doesn't use special `_dbg_` versions of asan, but msvc is:

```bash
$ cl.exe  /MDd "-fsanitize=address"    main.c
$ ldd main.exe
...
        clang_rt.asan_dbg_dynamic-x86_64.dll => /c/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/HostX64/x64/clang_rt.asan_dbg_dynamic-x86_64.dll (0x7fff1aaa0000)
...

$ clang-cl.exe  /MDd "-fsanitize=address" main.c
$ ldd main.exe
...
        clang_rt.asan_dynamic-x86_64.dll => /c/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/HostX64/x64/clang_rt.asan_dynamic-x86_64.dll (0x7fff1aaa0000)
....
```

So I simply substituted names of used asan libs inside LLVM project and it's works:
```bash
$ clang-cl.exe  /MTd "-fsanitize=address" main.c

$ main.exe
kek
=================================================================
==30680==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x11aba01200f8 at pc 0x7ff6d54d1076 bp 0x00561caff6f0 sp 0x00561caff6f8
WRITE of size 4 at 0x11aba01200f8 thread T0
    #0 0x7ff6d54d1075 in main (C:\Users\lolol\Projects\test\main.exe+0x140001075)
    #1 0x7ff6d551a408 in invoke_main d:\a01\_work\12\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
    #2 0x7ff6d551a35d in __scrt_common_main_seh d:\a01\_work\12\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    #3 0x7ff6d551a21d in __scrt_common_main d:\a01\_work\12\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:330
    #4 0x7ff6d551a47d in mainCRTStartup d:\a01\_work\12\s\src\vctools\crt\vcstartup\src\startup\exe_main.cpp:16
    #5 0x7fff844d54df  (C:\Windows\System32\KERNEL32.DLL+0x1800154df)
    #6 0x7fff85c6485a  (C:\Windows\SYSTEM32\ntdll.dll+0x18000485a)

0x11aba01200f8 is located 0 bytes to the right of 8-byte region [0x11aba01200f0,0x11aba01200f8)
allocated by thread T0 here:
    #0 0x7ff6d54fd591 in malloc D:\a01\_work\2\s\src\vctools\crt\asan\llvm\compiler-rt\lib\asan\asan_malloc_win.cpp:118
    #1 0x7ff6d54d1025 in main (C:\Users\lolol\Projects\test\main.exe+0x140001025)
    #2 0x7ff6d551a408 in invoke_main d:\a01\_work\12\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
    #3 0x7ff6d551a35d in __scrt_common_main_seh d:\a01\_work\12\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    #4 0x7ff6d551a21d in __scrt_common_main d:\a01\_work\12\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:330
    #5 0x7ff6d551a47d in mainCRTStartup d:\a01\_work\12\s\src\vctools\crt\vcstartup\src\startup\exe_main.cpp:16
    #6 0x7fff844d54df  (C:\Windows\System32\KERNEL32.DLL+0x1800154df)
    #7 0x7fff85c6485a  (C:\Windows\SYSTEM32\ntdll.dll+0x18000485a)
...
```

Also I remove [this check](https://github.com/llvm/llvm-project/blob/8fee667d31f6af9a8a6b44b120164fff4f65d198/clang/lib/Driver/SanitizerArgs.cpp#L817).

Normal patch for LLVM I provide later. But think that problem linked that MSVC uses special versions of asan libs, but clang is not

**Comment by lo1ol** [comment]
https://reviews.llvm.org/D119711

**Comment by dantamont** [comment]
Have there been any updates on this? It'd be convenient to be able to enable address sanitation in debug mode:

`Error		invalid argument '-MDd' not allowed with '-fsanitize=address' [clang-diagnostic-error]`

**Comment by laurynas-biveinis** [comment]
> Have there been any updates on this? It'd be convenient to be able to enable address sanitation in debug mode:
> 
> `Error invalid argument '-MDd' not allowed with '-fsanitize=address' [clang-diagnostic-error]`

MSVC 17.7 is said to address this: https://devblogs.microsoft.com/cppblog/msvc-address-sanitizer-one-dll-for-all-runtime-configurations/

I wish I could confirm this, because MSVC 17.7 also started crashing with internal compiler error on my project ¯\_(ツ)_/¯

**Comment by iyadahmed** [comment]
Is this solved yet?
it seems that on MSVC everythings works, but clangd 17 reports the error
