### ISSUE TITLE
ASan with online symbolizer sometimes produces mangled function names

### ISSUE THREAD

**Issue by ramosian-glider** [google/sanitizers#335]
Originally reported on Google Code with ID 335
```
In Chromium:

$ git pull 67fa5e94bdbd9eb7bce39c0cd6922321cf4998c9 && gclient sync
$ GYP_GENERATORS=ninja GYP_DEFINES="asan=1 lsan=1" gclient runhooks && ninja dbus_unittests
$ ASAN_OPTIONS=symbolize=1:detect_leaks=1 out/Release/dbus_unittests --gtest_filter=ObjectManagerTest.RemoveSecondObject
2>&1 | grep _ZN4base4BindIMN4dbus17ObjectMa

    #1 0x583b2a in _ZN4base4BindIMN4dbus17ObjectManagerTestEFvRKNS1_10ObjectPathERKNSt3__112basic_stringIcNS6_11char_traitsIcEENS6_9allocatorIcEEEEENS_8internal17UnretainedWrapperIS2_EES3_EENS_8CallbackINSH_9BindStateINSH_13FunctorTraitsIT_E12RunnableTypeENSO_7RunTypeEFvNSH_19CallbackParamTraitsIT0_Xsr14IsMoveOnlyTypeISS_EE5valueEE11StorageTypeENSR_IT1_Xsr14IsMoveOnlyTypeISV_EE5valueEE11StorageTypeEEE14UnboundRunTypeEEESN_RKSS_RKSV_
base/bind.h:168:3
    #7 0x583c8c in _ZN4base4BindIMN4dbus17ObjectManagerTestEFvRKNS1_10ObjectPathERKNSt3__112basic_stringIcNS6_11char_traitsIcEENS6_9allocatorIcEEEEENS_8internal17UnretainedWrapperIS2_EES3_EENS_8CallbackINSH_9BindStateINSH_13FunctorTraitsIT_E12RunnableTypeENSO_7RunTypeEFvNSH_19CallbackParamTraitsIT0_Xsr14IsMoveOnlyTypeISS_EE5valueEE11StorageTypeENSR_IT1_Xsr14IsMoveOnlyTypeISV_EE5valueEE11StorageTypeEEE14UnboundRunTypeEEESN_RKSS_RKSV_
base/bind.h:168

```

Reported by `earthdok@google.com` on 2014-08-29 20:04:14

**Comment by kcc** [comment]
Closing as stale.
