### ISSUE TITLE
chdir breaks symbolization of dynamic libraries

### ISSUE THREAD

**Issue by ramosian-glider** [google/sanitizers#405]
Originally reported on Google Code with ID 405

```
The program is:

// 1.c
#include <unistd.h>
#include <dlfcn.h>

int main() {
  void *handle = dlopen("./s.so", RTLD_LAZY);
  void (*f)() = (void (*)())dlsym(handle, "run");
  chdir("/tmp");  // breaks symbolization
  (*f)();
  return 0;
}

// 2.c
#include <stdlib.h>
void run() {
  void *p = malloc(1);
  *(volatile int *)p = 42;
}

Build as:

$ clang -fsanitize=address 1.c -g
$ clang -fsanitize=address 2.c -o s.so -shared -fPIC -g

When run s.so is not symbolized:

$ ./a.out 

==7130==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200000efd0 at
pc 0x7ffaeaafe7eb bp 0x7ffc4faf8500 sp 0x7ffc4faf84f8
WRITE of size 4 at 0x60200000efd0 thread T0
LLVMSymbolizer: error reading file: No such file or directory.
    #0 0x7ffaeaafe7ea  (s.so+0x7ea)
    #1 0x4ddc24 in main /tmp/111.c:8:3
    #2 0x7ffaed3e4ec4 in __libc_start_main /build/buildd/eglibc-2.19/csu/libc-start.c:287
    #3 0x4186e5 in _start (/usr/local/google/home/dvyukov/src/llvm/a.out+0x4186e5)

If chdir is commented out, then s.so is symbolized.

```

Reported by `dvyukov@google.com` on 2015-08-20 18:10:22

**Comment by morehouse** [comment]
@dvyukov:  Is this still an issue?

**Comment by jbulow** [comment]
Yes, still a problem.

```
==23656==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000000030 at pc 0x7f498bcfe72b bp 0x7fffeaeab900 sp 0x7fffeaeab8f8
WRITE of size 4 at 0x602000000030 thread T0
LLVMSymbolizer: error reading file: No such file or directory
    #0 0x7f498bcfe72a  (s.so+0x72a)
    #1 0x4f1394 in main /home/jonasbu/test/1.c:8:3
    #2 0x7f498f1a782f in __libc_start_main /build/glibc-Cl5G7W/glibc-2.23/csu/../csu/libc-start.c:291
    #3 0x41a458 in _start (/home/jonasbu/test/a.out+0x41a458)

0x602000000031 is located 0 bytes to the right of 1-byte region [0x602000000030,0x602000000031)
allocated by thread T0 here:
    #0 0x4c2383 in __interceptor_malloc /home/jonasbu/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:146:3
    #1 0x7f498bcfe6e3  (s.so+0x6e3)
    #2 0x4f1394 in main /home/jonasbu/test/1.c:8:3
    #3 0x7f498f1a782f in __libc_start_main /build/glibc-Cl5G7W/glibc-2.23/csu/../csu/libc-start.c:291

SUMMARY: AddressSanitizer: heap-buffer-overflow (s.so+0x72a)
Shadow bytes around the buggy address:
  0x0c047fff7fb0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff7fc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff7fd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff7fe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff7ff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c047fff8000: fa fa 07 fa fa fa[01]fa fa fa fa fa fa fa fa fa
  0x0c047fff8010: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8020: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8030: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8040: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8050: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==23656==ABORTING

````

```
clang --version
clang version 7.0.0 (https://llvm.org/git/clang.git aa3be4e3c06473db5996695a3ab9755aee5f9f9d) (https://llvm.org/git/llvm.git 6ac04e25a3a4078ece43cc6062286bc6270b5f3e)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/jonasbu/local/bin

```
