### ISSUE TITLE
False positives with qsort, std::stringstream, and AVX

### ISSUE THREAD

**Issue by ramosian-glider** [google/sanitizers#557]
Originally reported on Google Code with ID 54

```
What steps will reproduce the problem?
1. Compile libcxx & libcxxabi with msan
2. Compile test program with
clang++ -fsanitize=memory -O2 -fno-omit-frame-pointer -stdlib=libc++ -I$LIBCXX/include
-L$LIBCXX/lib -Wl,-R$LIBCXX/lib -lc++abi

With a test like:
#include <sstream>
int main() {
    std::stringstream ss;
    ss<<1;
    return 0;
}

Let me know if you need a small test cases for qsort or AVX.

I get 
==13450== WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7f86eb78ae7b in std::__1::basic_ostream<char, std::__1::char_traits<char>
>::operator<<(int) (/home/rschulz/download/gromacs5.0/clang35.msan.sse/a.out+0x9be7b)
    #1 0x7f86eb78a5c1 in main (/home/rschulz/download/gromacs5.0/clang35.msan.sse/a.out+0x9b5c1)

What version of the product are you using? On what operating system?
This is both with 3.4.1 and trunk (http://llvm.org/git/clang.git d23fd9aa52efc751322fbf7a3fc125ce58d44e4c)
(http://llvm.org/git/llvm.git fd76d8a72dac035a4e1963bc6fe635a3b688cfcd). libcxx/libcxxabi
are also trunk (208925). This is without dynamic instrumentation on Linux.


```

Reported by `roland@rschulz.eu` on 2014-05-15 22:29:14

**Comment by krytarowski** [comment]
I will try to put qsort(3) into sanitizers and check whether this is a step forward.

**Comment by krytarowski** [comment]
After further research I've concluded that the best option is to modify the libc and introduce 3 symbols:

- `__issanitized`
- `__libc_poison_memory_region`
- `__libc_unpoison_memory_region`

We need this for at least 3 sorting functions and a bunch of indirect users:

 - qsort(3) heapsort(3) mergesort(3)
 - fts_open(3)
 - alphasort(3)
 - scandir(3)
 - tdelete(3) twalk(3) tfind(3) tsearch(3)
 - bsearch(3)

**Comment by zoulasc** [comment]
Can you show an example implementation and use?

**Comment by krytarowski** [comment]
There are likely other users needing similar unpoisoning from libc, like: pwcache_userdb(3).

**Comment by krytarowski** [comment]
@dvyukov is there something like __asan_{,un}poision_memory_range() in TSan?

Are there similar scenarios/cases when we would need to help TSan from the internals of libc?

**Comment by eugenis** [comment]
Some of these functions, like tsearch, have interceptors in
sanitizer_common. Are they not enough?
You could add a qsort interceptor, too.

**Comment by krytarowski** [comment]
They are not enough, because once the callback is called, its arguments passed from the internals of libc aren't unpoisoned.

**Comment by eugenis** [comment]
Arguments passed by pointer? The interceptor can potentially unpoison
those. And for by-value parameters there is a macro somewhere, too.

Anyway, I would not mind if you solve this in libc!
How would __issanitized be implemented? A weak definition in libc, possibly
overridden by sanitizer runtime library? Might be easier to add a weak
declaration of __asan_init or some other known symbol and compare its
address with zero, we do this somewhere else already.

**Comment by krytarowski** [comment]
> Arguments passed by pointer?

Right, the arguments are passed by pointer. The data can be allocated and initialized inside libc, and passed by pointer to a callback function. In the fts_open(3) case, for the purpose of sorting files according to predefined rules in a program.

There would be an option to change userland programs and in such cases introduce UNPOISON/POISON macros.

I think that this is unacceptable and I'm trying to handle this in libc.

Example of code:
http://netbsd.org/%7Ekamil/llvm/fts_open.c

Regarding the implementation, I'm right now working on this with ELF weak/strong linking rules.. once I will get it to work I will show it.. hopefully soon.

**Comment by krytarowski** [comment]
After more research and playing with the implementation, it turned out that this would be useful only for MSan (from the currently supported sanitizers), however calling comparison functions through qsort(3) and similar functions has performance impact for all users and it requires specially patched libc.

I'm going to add direct implementation of __msan_unpoison() inside users (like ls(1)) of these APis, protected with ifdefs. This will restrict overhead and sanitization to programs that really want it.

Thank you for the feedback!

**Comment by krytarowski** [comment]
After some more discussion with the NetBSD developers, an approach to patch the userland programs and include conditional __msan_unpoison() has been requested/suggested to be replaced with a closure during code generation in Clang, for the fts_open(3) case.

We need to pass there comparison callback function, that is wrapped by a closure that initializes arguments of the callback and calls real function.

So a code like:

```
ftsp = fts_open(argv, options, mastercmp);
```

will generate for MSan:

```
static int
__sanitizer_fts_open_mastercmp(const FTSENT **a, const FTSENT **b)
{
	__msan_unpoison(a, sizeof(void*));
	__msan_unpoison(b, sizeof(void*));

	__msan_unpoison(*a, sizeof(FTSENT));
	__msan_unpoison(*b, sizeof(FTSENT));
        return mastercmp(a, b);
}
[...]
ftsp = fts_open(argv, options, __sanitizer_fts_open_mastercmp);
```

I have no experience in Clang code generation, a suggestion how to start is welcome :)

**Comment by eugenis** [comment]
I must be missing something big here.
Why not add an interceptor for fts_open?

**Comment by yugr** [comment]
@eugenis Probly because there's no `fts_open_r` so one can't easily wrap user's callback with unpoisoning wrapper.

On the other hand  `fts_open` and other functions seems to delegate sorting to `qsort` so it's not clear why anything else needs to be modified. Is that internal Glibc calls to `qsort` are not interceptable?

**Comment by krytarowski** [comment]
Right, there is no fts_open_r like version.

We have got an interceptor. but once we call `REAL(fts_open)` - libc calls from its internals a callback function, before returning from the `fts_open(3)` call.

Internally `fts_open` allocates, initializes and sorts with qsort(3) the data (`FTSENT` array). And that qsort(3) function can use user specified callback for comparison of elements.

**Comment by krytarowski** [comment]
Potential intercepting qsort(3) does not help, as we need to unpoison not just passed pointers, but also under-laying data.

Additionally we prefer to disable recursive interceptors for MSan.

**Comment by krytarowski** [comment]
https://github.com/NetBSD/src/blob/trunk/lib/libc/gen/fts.c#L118 the implmenentation of fts_open(3)

**Comment by yugr** [comment]
>> Probly because there's no fts_open_r so one can't easily wrap user's callback with unpoisoning wrapper.
> Right, there is no fts_open_r like version.

Have you considered passing address to original comparison function through TLS? Modifying compiler sounds like an overkill...

BTW you may want to add {radix,version}sort(3) to your list.

**Comment by krytarowski** [comment]
Sorting can be invoked from other functions than fts_open(3), e.g. from fts_read(3) and it can be called from a different thread. However maybe I can get access to FTSENT elements from FTS after the successful call from fts_open(3).

I will give it a try!

**Comment by eugenis** [comment]
Btw, https://bugs.llvm.org/show_bug.cgi?id=17267 speaks of the same problem
on linux. We already have interceptors that wrap a callback to a libc
function using TLS, the same trick can be used here. That would definitely
be easier than modifying the compiler.

**Comment by krytarowski** [comment]
This report looks related. TLS should do the trick.

I will give it a try, but after a while as I'm swamped with MKSANITZIER (https://github.com/google/sanitizers/issues/955), I've just booted successfully the NetBSD system with the whole userland prebuilt with UBSan... and I'm running regression tests and keep fixing issues.

We have got now downstream like 150 new interceptors for sanitizers... I will work on upstreaming all of them... including the fts(3) interfaces, as we require them for at least ls(1), find(1) and mtree(8).

**Comment by eugenis** [comment]
On Mon, Jun 11, 2018 at 4:19 PM, Kamil Rytarowski <notifications@github.com>
wrote:

> This report looks related. TLS should do the trick.
>
> I will give it a try, but after a while as I'm swamped with MKSANITZIER (
> #955 <https://github.com/google/sanitizers/issues/955>), I've just booted
> successfully the NetBSD system with the whole userland prebuilt with
> UBSan... and I'm running regression tests and keep fixing issues.
>
Nice!


> We have got now downstream like 150 new interceptors for sanitizers... I
> will work on upstreaming all of them... including the fts(3) interfaces, as
> we require them for at least ls(1), find(1) and mtree(8).
>
Sounds good. If your platform requires that many custom interceptors, it
would be great to put them in a separate file. Common_interceptors has
grown big enough.

**Comment by krytarowski** [comment]
> Sounds good. If your platform requires that many custom interceptors, it would be great to put them in a separate file. Common_interceptors has grown big enough.

Most of them are shared with other systems.. so we prefer to keep them in common. There are also downstream systems polling libc from NetBSD (Minix, newlib. Android..). There are also some other reasons why we need more inteceptors than GNU... as we control our userland tools in one tree and we can nicely put common parts into libc or similar library without bothering about interoperability.
