### ISSUE TITLE
Missing origin in memmove()

### ISSUE THREAD

**Issue by ramosian-glider** [google/sanitizers#564]
Originally reported on Google Code with ID 61

```
#include <string.h>
#include <sanitizer/msan_interface.h>

const int SZ = 3;
int arr[SZ];

int main(int argc, char *argv[]) {
  __msan_allocated_memory(&arr, sizeof(*arr) * 2);
  memmove(arr + 1, arr, sizeof(*arr) * 2);
  __msan_print_shadow(&arr, sizeof(arr));
  return 0;
}

Compile with
-fsanitize=memory -fsanitize-memory-track-origins=2 -o t -g -O2 -fno-omit-frame-pointer
-fno-inline


Shadow map of [0x3f774f4aab68, 0x3f774f4aab74), 12 bytes:
0x3f774f4aab68: ffffffff ffffffff ffffffff ........  |A B C .|

Origin A (origin_id 35c00001):
  Uninitialized value was created by a heap allocation
    #0 0x7f774cdd9260 in __msan_allocated_memory projects/compiler-rt/lib/msan/msan_interceptors.cc:840
    #1 0x7f774ce0f620 in main 2.cc:8:3
    #2 0x7f774b97f78c in __libc_start_main /build/buildd/eglibc-2.15/csu/libc-start.c:226

Origin B (origin_id 55c00002):
  Uninitialized value was stored to memory at
    #0 0x7f774ce0f691 in main 2.cc:9:3
    #1 0x7f774b97f78c in __libc_start_main /build/buildd/eglibc-2.15/csu/libc-start.c:226

  Uninitialized value was created by a heap allocation
    #0 0x7f774cdd9260 in __msan_allocated_memory projects/compiler-rt/lib/msan/msan_interceptors.cc:840
    #1 0x7f774ce0f620 in main 2.cc:8:3
    #2 0x7f774b97f78c in __libc_start_main /build/buildd/eglibc-2.15/csu/libc-start.c:226

Origin C (origin_id 0):
  invalid origin id(0)

```

Reported by `eugenis@google.com` on 2014-08-05 12:29:29

**Comment by morehouse** [comment]
@eugenis:  Status?

**Comment by eugenis** [comment]
Does not reproduce in ToT.
