### ISSUE TITLE
blacklist does not seem to work for interceptor functions

### ISSUE THREAD

**Issue by ramosian-glider** [google/sanitizers#570]
Originally reported on Google Code with ID 67
```
What steps will reproduce the problem?
1.
--- foo.cxx -----
#include <stdlib.h>
#include <string.h>

int bad_foo() {
  char* s = new char[10];
  int i = strlen(s);
  return i;
}

int main() { return bad_foo(); }
2.
 cat bl.txt
fun:bad_foo
fun:*strlen*
3.
clang++ -fsanitize=memory -fsanitize-blacklist=bl.txt -fPIE -pie -fno-omit-frame-pointer
-g -O2 foo.cxx
./a.out
UMR in __interceptor_strlen at offset 0 inside [0x60200000f7f0, +1) 
==10520== WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7f57737abb66 in bad_foo() /home/hoffman/foo.cxx:6
    #1 0x7f57737abb66 in main /home/hoffman/foo.cxx:18
    #2 0x7f5772324ec4 (/lib/x86_64-linux-gnu/libc.so.6+0x21ec4)
    #3 0x7f57737ab9cc in _start (/home/hoffman/a.out+0x739cc)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /home/hoffman/foo.cxx:6 bad_foo()

What is the expected output? What do you see instead?
I would expect there to be some way to black list this call.  bad_foo does not work
and strlen does not work either.

What version of the product are you using? On what operating system?
linux ubuntu clang3.4


```

Reported by `bill.hoffman@kitware.com` on 2014-10-09 00:48:09

**Comment by kcc** [comment]
Closing as stale. Please open new bug(s) if something work is still required.
