### ISSUE TITLE
LLVM symbolizer prints wrong function name if __attribute__((alias)) is involved.

### ISSUE THREAD

**Issue by chefmax** [google/sanitizers#617]
Not sure if it's a real bug, but still reporting.

Consider:
```
max@max:/tmp$ cat test.c

int foo (int N) {
  int a[10];
  return a[N]; // BOOM
}

int bar (int N) __attribute__((alias("foo")));

int main () {
  return foo (11);
}

max@max:/tmp$ clang -fsanitize=address test.c -o test.x -g
max@max:/tmp$ ./test.x 
=================================================================
==21641==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffdbe78924c at pc 0x0000004d26dd bp 0x7ffdbe7891f0 sp 0x7ffdbe7891e8
READ of size 4 at 0x7ffdbe78924c thread T0
    #0 0x4d26dc in bar (/tmp/test.x+0x4d26dc)      <========================
    #1 0x4d2758 in main (/tmp/test.x+0x4d2758)
    #2 0x7f044742dec4 in __libc_start_main /build/buildd/eglibc-2.19/csu/libc-start.c:287
    #3 0x418065 in _start (/tmp/test.x+0x418065)

Address 0x7ffdbe78924c is located in stack of thread T0 at offset 76 in frame
    #0 0x4d25cf in bar (/tmp/test.x+0x4d25cf)

  This frame has 1 object(s):
    [32, 72) 'a' <== Memory access at offset 76 overflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow (/tmp/test.x+0x4d26dc) in bar
Shadow bytes around the buggy address:
  0x100037ce91f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100037ce9200: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100037ce9210: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100037ce9220: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100037ce9230: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x100037ce9240: f1 f1 f1 f1 00 00 00 00 00[f3]f3 f3 f3 f3 f3 f3
  0x100037ce9250: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100037ce9260: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100037ce9270: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100037ce9280: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100037ce9290: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==21641==ABORTING
```
Why LLVM symbolizer prints alias name here (bar)? For me, expected output would a be real function name (foo), just like for adde2line symbolizer and GCC-compiled binary (libbacktrace symbolizer):
```
max@max:/tmp$ sudo mv /usr/local/bin/llvm-symbolizer /usr/local/bin/llvm-symbolizer-1
max@max:/tmp$ ASAN_OPTIONS=allow_addr2line=true ./test.x 
=================================================================
==21798==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffc61c66bec at pc 0x0000004d26dd bp 0x7ffc61c66b90 sp 0x7ffc61c66b88
READ of size 4 at 0x7ffc61c66bec thread T0
    #0 0x4d26dc in foo /tmp/test.c:3    <===========================
    #1 0x4d2758 in main /tmp/test.c:9
    #2 0x7fe1dc9b4ec4 in __libc_start_main /build/buildd/eglibc-2.19/csu/libc-start.c:287
    #3 0x418065 in _start (/tmp/test.x+0x418065)

Address 0x7ffc61c66bec is located in stack of thread T0 at offset 76 in frame
    #0 0x4d25cf in foo /tmp/test.c:1

  This frame has 1 object(s):
    [32, 72) 'a' <== Memory access at offset 76 overflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow /tmp/test.c:3 in foo
Shadow bytes around the buggy address:
  0x10000c384d20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10000c384d30: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10000c384d40: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10000c384d50: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10000c384d60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x10000c384d70: 00 00 00 00 f1 f1 f1 f1 00 00 00 00 00[f3]f3 f3
  0x10000c384d80: f3 f3 f3 f3 00 00 00 00 00 00 00 00 00 00 00 00
  0x10000c384d90: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10000c384da0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10000c384db0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10000c384dc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==21798==ABORTING
```

In any case, different function names coming from different symbolizers is a bit confusing to me.

**Comment by dvyukov** [comment]
These symbols are indistinguishable in binary, so I am not sure it is possible to fix this.

```
$ nm -A a.out | egrep "foo|bar"
a.out:00000000004006fd T bar
a.out:00000000004006fd T foo
```

```
$ readelf -a a.out | egrep "foo|bar"
    59: 00000000004006fd   146 FUNC    GLOBAL DEFAULT   13 bar
    68: 00000000004006fd   146 FUNC    GLOBAL DEFAULT   13 foo
```

**Comment by chefmax** [comment]
Well, this is true if we look to symtab, but if we have a debug info, perhaps we can distinguish them:

```
  Compilation Unit @ offset 0x55f90:
   Length:        0x92 (32-bit)
   Version:       4
   Abbrev Offset: 0x1ac6
   Pointer Size:  8
 <0><55f9b>: Abbrev Number: 1 (DW_TAG_compile_unit)
    <55f9c>   DW_AT_producer    : (indirect string, offset: 0x0): clang version 3.8.0 (https://github.com/llvm-mirror/clang 55216ae753b15189b5da72e5b287b4c7fe3208fc) (https://github.com/llvm-mirror/llvm e123ed65877ee3e2a26188b821b700cd51521b19)    
    <55fa0>   DW_AT_language    : 12    (ANSI C99)
    <55fa2>   DW_AT_name        : (indirect string, offset: 0x9055): test.c     
    <55fa6>   DW_AT_stmt_list   : 0x644fe       
    <55faa>   DW_AT_comp_dir    : (indirect string, offset: 0x905c): /tmp       
    <55fae>   DW_AT_low_pc      : 0x4d25c0      
    <55fb6>   DW_AT_high_pc     : 0x19f 
 <1><55fba>: Abbrev Number: 2 (DW_TAG_subprogram)
    <55fbb>   DW_AT_low_pc      : 0x4d25c0      
    <55fc3>   DW_AT_high_pc     : 0x17f 
    <55fc7>   DW_AT_frame_base  : 1 byte block: 56      (DW_OP_reg6 (rbp))
    <55fc9>   DW_AT_name        : (indirect string, offset: 0x9061): foo      <==================  
    <55fcd>   DW_AT_decl_file   : 1     
    <55fce>   DW_AT_decl_line   : 1     
    <55fcf>   DW_AT_prototyped  : 1     
    <55fcf>   DW_AT_type        : <0x5600b>     
    <55fd3>   DW_AT_external    : 1     
 <2><55fd3>: Abbrev Number: 3 (DW_TAG_formal_parameter)
    <55fd4>   DW_AT_location    : 3 byte block: 73 c4 0         (DW_OP_breg3 (rbx): 68)
    <55fd8>   DW_AT_name        : (indirect string, offset: 0x9065): N  
    <55fdc>   DW_AT_decl_file   : 1     
    <55fdd>   DW_AT_decl_line   : 1     
    <55fde>   DW_AT_type        : <0x5600b>     
 <2><55fe2>: Abbrev Number: 4 (DW_TAG_variable)
    <55fe3>   DW_AT_location    : 0x0   (location list)
    <55fe7>   DW_AT_name        : (indirect string, offset: 0x2b9f): a  
    <55feb>   DW_AT_decl_file   : 1     
    <55fec>   DW_AT_decl_line   : 2     
    <55fed>   DW_AT_type        : <0x56012>     
 <2><55ff1>: Abbrev Number: 0
 <1><55ff2>: Abbrev Number: 5 (DW_TAG_subprogram)
    <55ff3>   DW_AT_low_pc      : 0x4d2740      
    <55ffb>   DW_AT_high_pc     : 0x1f  
    <55fff>   DW_AT_frame_base  : 1 byte block: 56      (DW_OP_reg6 (rbp))
    <56001>   DW_AT_name        : (indirect string, offset: 0x1995): main       
    <56005>   DW_AT_decl_file   : 1     
    <56006>   DW_AT_decl_line   : 8     
    <56007>   DW_AT_type        : <0x5600b>     
    <5600b>   DW_AT_external    : 1     
 <1><5600b>: Abbrev Number: 6 (DW_TAG_base_type)
    <5600c>   DW_AT_name        : (indirect string, offset: 0x2eb4): int        
    <56010>   DW_AT_encoding    : 5     (signed)
    <56011>   DW_AT_byte_size   : 4     
 <1><56012>: Abbrev Number: 7 (DW_TAG_array_type)
    <56013>   DW_AT_type        : <0x5600b>     
 <2><56017>: Abbrev Number: 8 (DW_TAG_subrange_type)
    <56018>   DW_AT_type        : <0x5601e>     
    <5601c>   DW_AT_count       : 10    
 <2><5601d>: Abbrev Number: 0
 <1><5601e>: Abbrev Number: 9 (DW_TAG_base_type)
    <5601f>   DW_AT_name        : (indirect string, offset: 0x9067): sizetype   
    <56023>   DW_AT_byte_size   : 8     
    <56024>   DW_AT_encoding    : 7     (unsigned)
 <1><56025>: Abbrev Number: 0
```

Here, the original symbol **foo** is mentioned, but alias **bar** is not. I suspect addr2line and libbacktrace take advantage of this fact in their symbolization work.

**Comment by dvyukov** [comment]
We especially look at symbol table, because it is less often stripped.
It is probably nice to have, but I don't see it as high priority.

**Comment by kcc** [comment]
Closing this one. Please reopen if if you want to claim it for yourself. :)
