### ISSUE TITLE
Problem with LSAN?

### ISSUE THREAD

**Issue by FBergeron** [google/sanitizers#625]
Hi,

I'm experimenting ASAN and LSAN for the very first time.  I have an error on a very simple program.  I'm wondering if there is an issue with the Leak Sanitizer or if I'm doing something wrong.  I guess it's the latter but I would like to understand why.

Here is my program, the filename is ```test_simple_thread.cpp```:

```c++
#include <iostream>
#include <boost/thread.hpp>

void sayHello() {
    std::cout << "Hello!" << std::endl;
}

int main(int argc, char* argv[]) {
    boost::thread workerThread(sayHello);
    workerThread.join();
    return 0;
}
```
I compile it doing:

```sh
 % g++ -pthread -std=c++11 -DNDEBUG -O2 -Wall -DGOOGLE_STRIP_LOG=1 -lboost_thread -lboost_system -g -fsanitize=address,undefined,leak -fno-omit-frame-pointer -lasan -lubsan -llsan test_simple_thread.cpp
```

When I execute it, I get:

```sh
% ./a.out 
ASAN:SIGSEGV
=================================================================
==9481==ERROR: AddressSanitizer: SEGV on unknown address 0x61900000b908 (pc 0x7fe91755ae9f sp 0x7fffd5ce09e0 bp 0x00000000c000 T0)
    #0 0x7fe91755ae9e (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x1fe9e)
    #1 0x7fe91755b1c7 (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x201c7)
    #2 0x7fe91755b225 (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x20225)
    #3 0x7fe917557d9f (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x1cd9f)
    #4 0x7fe917558327 (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x1d327)
    #5 0x7fe91758f8c6 in calloc (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x548c6)
    #6 0x7fe918422fd1 (/lib64/ld-linux-x86-64.so.2+0x10fd1)
    #7 0x7fe9184236dd in _dl_allocate_tls (/lib64/ld-linux-x86-64.so.2+0x116dd)
    #8 0x7fe914bcfc27 in __pthread_create_2_1 (/lib/x86_64-linux-gnu/libpthread.so.0+0x8c27)
    #9 0x7fe91561194a in pthread_create (/usr/lib/x86_64-linux-gnu/liblsan.so.0+0xb94a)
    #10 0x7fe91755eb46 in pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x23b46)
    #11 0x7fe91732cea9 in boost::thread::start_thread_noexcept() (/usr/lib/x86_64-linux-gnu/libboost_thread.so.1.55.0+0xcea9)
    #12 0x40c302 in boost::thread::start_thread() /usr/include/boost/thread/detail/thread.hpp:180
    #13 0x40c302 in boost::thread::thread<void (&)()>(void (&)()) /usr/include/boost/thread/detail/thread.hpp:267
    #14 0x406a0c in main /home/fred/dev/tests/boost/threads/test_simple_thread.cpp:9
    #15 0x7fe91483fb44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b44)
    #16 0x406c91 (/home/fred/dev/tests/boost/threads/a.out+0x406c91)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ??:0 ??
==9481==ABORTING
```

If I remove the -llsan option when I compile my program, it runs fine without error messages.

Is this the expected normal behavior?

I'm working on a Debian 8 (stable) machine.  Versions of ASAN and LSAN:

```sh
 % dpkg -l | grep "[la]san"   
ii  libasan1:amd64                             4.9.2-10                             amd64        AddressSanitizer -- a fast memory error detector
ii  liblsan0:amd64                             4.9.2-10                             amd64        LeakSanitizer -- a memory leak detector (runtime)
```

Any help would be very appreciated.

**Comment by kcc** [comment]
you are not supposed to add -lasan, -lubsan, or -llsan to the link command line. 
-fsanitize=* does this for you. 
If there is any bit of documentation that says otherwise -- please let us know.
