### ISSUE TITLE
`printf("%d %m %s\n", 10, "label")` crashes asan: AddressSanitizer: SEGV on unknown address 0x00000000000a

### ISSUE THREAD

**Issue by evverx** [google/sanitizers#759]
```
$ rpm -q clang compiler-rt
clang-3.8.0-2.fc25.x86_64
compiler-rt-3.8.0-2.fc25.x86_64
```
```c
// test-printf.c
#include <stdio.h>

int main(int argc, char *argv[]) {
        printf("%d %m %s\n", 10, "label");
}
```
```
$ clang -o test-printf -fsanitize=address ./test-printf.c
$ ./test-printf
ASAN:DEADLYSIGNAL
=================================================================
==26575==ERROR: AddressSanitizer: SEGV on unknown address 0x00000000000a (pc 0x0000004ccbc2 bp 0x7ffda4cc17f0 sp 0x7ffda4cc0f28 T0)
    #0 0x4ccbc1  (/home/vagrant/asan-crash/test-printf+0x4ccbc1)
    #1 0x48521f  (/home/vagrant/asan-crash/test-printf+0x48521f)
    #2 0x4857ca  (/home/vagrant/asan-crash/test-printf+0x4857ca)
    #3 0x485887  (/home/vagrant/asan-crash/test-printf+0x485887)
    #4 0x4e7a93  (/home/vagrant/asan-crash/test-printf+0x4e7a93)
    #5 0x7f749d010400  (/lib64/libc.so.6+0x20400)
    #6 0x418509  (/home/vagrant/asan-crash/test-printf+0x418509)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/home/vagrant/asan-crash/test-printf+0x4ccbc1)
==26575==ABORTING
```
```
(gdb) thread apply all bt

Thread 1 (Thread 0x7ffff7fe4780 (LWP 26579)):
#0  0x00000000004ccbc2 in __sanitizer::internal_strlen(char const*) ()
#1  0x0000000000485220 in printf_common(void*, char const*, __va_list_tag*) ()
#2  0x00000000004857cb in vprintf ()
#3  0x0000000000485888 in printf ()
#4  0x00000000004e7a94 in main ()
```

**Comment by eugenis** [comment]
Thanks for the report!
Fixed in https://reviews.llvm.org/rL290632
