### ISSUE TITLE
MSan false-positive scanf("%ms", &str)

### ISSUE THREAD

**Issue by aryabinin** [google/sanitizers#767]
```
$ cat sscanf.c 
#include <stdio.h>

int main(void)
{
        char *str;
        sscanf("string", "%ms", &str);
        printf("str = %s\n", str);
        return str[0];
}

$ clang -fsanitize=memory -fsanitize-memory-track-origins -g sscanf.c && ./a.out
str = string
==12541==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x48db2f in main /tmp/sscanf.c:8:2
    #1 0x7f159b78c71f in __libc_start_main (/lib64/libc.so.6+0x2071f)
    #2 0x419e58 in _start (/tmp/a.out+0x419e58)

  Uninitialized value was created by a heap allocation
    #0 0x444a00 in __interceptor_malloc (/tmp/a.out+0x444a00)
    #1 0x7f159b7c2ab7 in _IO_vfscanf (/lib64/libc.so.6+0x56ab7)
    #2 0x7f159b7d06cb in __isoc99_vsscanf (/lib64/libc.so.6+0x646cb)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /tmp/sscanf.c:8:2 in main
Exiting
```

**Comment by kcc** [comment]
ACK, thanks for the report. 
Any volunteers? (I guess this needs to be implemented in `sanitizer_common_interceptors_format.inc`)
IMHO, this is pretty low priority given that %ms is a non-standard glibc extension.

**Comment by evverx** [comment]
`OSS-Fuzz` seems to have created https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=6884 due to this false positive. Could anyone suggest what would be better to do about it?

**Comment by kcc** [comment]
Indeed, looks similar, thanks for the ping. 
Assigning this to Vitaly, but I can't promise quick turnaround.

**Comment by morehouse** [comment]
@vitalybuka:  Any progress on this?

**Comment by vitalybuka** [comment]
no
