### ISSUE TITLE
arm7 linux: SEGV on unknown address 0x00000000

### ISSUE THREAD

**Issue by arbitraryuser** [google/sanitizers#839]
Hi, I am trying to apply AddressSanitizer to an arm7 linux program.  When I built a toy (hello) to test things out, things seemed to work fine.  When I try to run an actual program of interest (app) it fails as shown below.

I would be grateful for any suggestions as to how to debug the problem applying AddressSanitizer to app, the program of interest.

Thanks a lot,

```
# ./hello
=================================================================
==1479==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x75403b80 at pc 0x8e08 bp 0x7eb91a3c sp 0x7eb91a34
WRITE of size 1 at 0x75403b80 thread T0
    #0 0x8e07 in Foo::Foo(int) /home/trusty/tmp/mfoo/helloworld.cpp:37
    #1 0x8fbb in main /home/trusty/tmp/mfoo/helloworld.cpp:57
    #2 0x767845bf in __libc_start_main (/lib/libc.so.6+0x165bf)

0x75403b80 is located 0 bytes to the right of 1024-byte region [0x75403780,0x75403b80)
allocated by thread T0 here:
    #0 0x76a67dff in operator new(unsigned int) /home/tcagent/buildAgent/work/bb9d6e9fc7c3327e/build_armv7l-timesys-linux-gnueabihf/gcc-4.9.3/gcc-4.9.3/libsanitizer/asan/asan_new_delete.cc:50
    #1 0x8d27 in Foo::Foo(int) /home/trusty/tmp/mfoo/helloworld.cpp:35
    #2 0x8fbb in main /home/trusty/tmp/mfoo/helloworld.cpp:57
    #3 0x767845bf in __libc_start_main (/lib/libc.so.6+0x165bf)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/trusty/tmp/mfoo/helloworld.cpp:37 Foo::Foo(int)
Shadow bytes around the buggy address:
  0x2ea80720: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x2ea80730: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x2ea80740: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x2ea80750: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x2ea80760: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x2ea80770:[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x2ea80780: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x2ea80790: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x2ea807a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x2ea807b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x2ea807c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Contiguous container OOB:fc
  ASan internal:           fe
==1479==ABORTING
```
A program of interest:

```# ./app
==1627==Parsed ASAN_OPTIONS: verbosity=1
==1627==AddressSanitizer: failed to intercept 'strcmp'
==1627==AddressSanitizer: failed to intercept 'strncmp'
==1627==AddressSanitizer: failed to intercept 'read'
==1627==AddressSanitizer: failed to intercept 'write'
==1627==AddressSanitizer: failed to intercept 'localtime_r'
==1627==AddressSanitizer: failed to intercept 'gmtime_r'
==1627==AddressSanitizer: failed to intercept 'sscanf'
==1627==AddressSanitizer: failed to intercept 'fscanf'
==1627==AddressSanitizer: failed to intercept 'clock_gettime'
==1627==AddressSanitizer: failed to intercept 'time'
==1627==AddressSanitizer: failed to intercept 'waitpid'
==1627==AddressSanitizer: failed to intercept 'inet_ntop'
==1627==AddressSanitizer: failed to intercept 'inet_pton'
==1627==AddressSanitizer: failed to intercept 'getaddrinfo'
==1627==AddressSanitizer: failed to intercept 'gethostbyname_r'
==1627==AddressSanitizer: failed to intercept 'getsockopt'
==1627==AddressSanitizer: failed to intercept 'accept'
==1627==AddressSanitizer: failed to intercept 'ioctl'
==1627==AddressSanitizer: failed to intercept 'readdir'
==1627==AddressSanitizer: failed to intercept 'strerror'
==1627==AddressSanitizer: failed to intercept 'strerror_r'
==1627==AddressSanitizer: failed to intercept '_exit'
==1627==AddressSanitizer: failed to intercept 'pthread_mutex_lock'
==1627==AddressSanitizer: failed to intercept 'pthread_mutex_unlock'
==1627==AddressSanitizer: failed to intercept 'sincos'
==1627==AddressSanitizer: failed to intercept 'memcmp'
==1627==AddressSanitizer: failed to intercept 'memmove'
==1627==AddressSanitizer: failed to intercept 'memset'
==1627==AddressSanitizer: failed to intercept 'memcpy'
==1627==AddressSanitizer: failed to intercept 'strcat'
==1627==AddressSanitizer: failed to intercept 'strchr'
==1627==AddressSanitizer: failed to intercept 'strcpy'
==1627==AddressSanitizer: failed to intercept 'strlen'
==1627==AddressSanitizer: failed to intercept 'strncat'
==1627==AddressSanitizer: failed to intercept 'strncpy'
==1627==AddressSanitizer: failed to intercept 'strtol'
==1627==AddressSanitizer: failed to intercept 'strtoll'
==1627==AddressSanitizer: libc interceptors initialized
|| `[0x40000000, 0xffffffff]` || HighMem    ||
|| `[0x28000000, 0x3fffffff]` || HighShadow ||
|| `[0x24000000, 0x27ffffff]` || ShadowGap  ||
|| `[0x20000000, 0x23ffffff]` || LowShadow  ||
|| `[0x00000000, 0x1fffffff]` || LowMem     ||
MemToShadow(shadow): 0x24000000 0x247fffff 0x25000000 0x27ffffff
red_zone=16
quarantine_size=64M
malloc_context_size=30
SHADOW_SCALE: 3
SHADOW_GRANULARITY: 8
SHADOW_OFFSET: 20000000
==1627==Installed the sigaction for signal 11
==1627==T0: stack [0x7e076000,0x7e876000) size 0x800000; local=0x7e875c5c
==1627==AddressSanitizer Init done
ASAN:SIGSEGV
=================================================================
==1627==ERROR: AddressSanitizer: SEGV on unknown address 0x00000000 (pc 0x00000000 sp 0x7e875c58 bp 0x7e875c7c T0)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ??:0 ??
==1627==ABORTING
```

The app of interest uses a bunch of shared libraries.  Maybe some of these are of interest.

```
Dynamic section at offset 0x1732650 contains 56 entries:
  Tag        Type                         Name/Value
 0x00000001 (NEEDED)                     Shared library: [libasan.so.1]
 0x00000001 (NEEDED)                     Shared library: [libftdi.so.1]
 0x00000001 (NEEDED)                     Shared library: [libpcap.so.0.8]
 0x00000001 (NEEDED)                     Shared library: [libusb-1.0.so.0]
 0x00000001 (NEEDED)                     Shared library: [libdbus-1.so.3]
 0x00000001 (NEEDED)                     Shared library: [libjpeg.so.9]
 0x00000001 (NEEDED)                     Shared library: [libQt5Quick.so.5]
 0x00000001 (NEEDED)                     Shared library: [libQt5PrintSupport.so.5]
 0x00000001 (NEEDED)                     Shared library: [libQt5Svg.so.5]
 0x00000001 (NEEDED)                     Shared library: [libQt5Qml.so.5]
 0x00000001 (NEEDED)                     Shared library: [libQt5Widgets.so.5]
 0x00000001 (NEEDED)                     Shared library: [libQt5SerialPort.so.5]
 0x00000001 (NEEDED)                     Shared library: [libQt5Positioning.so.5]
 0x00000001 (NEEDED)                     Shared library: [libQt5Network.so.5]
 0x00000001 (NEEDED)                     Shared library: [libQt5Xml.so.5]
 0x00000001 (NEEDED)                     Shared library: [libQt5Concurrent.so.5]
 0x00000001 (NEEDED)                     Shared library: [libQt5Bluetooth.so.5]
 0x00000001 (NEEDED)                     Shared library: [libQt5DBus.so.5]
 0x00000001 (NEEDED)                     Shared library: [libQt5Sql.so.5]
 0x00000001 (NEEDED)                     Shared library: [libQt5Gui.so.5]
 0x00000001 (NEEDED)                     Shared library: [libQt5Core.so.5]
 0x00000001 (NEEDED)                     Shared library: [libGLESv2.so.2]
 0x00000001 (NEEDED)                     Shared library: [libEGL.so.1]
 0x00000001 (NEEDED)                     Shared library: [libGAL.so]
 0x00000001 (NEEDED)                     Shared library: [libpthread.so.0]
 0x00000001 (NEEDED)                     Shared library: [libstdc++.so.6]
 0x00000001 (NEEDED)                     Shared library: [libm.so.6]
 0x00000001 (NEEDED)                     Shared library: [libgcc_s.so.1]
 0x00000001 (NEEDED)                     Shared library: [libc.so.6]
 0x00000001 (NEEDED)                     Shared library: [ld-linux-armhf.so.3]
```

**Comment by chefmax** [comment]
Please provide more details about your system: what compiler do you use (I guess GCC 4.8 or 4.9 ?), what  Linux system do you use (Linaro Ubuntu?).
Also, please provide more details about how did you build your program under test: compile/link flags might help to diagnose the problem.

**Comment by yugr** [comment]
GDB backtrace might be helpful too.

**Comment by arbitraryuser** [comment]
I have a 4.9.3 gcc:

```
armv7l-timesys-linux-gnueabihf-gcc (Timesys 20150810) 4.9.3
```

A weird freescale lineage 3.14 linux kernel with busybox:
```
# uname -a
Linux mx6q_camaro_00759 3.14.28-ts-armv7l #1 SMP PREEMPT Mon Jun 26 14:08:58 EDT 2017 armv7l GNU/Linux
```
Compiling like:
```
armv7l-timesys-linux-gnueabihf-g++ \
-c \
-pipe \
-std=c++0x \
-fsanitize=address \
-fno-omit-frame-pointer \
-Werror \
-Wno-reorder \
-Werror=return-type \
-Wno-unused-parameter \
-Wno-unused-variable \
-Wno-unused-but-set-variable \
-Wno-deprecated \
-ggdb3 \
-O2 \
-DLINUX=1 \
-Os \
-g \
-pipe \
-Wall \
-W \
-D_REENTRANT \
-fPIE \
-DRELEASE \
-DQXT_STATIC \
-DQT_SVG_LIB \
-DUSE_QWT \
-DQT_DLL \
-DTF_LOG_GROUP=Lightship \
-DTARGET \
-DLINUX \
-DUSE_SERIAL \
-DQSERIALPORT_STATIC \
-DCLI_CMDS \
-DUSE_FTDI \
-DQT_QML_DEBUG \
-DQT_NO_DEBUG \
-DQT_QUICK_LIB \
-DQT_PRINTSUPPORT_LIB \
-DQT_SVG_LIB \
-DQT_QML_LIB \
-DQT_WIDGETS_LIB \
-DQT_SERIALPORT_LIB \
-DQT_POSITIONING_LIB \
-DQT_NETWORK_LIB \
-DQT_XML_LIB \
-DQT_CONCURRENT_LIB \
-DQT_BLUETOOTH_LIB \
-DQT_SQL_LIB \
-DQT_GUI_LIB \
-DQT_CORE_LIB
```

Linking like:

```
armv7l-timesys-linux-gnueabihf-g++ \
-fsanitize=address \
-Wl,--build-id \
-Wl,-O1 \
-Wl,-rpath,/usr/lib \
-o ../../release/foo qtquick2applicationviewer.o bar.o qrc_Resources.o qrc_resources.o qrc_XRFCutoffs.o qrc_XRFCalfactors.o qrc_fonts.o moc_qtquick2applicationviewer.o   \
-L. \
-L/home/trusty/build/xl5-1.3.1-base/Camaro_5_3_2-release/release \
-lElementalAppLib \
-lLightshipScienceEngineImplementorLib \
-lXrfHardware \
-lExtCommLayer \
-lXRFLib \
-lAlloyLibrary \
-lUIManagers \
-lXrfReadingsLib \
-lMathExpressionParser \
-lDataEntry \
-lXRFScanEngine \
-lSystemUpdate \
-lCliCmds \
-lNetLib \
-lRPCLib \
-lLsdLib \
-lSysLib \
-lAsBuilt10 \
-lAsConfigured10 \
-lxl5Diagnostic10 \
-lInterfaces \
-lDataStructures \
-lCommon \
-lLoggingLib \
-lNodesLib \
-lMirrorLib \
-lprotobuffer \
-lgSoapRuntime \
-lftdi \
-lQtSerialPort \
-L/usr/lib \
-lqwt \
-lQxtNetwork \
-lQxtCore \
-lwifi \
-lpcap \
-lusb-1.0 \
-ldbus-1 \
-ljpeg \
-lQt5Quick \
-lQt5PrintSupport \
-lQt5Svg \
-lQt5Qml \
-lQt5Widgets \
-lQt5SerialPort \
-lQt5Positioning \
-lQt5Network \
-lQt5Xml \
-lQt5Concurrent \
-lQt5Bluetooth \
-lQt5DBus \
-lQt5Sql \
-lQt5Gui \
-lQt5Core \
-lGLESv2 \
-lEGL \
-lGAL \
-lpthread 
```

If I try to debug this, I don't get a lot.  If I omit
-fsanitize=address things work and are debugable (b main, have
symbols).  This is before main.

```
Program received signal SIGSEGV, Segmentation fault.
0x00000000 in ?? ()
(gdb) where
#0  0x00000000 in ?? ()
#1  0x76b1eda0 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) info reg
r0             0x73601bc8	1935678408
r1             0x7efffcc8	2130705608
r2             0x0	0
r3             0x0	0
r4             0x30	48
r5             0x73601bc8	1935678408
r6             0x7efffcc8	2130705608
r7             0x0	0
r8             0x7efffd4c	2130705740
r9             0x76fff908	1996486920
r10            0x1	1
r11            0x7efffcbc	2130705596
r12            0x2e6c037c	778830716
sp             0x7efffc98	0x7efffc98
lr             0x76b1eda0	1991372192
pc             0x0	0x0
cpsr           0x60000010	1610612752
(gdb) info symbol 0x76b1eda0
No symbol matches 0x76b1eda0.
(gdb) 
```

Thanks a lot for any comments you may have.

**Comment by arbitraryuser** [comment]
With sysroot in better order:

```
(gdb) where
#0  0x00000000 in ?? ()
#1  0x76b1eda0 in __interceptor_pthread_cond_init (c=0x73601bc8, a=0x7efffcd8) at /home/tcagent/buildAgent/work/bb9d6e9fc7c3327e/build_armv7l-timesys-linux-gnueabihf/gcc-4.9.3/gcc-4.9.3/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:2261
#2  0x757035b8 in QWaitCondition::QWaitCondition() () from /home/trusty/devices/xl5-759/usr/lib/libQt5Core.so.5
#3  0x75c06344 in ?? () from /home/trusty/devices/xl5-759/usr/lib/libQt5Gui.so.5
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

**Comment by chefmax** [comment]
Seems like a dup of #297 ?

**Comment by morehouse** [comment]
Solution is probably to use a newer GCC or Clang.  Please re-open if the issue persists.
