### ISSUE TITLE
memory sanitizer doesn't complain about bitwise or.

### ISSUE THREAD

**Issue by kuszmaul** [google/sanitizers#867]
msan doesn't complain when an undefined value is fed through `|`, but it correctly complains about `+`.

For example, this program doesn't give an msan error:
```c
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
int main(int argc, char *argv[] __attribute__((unused))) {
    uint64_t *a = malloc(sizeof(*a));
    if (*a | (uint64_t)argc) {
        printf("foo\n");
    }
    return 0;
}
```
which incorrectly yields the following output:
```bash
$ make sanitize-bitwise-or CC=~/clang5/bin/clang CFLAGS="-fsanitize=memory -O0" && ./sanitize-bitwise-or 
/home/bradley/clang5/bin/clang -fsanitize=memory -O0    sanitize-bitwise-or.c   -o sanitize-bitwise-or
foo
```

Changing the `|` to a `+` as
```c
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
int main(int argc, char *argv[] __attribute__((unused))) {
    uint64_t *a = malloc(sizeof(*a));
    if (*a + (uint64_t)argc) {
        printf("foo\n");
    }
    return 0;
}
```
correctly produces an error:
```bash
$make sanitize-bitwise-or CC=~/clang5/bin/clang CFLAGS="-fsanitize=memory -O0" && ./sanitize-bitwise-or 
/home/bradley/clang5/bin/clang -fsanitize=memory -O0    sanitize-bitwise-or.c   -o sanitize-bitwise-or
==23207==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x488e9a in main (/home/bradley/ctest/sanitize-bitwise-or+0x488e9a)
    #1 0x7f109ad6d82f in __libc_start_main /build/glibc-bfm8X4/glibc-2.23/csu/../csu/libc-start.c:291
    #2 0x41a0c8 in _start (/home/bradley/ctest/sanitize-bitwise-or+0x41a0c8)

SUMMARY: MemorySanitizer: use-of-uninitialized-value (/home/bradley/ctest/sanitize-bitwise-or+0x488e9a) in main
Exiting
```

I first noticed this on clang 3.8.0-2ubuntu4, but also see it on a freshly downloaded
```
$ ~/clang5/bin/clang --version
~/clang5/bin/clang --version
clang version 5.0.0 (tags/RELEASE_500/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/bradley/clang5/bin
```
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&ved=0ahUKEwieqtyNvObWAhWhw1QKHVj6CXMQFggvMAE&url=https%3A%2F%2Fclang.llvm.org%2Fdocs%2FMemorySanitizer.html&usg=AOvVaw01LY6IlCiAgbsCi1bxfmFP

**Comment by eugenis** [comment]
It does not complain because with argc == 1 the result of bitwise or will
have the lowest bit set no matter what the contents of uninitialized memory
are, and the boolean conversion will always yield true.
