### ISSUE TITLE
Global buffer underflow not caught for first variable in a first TU

### ISSUE THREAD

**Issue by marxin** [google/sanitizers#869]
As one can see in following example:

```
char global = 0;
char global2 = 0;

int main()
{
  char *p = &global;
  *(p - 1) = 'a'; // not caught
  *(p + 1) = 'b'; // caught
  p = &global2;
  *(p - 1) = 'c'; // caught
}

 gcc global.c -g -fsanitize=address -fsanitize-recover=address && ASAN_OPTIONS="halt_on_error=0" ./a.out 
=================================================================
==14329==ERROR: AddressSanitizer: global-buffer-overflow on address 0x000000601121 at pc 0x000000400801 bp 0x7ffd35300630 sp 0x7ffd35300628
WRITE of size 1 at 0x000000601121 thread T0
    #0 0x400800 in main /tmp/global.c:8
    #1 0x7f720d38af49 in __libc_start_main (/lib64/libc.so.6+0x20f49)
    #2 0x4006c9 in _start (/tmp/a.out+0x4006c9)

0x000000601121 is located 0 bytes to the right of global variable 'global' defined in 'global.c:1:6' (0x601120) of size 1
  'global' is ascii string ''
0x000000601121 is located 63 bytes to the left of global variable 'global2' defined in 'global.c:2:6' (0x601160) of size 1
  'global2' is ascii string ''
SUMMARY: AddressSanitizer: global-buffer-overflow /tmp/global.c:8 in main
Shadow bytes around the buggy address:
  0x0000800b81d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0000800b81e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0000800b81f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0000800b8200: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0000800b8210: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0000800b8220: 00 00 00 00[01]f9 f9 f9 f9 f9 f9 f9 01 f9 f9 f9
  0x0000800b8230: f9 f9 f9 f9 00 00 00 00 00 00 00 00 00 00 00 00
  0x0000800b8240: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0000800b8250: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0000800b8260: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0000800b8270: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
=================================================================
==14329==ERROR: AddressSanitizer: global-buffer-overflow on address 0x00000060115f at pc 0x000000400847 bp 0x7ffd35300630 sp 0x7ffd35300628
WRITE of size 1 at 0x00000060115f thread T0
    #0 0x400846 in main /tmp/global.c:10
    #1 0x7f720d38af49 in __libc_start_main (/lib64/libc.so.6+0x20f49)
    #2 0x4006c9 in _start (/tmp/a.out+0x4006c9)

0x00000060115f is located 62 bytes to the right of global variable 'global' defined in 'global.c:1:6' (0x601120) of size 1
  'global' is ascii string ''
0x00000060115f is located 1 bytes to the left of global variable 'global2' defined in 'global.c:2:6' (0x601160) of size 1
  'global2' is ascii string ''
SUMMARY: AddressSanitizer: global-buffer-overflow /tmp/global.c:10 in main
Shadow bytes around the buggy address:
  0x0000800b81d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0000800b81e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0000800b81f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0000800b8200: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0000800b8210: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0000800b8220: 00 00 00 00 01 f9 f9 f9 f9 f9 f9[f9]01 f9 f9 f9
  0x0000800b8230: f9 f9 f9 f9 00 00 00 00 00 00 00 00 00 00 00 00
  0x0000800b8240: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0000800b8250: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0000800b8260: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0000800b8270: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
```

We do not catch underflow for a first variable (in a first TU). There's GCC bug entry:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=82501

We suggest either to create a dummy global variable with size == 0 for each TU. Or we could be done is that for -fsanitize=address you link in first some dummy object with zero sized variables with padding registered in each of the sections commonly used for variables (at least .data, .rodata, dunno about the various .data.rel.ro etc.).

Thought?

**Comment by morehouse** [comment]
@eugenis, @kcc:  Opinions on this?

**Comment by kcc** [comment]
still there, no plan to fix, but volunteers welcome.
