### ISSUE TITLE
malloc() failing in LargeMmapAllocator should return NULL when mmap fails

### ISSUE THREAD

**Issue by mrichtarsky** [google/sanitizers#889]
For this code:

```
#include <cstdlib>

int main()
{
  void *p = malloc(0x4000003000);
  return 0;
}
```

I get this report:

```
==92092==ERROR: AddressSanitizer failed to allocate 0x4000005000 (274877927424) bytes of LargeMmapAllocator (error code: 12)
==92092==Process memory map follows:
...
==92092==AddressSanitizer CHECK failed: /llvm-4.0.0.src/projects/compiler-rt/lib/sanitizer_common/sanitizer_common.cc:120 "((0 && "unable to mmap")) != (0)" (0x0, 0x0)
    #0 0x2b1d32bb975f in __asan::AsanCheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /llvm-4.0.0.src/projects/compiler-rt/lib/asan/asan_rtl.cc:69
    #1 0x2b1d32ae6a55 in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /llvm-4.0.0.src/projects/compiler-rt/lib/sanitizer_common/sanitizer_termination.cc:79
    #2 0x2b1d32ad5f02 in __sanitizer::ReportMmapFailureAndDie(unsigned long, char const*, char const*, int, bool) /llvm-4.0.0.src/projects/compiler-rt/lib/sanitizer_common/sanitizer_common.cc:120
    #3 0x2b1d32adf945 in __sanitizer::MmapOrDie(unsigned long, char const*, bool) /llvm-4.0.0.src/projects/compiler-rt/lib/sanitizer_common/sanitizer_posix.cc:132
    #4 0x2b1d32b01962 in __sanitizer::LargeMmapAllocator<__asan::AsanMapUnmapCallback>::Allocate(__sanitizer::AllocatorStats*, unsigned long, unsigned long) /llvm-4.0.0.src/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_allocator_secondary.h:41
    #5 0x2b1d32b01962 in __sanitizer::CombinedAllocator<__sanitizer::SizeClassAllocator64<__asan::AP64>, __sanitizer::SizeClassAllocatorLocalCache<__sanitizer::SizeClassAllocator64<__asan::AP64> >, __sanitizer::LargeMmapAllocator<__asan::AsanMapUnmapCallback> >::Allocate(__sanitizer::SizeClassAllocatorLocalCache<__sanitizer::SizeClassAllocator64<__asan::AP64> >*, unsigned long, unsigned long, bool, bool) /llvm-4.0.0.src/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_allocator_combined.h:70
    #6 0x2b1d32b01962 in __asan::Allocator::Allocate(unsigned long, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType, bool) /llvm-4.0.0.src/projects/compiler-rt/lib/asan/asan_allocator.cc:407
    #7 0x2b1d32b01962 in __asan::asan_malloc(unsigned long, __sanitizer::BufferedStackTrace*) /llvm-4.0.0.src/projects/compiler-rt/lib/asan/asan_allocator.cc:782
    #8 0x2b1d32baf754 in __interceptor_malloc /llvm-4.0.0.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:67
    #9 0x4006fd in main (a.out+0x4006fd)
    #10 0x2b1d343a1b04 in __libc_start_main (/lib64/libc.so.6+0x21b04)
    #11 0x400618 in _start /home/abuild/rpmbuild/BUILD/glibc-2.19/csu/../sysdeps/x86_64/start.S:122
```

This seems to be different for other allocators, which are able to return NULL when allocator_may_return_null=1 is set.

mmap() failure should be caught and malloc() should return NULL.

Best regards,
Martin

**Comment by kcc** [comment]
what revision?

**Comment by kcc** [comment]
If it's 4.0.0 (very old!) try the new one from trunk.

**Comment by mrichtarsky** [comment]
Version was 4.0.0. I tested with 5.0.0 and there I get the desired behavior.
