### ISSUE TITLE
msan: need an interceptor for strtouq

### ISSUE THREAD

**Issue by oliverchang** [google/sanitizers#892]
Using clang from latest chromium clang roll (clang version 6.0.0 (trunk 318667)) and compiling:

```c
#include <stdio.h>
#include <stdlib.h>

int main() {
  char blah[] = "1234";

  char* end;
  strtouq(blah, &end, 10);

  if (end == blah + 4) {
    printf("ok\n");
  }

  return 0;
}

```

Gives:

```
==2630==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x48c4a3 in main /usr/local/google/home/ochang/test.c:10:7
    #1 0x7f8e8ce79f44 in __libc_start_main /build/eglibc-SvCtMH/eglibc-2.19/csu/libc-start.c:287
    #2 0x41a3fe in _start (/usr/local/google/home/ochang/a.out+0x41a3fe)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /usr/local/google/home/ochang/test.c:10:7 in main
ok
MemorySanitizer: 1 warnings reported.

```
 
libpcre3 on xenial (at least) uses this.

**Comment by oliverchang** [comment]
Thanks for the quick fix @vitalybuka !
