### ISSUE TITLE
Is it possible to suppress errors further up the stack?

### ISSUE THREAD

**Issue by Ono-Sendai** [google/sanitizers#894]
Take this example output from ASAN:
```
==22919==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200067d2bc at pc 0x000113995ea8 bp 0x7ffee0ea3df0 sp 0x7ffee0ea35a0
READ of size 16 at 0x60200067d2bc thread T0
    #0 0x113995ea7 in __asan_memcpy (libclang_rt.asan_osx_dynamic.dylib:x86_64+0x4dea7)
    #1 0x10f421d7d in std::__1::vector<unsigned int, std::__1::allocator<unsigned int> >::__swap_out_circular_buffer(std::__1::__split_buffer<unsigned int, std::__1::allocator<unsigned int>&>&) memory:1676
    #2 0x10f828be2 in void std::__1::vector<unsigned int, std::__1::allocator<unsigned int> >::__push_back_slow_path<unsigned int const&>(unsigned int const&&&) vector:1574
    #3 0x110bccfba in (anonymous namespace)::VirtRegRewriter::runOnMachineFunction(llvm::MachineFunction&) (indigo_gui:x86_64+0x101e91fba)
    #4 0x110b1f922 in llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (indigo_gui:x86_64+0x101de4922)
    #5 0x110ea557e in llvm::FPPassManager::runOnFunction(llvm::Function&) (indigo_gui:x86_64+0x10216a57e)
```

I don't want to suppress errors in __asan_memcpy because that may suppress other errors that I can fix.
Is it possible to suppress, for example, runOnMachineFunction and all functions called by it?

Thanks!

**Comment by kcc** [comment]
We usually strongly discourage the use of suppressions -- they are almost never the right solution. 
And anyway I don't think we have a way to suppress the error in your case.
