### ISSUE TITLE
Add -fno-builtin to wiki help for replace_str?

### ISSUE THREAD

**Issue by sitsofe** [google/sanitizers#898]
Over on https://github.com/google/sanitizers/wiki/AddressSanitizerFlags there is an entry for replace_str that says

> If set, uses custom wrappers and replacements for libc string functions to find more errors.

It may be helpful to also suggest the user rebuild their program with `-fno-builtin` as this seems to help at least clang identify stack-buffer-overflow problems when using -fsanitize=address whereas without it it would just allow the stack stomp through and crash elsewhere.

**Comment by yugr** [comment]
AFAIK without `-fno-builtin` Clang would just expand calls to standard APIs inline and then Asan should be able to detect bug in instrumented memory accesses. In case it fails, can you provide a repro?

@chefmax maybe mention `replace_str` in FAQ entry about aggressive options?

**Comment by sitsofe** [comment]
@yugr it's a bit messy but if you compile [fio](https://github.com/axboe/fio/) 3.3 with clang 3.9 via
```
./configure --extra-cflags="-fsanitize=address" --disable-optimizations
make
```

and then run it with
```
    rw[0]='read'; rw[1]='write'; \
    for i in {1..1000}; do \
     echo -e "[job$i]\nrw=${rw[$((i % 2))]}\n" \
             "ramp_time=$(((1000 - i) / 350 * 5))\n" \
             "runtime=$((60 - (i % 3) * 2))"; \
    done | \
    ./fio --eta-newline=1s --group_reporting --ioengine=null --size=1g \
     --time_based --bs=512 --thread --rate_iops=123456 -
```

it explodes with this:
```
=================================================================
==28912==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x0000004286f5 bp 0x2020202020202020 sp 0x7f2ecdf41e60 T1)
==28912==The signal is caused by a READ memory access.
==28912==Hint: address points to the zero page.
    #0 0x4286f4 in atomic_compare_exchange_strong<__sanitizer::atomic_uint8_t> /home/user/clang-3.9/llvm/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_atomic_clang.h:81
    #1 0x4286f4 in __asan::Allocator::AtomicallySetQuarantineFlagIfAllocated(__asan::AsanChunk*, void*, __sanitizer::BufferedStackTrace*) /home/user/clang-3.9/llvm/projects/compiler-rt/lib/asan/asan_allocator.cc:468
    #2 0x4286f4 in __asan::Allocator::Deallocate(void*, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType) /home/user/clang-3.9/llvm/projects/compiler-rt/lib/asan/asan_allocator.cc:522
    #3 0x4286f4 in __asan::asan_free(void*, __sanitizer::BufferedStackTrace*, __asan::AllocType) /home/user/clang-3.9/llvm/projects/compiler-rt/lib/asan/asan_allocator.cc:725
    #4 0x4df9ec in __interceptor_free /home/user/clang-3.9/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:50
    #5 0x57f64a in display_thread_status /home/user/fio/eta.c:611:4
    #6 0x5808c1 in print_thread_status /home/user/fio/eta.c:658:3
    #7 0x6153d6 in helper_thread_main /home/user/fio/helper_thread.c:145:4
    #8 0x7f2ee95416b9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9)
    #9 0x7f2ee8c543dc in clone /build/glibc-bfm8X4/glibc-2.23/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:109

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/user/clang-3.9/llvm/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_atomic_clang.h:81 in atomic_compare_exchange_strong<__sanitizer::atomic_uint8_t>
Thread T1 created by T0 here:
    #0 0x437b51 in __interceptor_pthread_create /home/user/clang-3.9/llvm/projects/compiler-rt/lib/asan/asan_interceptors.cc:245
    #1 0x614e18 in helper_thread_create /home/user/fio/helper_thread.c:172:8

==28912==ABORTING
```

Fair enough a pointer that normally took you to malloced memory got stomped on. However, if you compile it with
```
./configure --extra-cflags="-fsanitize=address  -fno-builtin" --disable-optimizations
make
```

and run it as before you quickly get this:

```
=================================================================
==31968==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7f7060643140 at pc 0x0000004a9ba1 bp 0x7f7060641e20 sp 0x7f70606415d0
WRITE of size 2 at 0x7f7060643140 thread T1
    #0 0x4a9ba0 in vsprintf /home/user/clang-3.9/llvm/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:1338
    #1 0x4a9ea2 in __interceptor_sprintf /home/user/clang-3.9/llvm/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:1369
    #2 0x5ce9e6 in display_thread_status /home/user/fio/eta.c:614:7
    #3 0x5cef4a in print_thread_status /home/user/fio/eta.c:658:3
    #4 0x6e7c18 in helper_thread_main /home/user/fio/helper_thread.c:145:4
    #5 0x7f707bc366b9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9)
    #6 0x7f707b3493dc in clone /build/glibc-bfm8X4/glibc-2.23/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Address 0x7f7060643140 is located in stack of thread T1 at offset 4640 in frame
    #0 0x5cb5ff in display_thread_status /home/user/fio/eta.c:518

  This frame has 5 object(s):
    [32, 4640) 'output' <== Memory access at offset 4640 overflows this variable
    [4896, 5024) 'eta_str'
    [5056, 5088) 'perc_str'
    [5120, 5144) 'iops_str'
    [5184, 5208) 'rate_str'
HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
      (longjmp and C++ exceptions *are* supported)
Thread T1 created by T0 here:
    #0 0x437cb1 in __interceptor_pthread_create /home/user/clang-3.9/llvm/projects/compiler-rt/lib/asan/asan_interceptors.cc:245
    #1 0x6e6d2a in helper_thread_create /home/user/fio/helper_thread.c:172:8
    #2 0x691da1 in fio_backend /home/user/fio/backend.c:2488:2
    #3 0x73dbf4 in main /home/user/fio/fio.c:65:9

SUMMARY: AddressSanitizer: stack-buffer-overflow /home/user/clang-3.9/llvm/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:1338 in vsprintf
Shadow bytes around the buggy address:
  0x0fee8c0c05d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fee8c0c05e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fee8c0c05f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fee8c0c0600: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fee8c0c0610: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0fee8c0c0620: 00 00 00 00 00 00 00 00[f2]f2 f2 f2 f2 f2 f2 f2
  0x0fee8c0c0630: f2 f2 f2 f2 f2 f2 f2 f2 f2 f2 f2 f2 f2 f2 f2 f2
  0x0fee8c0c0640: f2 f2 f2 f2 f2 f2 f2 f2 00 00 00 00 00 00 00 00
  0x0fee8c0c0650: 00 00 00 00 00 00 00 00 f2 f2 f2 f2 00 00 00 00
  0x0fee8c0c0660: f2 f2 f2 f2 00 00 00 f2 f2 f2 f2 f2 00 00 00 f3
  0x0fee8c0c0670: f3 f3 f3 f3 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==31968==ABORTING
```

Which is extra useful!

**Comment by yugr** [comment]
I still think the real problem is that we don't detect overflow in first (`-fbuiltin`) case. It's hard to see what's wrong without minirepro though...
