### ISSUE TITLE
Possible false positive using OpenCL clEnqueueFillBuffer on MacBook Iris Pro

### ISSUE THREAD

**Issue by sschaetz** [google/sanitizers#902]
We are looking at a possible false positive when using the OpenCL call clEnqueueFillBuffer on MacBook with Intel Iris Pro GPU when compiling with `-fsanitize=address`.

Reproducer attached (remove .txt extensions). 

My MacBook has 2 GPUs, one Intel Iris and one GeForce GT 750M.
In the reproducer if `ENABLE_FAILURE 1` is defined the Intel Iris GPU is selected on my system.

It fails with

```
./main
Iris Pro
=================================================================
==26254==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000009571 at pc 0x00010e23e62a bp 0x70000c5e9250 sp 0x70000c5e89f0
READ of size 16 at 0x602000009571 thread T3
    #0 0x10e23e629 in wrap_memcpy (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x1b629)
    #1 0x110d50555 in CHAL_INTEL::ChalContext::ChalExecuteFillBuffer(GLDBufferImageRegionRec*, GLDBufferRec*, GLDBufferImageRegionRec*, GLDBufferRec*, GLDFenceRec*) (AppleIntelHD5000GraphicsGLDriver:x86_64+0x4f2555)
    #2 0x110d47563 in gldCopyBufferDataWithQueue (AppleIntelHD5000GraphicsGLDriver:x86_64+0x4e9563)
    #3 0x7fffc60bf26e  (OpenCL:x86_64+0x226e)
    #4 0x7fffc60dce9a  (OpenCL:x86_64+0x1fe9a)
    #5 0x7fffc60e02c4  (OpenCL:x86_64+0x232c4)
    #6 0x10e27a10b in asan_dispatch_call_block_and_release (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x5710b)
    #7 0x7fffd74458fb in _dispatch_client_callout (libdispatch.dylib:x86_64+0x18fb)
    #8 0x7fffd745b99f in _dispatch_queue_serial_drain (libdispatch.dylib:x86_64+0x1799f)
    #9 0x7fffd744e305 in _dispatch_queue_invoke (libdispatch.dylib:x86_64+0xa305)
    #10 0x7fffd745401f in _dispatch_queue_override_invoke (libdispatch.dylib:x86_64+0x1001f)
    #11 0x7fffd74476b4 in _dispatch_root_queue_drain (libdispatch.dylib:x86_64+0x36b4)
    #12 0x7fffd744748b in _dispatch_worker_thread3 (libdispatch.dylib:x86_64+0x348b)
    #13 0x7fffd76945a1 in _pthread_wqthread (libsystem_pthread.dylib:x86_64+0x35a1)
    #14 0x7fffd769407c in start_wqthread (libsystem_pthread.dylib:x86_64+0x307c)

0x602000009571 is located 0 bytes to the right of 1-byte region [0x602000009570,0x602000009571)
allocated by thread T0 here:
    #0 0x10e27be9c in wrap_malloc (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x58e9c)
    #1 0x7fffc60d36f0 in clEnqueueFillBuffer (OpenCL:x86_64+0x166f0)
    #2 0x10e1f492c in int cl::CommandQueue::enqueueFillBuffer<char>(cl::Buffer const&, char, unsigned long, unsigned long, std::__1::vector<cl::Event, std::__1::allocator<cl::Event> > const*, cl::Event*) const (main:x86_64+0x10000792c)
    #3 0x10e1f1925 in main (main:x86_64+0x100004925)
    #4 0x7fffd747b234 in start (libdyld.dylib:x86_64+0x5234)

Thread T3 created by T0 here:
    <empty stack>

SUMMARY: AddressSanitizer: heap-buffer-overflow (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x1b629) in wrap_memcpy
Shadow bytes around the buggy address:
  0x1c0400001250: fa fa 00 fa fa fa fd fd fa fa fd fa fa fa 00 fa
  0x1c0400001260: fa fa fd fa fa fa 01 fa fa fa fd fa fa fa fd fa
  0x1c0400001270: fa fa fd fd fa fa fd fa fa fa fd fa fa fa fd fa
  0x1c0400001280: fa fa 00 fa fa fa 04 fa fa fa 04 fa fa fa 04 fa
  0x1c0400001290: fa fa 00 00 fa fa 00 fa fa fa 04 fa fa fa 00 fa
=>0x1c04000012a0: fa fa 04 fa fa fa 00 fa fa fa 04 fa fa fa[01]fa
  0x1c04000012b0: fa fa 00 fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c04000012c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c04000012d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c04000012e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c04000012f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==26254==ABORTING
Abort trap: 6
```

If `ENABLE_FAILURE 1` is not defined the GeForce GT 750M GPU is selected on my system. Code executes fine in that case:

```
./main
GeForce GT 750M
3
```

[main.cpp.txt](https://github.com/google/sanitizers/files/1616983/main.cpp.txt)
[Makefile.txt](https://github.com/google/sanitizers/files/1616984/Makefile.txt)

**Comment by kcc** [comment]
will need someone from Apple (or Intel?) to chime in... @kubamracek

**Comment by kubamracek** [comment]
Hi, this might be an actual overflow in the OpenCL driver. Can you file this at <https://bugreport.apple.com>?

**Comment by kubamracek** [comment]
You would probably need to wait for an update with a fix, so if this is blocking you from using ASan, you should be able to use the suppression file to silence this issue, see <https://clang.llvm.org/docs/AddressSanitizer.html#suppressing-reports-in-external-libraries>.

**Comment by sschaetz** [comment]
Thanks for the quick feedback. Filed bug with Apple (36438092). We'll look into Suppressing Reports in External Libraries.

**Comment by kcc** [comment]
Thanks Kuba!
Closing here; feel free to reopen if there is something we can do with this
