### ISSUE TITLE
dynamic tls tests broken with glibc 2.5

### ISSUE THREAD

**Issue by kcc** [google/sanitizers#914]
People start complaining about glibc 2.5 breaking the sanitizers. 
https://bugs.llvm.org/show_bug.cgi?id=36065
https://bugs.llvm.org/show_bug.cgi?id=36326

I don't have cycles to work on this, volunteers welcome. 

If anyone here from glibc, https://sourceware.org/glibc/wiki/ThreadPropertiesAPI is still relevant.

**Comment by mgorny** [comment]
I think you wanted to say '2.25'.

**Comment by kcc** [comment]
Yes, thanks. Updated.

**Comment by chefmax** [comment]
Seems to be caused by this: https://sourceware.org/bugzilla/show_bug.cgi?id=17730

**Comment by chefmax** [comment]
Perhaps we just need something like `DTLS_on_libc_memalign` for malloc, but I'm not sure, this needs testing.

**Comment by kcc** [comment]
I've pinged the glibc folks here: https://sourceware.org/ml/libc-alpha/2018-02/msg00567.html

**Comment by Lekensteyn** [comment]
All 32-bit applications currently crash with glibc 2.27 as demonstrated by:
```
$ echo 'int main(){}' > empty.c
$ clang -g -fsanitize=address -m32 empty.c -o empty && ./empty
=================================================================
==27867==ERROR: AddressSanitizer: SEGV on unknown address 0xf7f70020 (pc 0xf7f70034 bp 0xffa9ac1c sp 0xffa9abdc T16777215)
==27867==The signal is caused by a WRITE memory access.
    #0 0xf7f70033 in _dl_get_tls_static_info (/lib/ld-linux.so.2+0x12033)
    #1 0x567081cb in __sanitizer::InitTlsSize() (main+0x11b1cb)
    #2 0x566e7cd2 in __asan::AsanInitInternal() [clone .part.0] (main+0xfacd2)
    #3 0xf7f6da57 in _dl_init (/lib/ld-linux.so.2+0xfa57)
    #4 0xf7f5ec99  (/lib/ld-linux.so.2+0xc99)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/lib/ld-linux.so.2+0x12033) in _dl_get_tls_static_info
==27867==ABORTING
```
For some reason the calling convention has changed from `regparm(2)` to cdecl. It has likely something to do with https://sourceware.org/git/gitweb.cgi?p=glibc.git;a=commit;h=17e00cc69eac2ec10ac69a3f85db0dffc9d73845

Environment: Arch Linux x86_64 with lib32-glibc 2.27-3. Working version is lib32-glibc 2.26-11.
