### ISSUE TITLE
`msan` doesn't seem to instrument vlas

### ISSUE THREAD

**Issue by evverx** [google/sanitizers#926]
`OSS-Fuzz` has reported https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=6897. I reduced the test case a little:
```sh
root@7312ea87ce69:/src/systemd# cat test.c
#include <string.h>

int main(int argc, char *argv[]) {
    char *p = "abc-def";
    char *dash = strchr(p, '-');
    if (dash) {
        char n[dash - p + sizeof(".slice")];
        strcpy(stpncpy(n, p, dash - p), ".slice");
        return n[0];
    }
    return 0;
}

root@7312ea87ce69:/src/systemd# clang --version
clang version 7.0.0 (trunk 325667)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin

root@7312ea87ce69:/src/systemd# clang -fsanitize=memory -fsanitize-memory-track-origins -g ./test.c
root@7312ea87ce69:/src/systemd# ./a.out
==60==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x49743f in main /src/systemd/./test.c:12:1
    #1 0x7fab33d7782f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #2 0x41a998 in _start (/src/systemd/a.out+0x41a998)

  Uninitialized value was stored to memory at
    #0 0x49734d in main /src/systemd/./test.c:9:1
    #1 0x7fab33d7782f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

  Uninitialized value was created by an allocation of 'vla' in the stack frame of function 'main'
    #0 0x4969f0 in main /src/systemd/./test.c:3

SUMMARY: MemorySanitizer: use-of-uninitialized-value /src/systemd/./test.c:12:1 in main
Exiting
```

**Comment by eugenis** [comment]
This is not about VLAs.
MSan does not intercept stpncpy.

**Comment by evverx** [comment]
That's correct. Thank you.

Could you recommend a simple way to find out what else `msan` doesn't intercept, so that I could spend a little bit less time trying to distinguish false positives from real bugs?

**Comment by eugenis** [comment]
Generally I go here (in a local checkout): http://llvm-cs.pcc.me.uk/projects/compiler-rt/lib/ and grep for the function name. If it is not found in (msan|sanitizer).*interceptors.* - it is unsupported. Note that functions that do not write to memory do not need to be intercepted.
