### ISSUE TITLE
ASAN false positive for new/delete, malloc/free mismatch

### ISSUE THREAD

**Issue by rianquinn** [google/sanitizers#930]
The following code generates a mismatch on the latest ASAN checks:
https://github.com/Bareflank/hypervisor/blob/master/bfsdk/include/bfbenchmark.h

Its certainly possible that this is not written properly, but at the moment I don't see how. The error I get while unit testing is as follows:
```
=================================================================
==41551==ERROR: AddressSanitizer: alloc-dealloc-mismatch (operator new vs free) on 0x602000000010
    #0 0x7f9d271a5711 in __interceptor_free /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:45
    #1 0x558150f3d429 in custom_delete(void*, unsigned long) (/home/user/working/hypervisor/build/bfsdk/x86_64-test-elf/build/test_benchmark+0x2a5429)
    #2 0x558150f37536 in operator delete(void*, unsigned long) /home/user/working/hypervisor/bfsdk/include/bfbenchmark.h:74
    #3 0x558151159a98 in Catch::TestInvokerAsFunction::~TestInvokerAsFunction() /home/user/working/hypervisor/build/prefixes/x86_64-test-elf/include/catch/catch.hpp:8181
    #4 0x55815115ffd4 in std::_Sp_counted_ptr<Catch::ITestInvoker*, (__gnu_cxx::_Lock_policy)2>::_M_dispose() /usr/include/c++/7.3.0/bits/shared_ptr_base.h:376
    #5 0x558151044b42 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() /usr/include/c++/7.3.0/bits/shared_ptr_base.h:154
    #6 0x558151018df1 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() /usr/include/c++/7.3.0/bits/shared_ptr_base.h:684
    #7 0x558151011125 in std::__shared_ptr<Catch::ITestInvoker, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() /usr/include/c++/7.3.0/bits/shared_ptr_base.h:1123
    #8 0x558151011165 in std::shared_ptr<Catch::ITestInvoker>::~shared_ptr() /usr/include/c++/7.3.0/bits/shared_ptr.h:93
    #9 0x5581510111ab in Catch::TestCase::~TestCase() /home/user/working/hypervisor/build/prefixes/x86_64-test-elf/include/catch/catch.hpp:2723
    #10 0x5581510ad38d in void std::_Destroy<Catch::TestCase>(Catch::TestCase*) /usr/include/c++/7.3.0/bits/stl_construct.h:98
    #11 0x558151095d7b in void std::_Destroy_aux<false>::__destroy<Catch::TestCase*>(Catch::TestCase*, Catch::TestCase*) /usr/include/c++/7.3.0/bits/stl_construct.h:108
    #12 0x558151072b4a in void std::_Destroy<Catch::TestCase*>(Catch::TestCase*, Catch::TestCase*) /usr/include/c++/7.3.0/bits/stl_construct.h:137
    #13 0x55815104cb5a in void std::_Destroy<Catch::TestCase*, Catch::TestCase>(Catch::TestCase*, Catch::TestCase*, std::allocator<Catch::TestCase>&) /usr/include/c++/7.3.0/bits/stl_construct.h:206

    #14 0x55815102193b in std::vector<Catch::TestCase, std::allocator<Catch::TestCase> >::~vector() /usr/include/c++/7.3.0/bits/stl_vector.h:434
    #15 0x558151159b4e in Catch::TestRegistry::~TestRegistry() /home/user/working/hypervisor/build/prefixes/x86_64-test-elf/include/catch/catch.hpp:8164
    #16 0x558150fe85a4 in ~RegistryHub /home/user/working/hypervisor/build/prefixes/x86_64-test-elf/include/catch/catch.hpp:8281
    #17 0x558150fe8657 in ~RegistryHub /home/user/working/hypervisor/build/prefixes/x86_64-test-elf/include/catch/catch.hpp:8281
    #18 0x558150f6fd13 in Catch::cleanUp() /home/user/working/hypervisor/build/prefixes/x86_64-test-elf/include/catch/catch.hpp:8346
    #19 0x558150f80505 in Catch::Session::~Session() /home/user/working/hypervisor/build/prefixes/x86_64-test-elf/include/catch/catch.hpp:9112
    #20 0x558150fd0ba8 in main /home/user/working/hypervisor/build/prefixes/x86_64-test-elf/include/catch/catch.hpp:12552
    #21 0x7f9d26443f49 in __libc_start_main (/usr/lib/libc.so.6+0x20f49)
    #22 0x558150f37399 in _start (/home/user/working/hypervisor/build/bfsdk/x86_64-test-elf/build/test_benchmark+0x29f399)

0x602000000010 is located 0 bytes inside of 16-byte region [0x602000000010,0x602000000020)
allocated by thread T0 here:
    #0 0x7f9d271a7849 in operator new(unsigned long, std::nothrow_t const&) /build/gcc/src/gcc/libsanitizer/asan/asan_new_delete.cc:85
    #1 0x558150f94559 in Catch::makeTestInvoker(void (*)()) /home/user/working/hypervisor/build/prefixes/x86_64-test-elf/include/catch/catch.hpp:10268
    #2 0x558150f3a3c6 in __static_initialization_and_destruction_0 /home/user/working/hypervisor/bfsdk/tests/test_benchmark.cpp:22
    #3 0x558150f3b0f4 in _GLOBAL__sub_I_test_benchmark.cpp /home/user/working/hypervisor/bfsdk/tests/test_benchmark.cpp:52
    #4 0x5581511730ac in __libc_csu_init (/home/user/working/hypervisor/build/bfsdk/x86_64-test-elf/build/test_benchmark+0x4db0ac)

SUMMARY: AddressSanitizer: alloc-dealloc-mismatch /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:45 in __interceptor_free
==41551==HINT: if you don't care about these errors you may set ASAN_OPTIONS=alloc_dealloc_mismatch=0
==41551==ABORTING
```

It appears that the checks are not recording the use of "malloc", but are recording the use of "free" and thinking a mismatch has occurred, when in fact, malloc/free is being used properly.

**Comment by rianquinn** [comment]
NVM. 

Catch was using the nothrow specific new operator which we had not overloaded. The fix was to add the nothrow overloads to this header.
