### ISSUE TITLE
UBSAN does not catch overflow of short, chart

### ISSUE THREAD

**Issue by milianw** [google/sanitizers#940]
Overflows for short, char and signed char are not caught by UBSAN. It does work for long long, long and int though:

```
┌milian:/tmp
└$ cat test.c
#include <limits.h>

int main()
{
  long long ll = LLONG_MAX;
  ++ll;

  long l = LONG_MAX;
  ++l;

  int i = INT_MAX;
  ++i;

  short s = SHRT_MAX;
  ++s;

  char c = CHAR_MAX;
  ++c;

  signed char sc = SCHAR_MAX;
  ++sc;

  return 0;
}
┌milian:/tmp
└$ clang -fsanitize=undefined -g test.c && ./a.out 
test.c:6:3: runtime error: signed integer overflow: 9223372036854775807 + 1 cannot be represented in type 'long long'
    #0 0x55ca3af09f67 in main /tmp/test.c:6:3
    #1 0x7f6ad1feaf49 in __libc_start_main (/usr/lib/libc.so.6+0x20f49)
    #2 0x55ca3aee4249 in _start (/tmp/a.out+0x3249)

test.c:9:3: runtime error: signed integer overflow: 9223372036854775807 + 1 cannot be represented in type 'long'
    #0 0x55ca3af09fbb in main /tmp/test.c:9:3
    #1 0x7f6ad1feaf49 in __libc_start_main (/usr/lib/libc.so.6+0x20f49)
    #2 0x55ca3aee4249 in _start (/tmp/a.out+0x3249)

test.c:12:3: runtime error: signed integer overflow: 2147483647 + 1 cannot be represented in type 'int'
    #0 0x55ca3af0a004 in main /tmp/test.c:12:3
    #1 0x7f6ad1feaf49 in __libc_start_main (/usr/lib/libc.so.6+0x20f49)
    #2 0x55ca3aee4249 in _start (/tmp/a.out+0x3249)
```

**Comment by dvyukov** [comment]
Isn't it defined in C/C++ due to promotion rules? AFAIK if you add two shorts and assign the result to short, arguments are first promoted to int's, int's are added and then the result is truncated back to short.

**Comment by milianw** [comment]
ugh TIL... Considering that this is often not what the developer intended, can we maybe get a flag for this similar to `-fsanitize=unsigned-integer-overflow` to catch these?

**Comment by yugr** [comment]
I once filed [LLVM bug #21530](https://bugs.llvm.org/show_bug.cgi?id=21530) about this and feedback was positive but it never got beyond prototype. Maybe try asking in Bugzilla?

**Comment by LebedevRI** [comment]
https://reviews.llvm.org/D50250

**Comment by LebedevRI** [comment]
And the second half - sign change - is finally here too.
For integer scalars, i claim that the sanitizer is feature-complete.
Only bitfield handling is missing.

**Comment by LebedevRI** [comment]
Compound assignment operators - done (yay)
https://github.com/llvm-mirror/clang/commit/d8a18b8bb0023a295456958e267e84ba1d1f3d1f

**Comment by LebedevRI** [comment]
inc/dec: [check](https://github.com/llvm/llvm-project/commit/9872ea4ed1de4c49300430e4f1f4dfc110a79ab9).
For plain integers i think only bitfields are left.

**Comment by caarecengi** [comment]
Dummy comment to subscribe to this issue

**Comment by LebedevRI** [comment]
You can just click on "Subscribe" button :)
