### ISSUE TITLE
missing stack frames in TSAN

### ISSUE THREAD

**Issue by WallStProg** [google/sanitizers#941]
When running TSAN we're seeing missing stack frames.  For example, TSAN reports the following:

```
WARNING: ThreadSanitizer: destroy of a locked mutex (pid=25100)
    #0 pthread_mutex_destroy /shared/buildtest/clang/5.0.0/llvm/projects/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:1122 (MamaAdapterTest+0x432a1f)
    #1 wlock_destroy /shared/work/OpenMAMA/6.2.1/common/c_cpp/src/c/wlock.c:55:5 (libmama.so+0xe6770)
    #2 mamaEnvTimer_destroy /home/btorpey/work/transact/4.0.0/src/common/Middleware/MamaAdapter/mme/mamaEnvTimer.c:98 (libmme.so+0x45b3)
    #3 wombatQueue_timedDispatch /shared/work/OpenMAMA/6.2.1/common/c_cpp/src/c/queue.c:342:12 (libmama.so+0xe0d5d)
    #4 zmqBridgeMamaQueue_dispatch /home/btorpey/work/OpenMAMA-zmq/2.0/src/queue.c:253:16 (libmamazmqimpl.so+0x1036c)
    #5 mamaQueue_dispatch /shared/work/OpenMAMA/6.2.1/mama/c_cpp/src/c/queue.c:825:12 (libmama.so+0x8cc06)
    #6 dispatchThreadProc /shared/work/OpenMAMA/6.2.1/mama/c_cpp/src/c/queue.c:1303:30 (libmama.so+0x8e6a3)
```

But gdb reports the stack frame as:

```
#0  mamaEnvTimer_destroy (timer=timer@entry=0x7b0c00003390) at mamaEnvTimer.c:98
#1  0x00007ffff6d616bf in mamaEnvTimer_onTimerDestroy (queue=<optimized out>, closure=0x7b0c00003390) at mamaEnvTimer.c:131
#2  0x00007ffff7046cd1 in wombatQueue_dispatchInt (queue=0x7b4000008000, data=0x0, closure=0x0, isTimed=1 '\001', timout=500) at common/c_cpp/src/c/queue.c:326
#3  0x00007ffff7046d5e in wombatQueue_timedDispatch (queue=0x7b4000008000, data=0x0, closure=0x0, timeout=500) at common/c_cpp/src/c/queue.c:342
#4  0x00007ffff44ca36d in zmqBridgeMamaQueue_dispatch (queue=0x7b2000008000) at /home/btorpey/work/OpenMAMA-zmq/2.0/src/queue.c:253
#5  0x00007ffff6ff2c07 in mamaQueue_dispatch (queue=0x7b3400006800) at mama/c_cpp/src/c/queue.c:825
#6  0x00007ffff6ff46a4 in dispatchThreadProc (closure=0x7b440000ff00) at mama/c_cpp/src/c/queue.c:1303
#7  0x0000000000427885 in __tsan_thread_start_func (arg=0x7fffef7be730) at /shared/buildtest/clang/5.0.0/llvm/projects/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:879
#8  0x00000033c0607aa1 in start_thread () from /lib64/libpthread.so.0
#9  0x00000033bfee8bcd in clone () from /lib64/libc.so.6

```

Note that these stack traces are from the same run -- i.e., I ran a TSAN-instrumented executable under gdb and set a breakpoint at the source location (mamaEnvTimer.c:98).

The above is with clang 5.0.0.

Tried adding "fast_unwind_on_malloc=0" to options but that doesn't seem to help.  Couldn't find any other unwind options specific to TSAN at <https://github.com/google/sanitizers/wiki/ThreadSanitizerFlags>.  AFAICT everything is compiled w/"-fno-omit-frame-pointer".

Thanks for any suggestions ...

**Comment by dvyukov** [comment]
TSAN only unwinds through instrumented code. It seems that one of the libraries is not instrumented (libmme.so?).

**Comment by WallStProg** [comment]
Brilliant -- thanks!  That was in fact the problem (libmme is a C library in a C++ project, and didn't get the right command line params).

On a related note, is the fact that TSAN only unwinds through instrumented code documented anywhere?  

The reason I ask is that I'm looking to use TSAN with some libraries that either can't be instrumented (e.g., libjvm.so from JVM) or where instrumentation leads to an unmanageable number of false positives (e.g., libzmq.so from ZeroMQ).

I'm curious what potential issues may arise from using a mix of instrumented and un-instrumented code.

Thanks again ...

**Comment by dvyukov** [comment]
> On a related note, is the fact that TSAN only unwinds through instrumented code documented anywhere?

What kind of documentation are you looking for? FWIW both https://clang.llvm.org/docs/ThreadSanitizer.html and https://github.com/google/sanitizers/wiki/ThreadSanitizerCppManual say `compile and link your program with -fsanitize=thread`.

> or where instrumentation leads to an unmanageable number of false positives (e.g., libzmq.so from ZeroMQ).

Can you tell more? TSan generally does not have false positives if all code is compiled with -fsanitize=thread (except for few obscure ones).

> I'm curious what potential issues may arise from using a mix of instrumented and un-instrumented code.

It depends on how much that code has to do with synchronization. Say if you use a single-threaded non-instrumented media processing library solely to crunch some blobs, it should be fine (except that races during memory accesses in that library won't be detected, of course). But otherwise you can get a varying mix of false positives, false negatives and missed stack frames.

**Comment by WallStProg** [comment]
I understand that the "compile and link with -fsanitize=thread" is the basic idea, but I'm dealing with a rather large library which uses a bunch of third-party libraries, in addition to the code that I build. On top of that, the library is also used by a Java application running under the JVM via JNI.  All of this code is heavily multi-threaded, hence my desire to use TSAN to try to identify where we may have latent problems.

In particular, the specific detail about stack unwinding getting mixed up if there is un-instrumented code in the stack is news to me.

I've used ASAN for a while, and the ability to exclude certain components from instrumentation comes in very handy -- for example, the JVM does *lots* of naughty things with memory.  In any case, I'm simply not willing to go to the trouble of building OpenJDK w/TSAN -- the JVM is a black box as far as I'm concerned, and it does whatever it does.

As for ZeroMQ, its uses lock-free techniques internally that TSAN definitely does not like, and in fact ZeroMQ is used as an example for TSAN's suppressions (<https://github.com/google/sanitizers/wiki/ThreadSanitizerSuppressions>):

```
...
# Uninstrumented library.
called_from_lib:libzmq.so
```

Maybe that's just a coincidence, but in my experience it appears to be necessary to avoid instrumenting ZeroMQ with TSAN.  The potential problem that I'm concerned about is missing error reports in callbacks that originate with ZeroMQ, but so far I haven't found that to be a problem.

**Comment by dvyukov** [comment]
Well, the requirement to compile code with tsan is not just somebody's caprice. There are fundamental technical problems underneath. Asan obtains stack traces only for malloc and free, it's feasible to unwind on these events. Tsan needs stack traces for each and every memory access in the program, it's not feasible to unwind on every memory access. Besides stack traces, synchronization is even more fundamental to tsan operation and missed synchronization is simply unrecoverable.

**Comment by dvyukov** [comment]
The fact that tsan produces lots of reports on zeromq does not necessary mean false positives, it can also be that zeromq contains lots of bugs. Tsan generally likes lock-free techniques, but it does not like buggy lock-free techniques.

**Comment by WallStProg** [comment]
True, but I have to start somewhere, and it's reasonable to assume that *my* code has more bugs than code which is (more) widely used.  I'm just trying to start at the bottom and work up, until I run out of time or bugs.

In the meantime, the practical problem is to increase the signal-to-noise ratio.  The easy way to do that (and the way that works with other sanitizers) is to simply not instrument code you don't want checked, and that pretty much works.  I hear what you're saying about TSAN having a tougher problem to solve, and it's good to know how that affects the granularity of the stack traces.  (A note in the docs might help, and I'm happy to do a PR if you'd like).

That leaves suppressions, which can be difficult to work with -- they're always either too narrow or too broad.  (We also post-process the output of sanitizers, so we may be able to come up with a way to further winnow out false positives).

I *am* curious though how libzmq.so got used as an example in the docs:  https://github.com/google/sanitizers/wiki/ThreadSanitizerSuppressions.  If anyone in the community knows about that, I'd love to know.

Thanks again for the help!

**Comment by dvyukov** [comment]
> The easy way to do that (and the way that works with other sanitizers) is to simply not instrument code you don't want checked, and that pretty much works.

By "other sanitizers" you probably mean ASAN. ASAN only needs to intercept malloc/free (which are always in libc) and then an arbitrary set of memory accesses. If it does not intercept some memory accesses, it just leads to false negatives on these accesses.
But if you take MSAN, then situation is even worse than with TSAN. MSAN needs to intercept _all_ memory accesses and all computations. Which pretty much means instrument everything.

There are some precedents of making TSAN work with non-instrumented libraries. Success of this highly depends on what exactly these libraries are doing. Besides suppressions, one can use `ignore_interceptors_accesses` flag which ignores races in, say, memcpy called from a non-instrumented library. Then, `ignore_noninstrumented_modules` flag which makes TSAN ignore all interceptors called from the given set of (non-instrumented) libraries. Also, TSAN has some dynamic annotations (http://llvm.org/viewvc/llvm-project/compiler-rt/trunk/lib/tsan/rtl/tsan_interface_ann.cc?revision=319650&view=markup) which can be inserted into code to tell it about some synchronization, or ignore races on given memory ranges.

Improving documentation (https://github.com/google/sanitizers/wiki/ThreadSanitizerCppManual) is always welcome.

**Comment by WallStProg** [comment]
> By "other sanitizers" you probably mean ASAN.

Yes (plus LSAN, which is the same thing).

> The fact that tsan produces lots of reports on zeromq does not necessary mean false positives, it can also be that zeromq contains lots of bugs. 

So I dug a little deeper, and ZeroMQ provides a build-time flag to select the use of compiler intrinsics (e.g., __atomic_fetch_add, etc.) for atomic operations.  In my simple "smoke test" program, using the instrinsics supported by TSAN decreased the number of warnings from 493 to 75.  

The remaining warnings I suspect can be attributed to  ZeroMQ's design (http://zeromq.org/whitepapers:architecture), where certain data structures are deliberately *not* protected by mutexes -- instead, a sort of "temporal" synchronization is used where the code "knows" when it is safe to access shared state.  This is clearly not something that TSAN can know about (at least not without annotations).

> There are some precedents of making TSAN work with non-instrumented libraries...

Thanks for the tip.  I will be digging into the code to learn more about the flags you mention.

> Improving documentation is always welcome.

I don't see a way to submit a PR against the wiki, so I've attached a couple of files that expand on the existing docs.  Please let me know if there's a better way to suggest changes.

And again, thanks for the thoughtful replies!

[wiki.zip](https://github.com/google/sanitizers/files/1943111/wiki.zip)

**Comment by dvyukov** [comment]
FTR, here is a new part for the manual:

```
# Stack Traces

Given that ThreadSanitizer needs stack traces for each and every memory access in the program, performance of the stack unwinder is critical.  For that reason, TSAN uses the equivalent of the "fast" unwinder used by e.g., AddressSanitizer.  The effect of this is that TSAN will sometimes not display full stack traces, under the following conditions:

- If un-instrumented code is interspersed with instrumented code in the stack trace.
- If code is compiled with `-fomit-frame-pointer` (the default with -O2 and above).

If you suspect that your stack traces are incomplete, please ensure that all code is instrumented (`-fsanitize=thread`), and built with `-fno-omit-frame-pointer`.
```

And here is the new text for the report format page:

```
(If your stack trace appears incomplete, please see the "Stack Traces" section in the [ThreadSanitizerCppManual](ThreadSanitizerCppManual) page).
```

This is all, right?

**Comment by WallStProg** [comment]
Yes.

**Comment by dvyukov** [comment]
I am not sure the part about `-fomit-frame-pointer` is correct. Tsan does not use fast unwind. It uses instrumentation to capture frames on function entry. And that ever uses caller PC, which should not require frame pointers.
Do you see any difference with/without `-fomit-frame-pointer`?

**Comment by WallStProg** [comment]
Actually no.  I included that bit based on past experience with other stack unwinders being confused by `-fomit-frame-pointer`, but if that's not relevant for TSAN then it should come out.

**Comment by dvyukov** [comment]
> So I dug a little deeper, and ZeroMQ provides a build-time flag to select the use of compiler intrinsics (e.g., __atomic_fetch_add, etc.) for atomic operations.

This is the first thing to do for tsan.

> The remaining warnings I suspect can be attributed to ZeroMQ's design 

Tsan understands atomic operations (as you can see by the difference caused by the switch to intrinsics). If you mean something like sequence locks, there is a way to express them correctly in C/C++ even though the data is not protected by mutexes. I suspect that 0mq just does not do it right.

**Comment by WallStProg** [comment]
Here's an updated version:

# Stack Traces

Given that ThreadSanitizer needs stack traces for each and every memory access in the program, performance of the stack unwinder is critical.  For that reason, TSAN uses the equivalent of the "fast" unwinder used by e.g., AddressSanitizer.  The effect of this is that TSAN will sometimes not display full stack traces if un-instrumented code is interspersed with instrumented code in the stack trace.

If you suspect that your stack traces are incomplete, please ensure that all code is instrumented (`-fsanitize=thread`).

**Comment by dvyukov** [comment]
I've added this section, please check:
https://github.com/google/sanitizers/wiki/ThreadSanitizerCppManual#non-instrumented-code
Tsan does not use _any_ unwinder. Its approach is radically different from anything used in Asan.

**Comment by WallStProg** [comment]
Looks great -- thanks!

**Comment by dvyukov** [comment]
The instrumentation pass has these flags which can be used to turn off instrumentation of memory accesses:
```
54	static cl::opt<bool>  ClInstrumentMemoryAccesses(
55	    "tsan-instrument-memory-accesses", cl::init(true),
56	    cl::desc("Instrument memory accesses"), cl::Hidden);
57	static cl::opt<bool>  ClInstrumentFuncEntryExit(
58	    "tsan-instrument-func-entry-exit", cl::init(true),
59	    cl::desc("Instrument function entry and exit"), cl::Hidden);
60	static cl::opt<bool>  ClHandleCxxExceptions(
61	    "tsan-handle-cxx-exceptions", cl::init(true),
62	    cl::desc("Handle C++ exceptions (insert cleanup blocks for unwinding)"),
63	    cl::Hidden);
64	static cl::opt<bool>  ClInstrumentAtomics(
65	    "tsan-instrument-atomics", cl::init(true),
66	    cl::desc("Instrument atomics"), cl::Hidden);
67	static cl::opt<bool>  ClInstrumentMemIntrinsics(
68	    "tsan-instrument-memintrinsics", cl::init(true),
69	    cl::desc("Instrument memintrinsics (memset/memcpy/memmove)"), cl::Hidden);
```
http://llvm.org/viewvc/llvm-project/llvm/trunk/lib/Transforms/Instrumentation/ThreadSanitizer.cpp?revision=328165&view=markup

I don't remember the exact syntax of how to pass them. Maybe `-mllvm flag`? If you won't figure it out, I can try to find/try it.

**Comment by WallStProg** [comment]
Hi Dmitry:

With your help, I think I've been able to come up with a viable approach to dealing with library code like ZeroMQ that have a non-standard approach to synchronization.

I'm posting the build flags I use for libzmq below for your information, as well as to potentially help others who may have a similar problem.

```
if("$ENV{BUILD_TYPE}" STREQUAL "tsan")
  #
  # NOTE: TSAN generates many false(?) positives w/ZMQ, esp. if ZMQ is built w/o "-DZMQ_HAVE_ATOMIC_INTRINSICS=1"
  # These flag settings have been arrived at w/help of https://github.com/dvyukov along with trial and error to
  # enable ZMQ to "play nice" w/other code instrumented w/TSAN.
  #
  # Note also that a runtime suppression "called_from_lib:libzmq.so" is also required to prevent spurious reports when 
  # ZMQ calls intercepted functions (e.g., memcpy).
  #
  # See https://github.com/google/sanitizers/issues/941 for more info.
  #
  # P.S.  These settings may cause warnings like following -- this is a known issue w/cmake passing compile-specific flags to linker 
  # when building shared libs.
  # clang-7: warning: argument unused during compilation: '-mllvm -tsan-instrument-memory-accesses=false' [-Wunused-command-line-argument]
  #
  # standard flags 
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsanitize=thread -fPIE")
  # following settings disable TSAN instrumentation (*except* for func entry/exit)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mllvm -tsan-instrument-memory-accesses=false ")
  # not strictly needed if building w/"-DZMQ_HAVE_ATOMIC_INTRINSICS=1" (see above)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mllvm -tsan-instrument-atomics=false")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mllvm -tsan-handle-cxx-exceptions=false")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mllvm -tsan-instrument-memintrinsics=false")
  # this is needed for proper stack traces w/TSAN
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mllvm -tsan-instrument-func-entry-exit=true")
  set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -fsanitize=thread  ")
  set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -fsanitize=thread -pie ")
endif()
```

There's one remaining bump in the road, for which I created a new issue: https://github.com/google/sanitizers/issues/949

Thanks again for all the help!

**Comment by morehouse** [comment]
@WallStProg:  Can this be closed?

**Comment by WallStProg** [comment]
@morehouse: I'm not sure -- that depends on what your criteria for closing issues is.

- From the testing I've done, it appears that it's not possible to use TSAN effectively (i.e., without a lot of false positives and/or false negatives) with un-instrumented libraries on Linux, because doing so requires setting the run-time flag `ignore_noninstrumented_modules=1`, but that setting is silently ignored on Linux.  (It apparently is supported on MacOS).

- Even with the `ignore_noninstrumented_modules=1` setting, stack traces are missing frames because of the way TSAN captures stack traces.  
  - For stack traces to be accurate, ALL libraries need to be built with the `-mllvm -tsan-instrument-func-entry-exit=true`.
  - To prevent TSAN from generating warnings against a library, the library must be built with a number of additional flags to disable everything *but* the function entry/exit instrumentation.      Based on Dmitry's suggestions and my testing, I think these flags are:

```
-fsanitize=thread -fPIE
-mllvm -tsan-instrument-memory-accesses=false
-mllvm -tsan-instrument-atomics=false
-mllvm -tsan-handle-cxx-exceptions=false
-mllvm -tsan-instrument-memintrinsics=false
-mllvm -tsan-instrument-func-entry-exit=true
```  

I don't know if making TSAN work with un-instrumented libraries  is a priority for anyone, but it's beyond my capabilities at this point.  (Plus I have an even bigger problem, which is that it looks like TSAN and JNI code don't play nice together either).

However, it would have been nice if I knew all this before going down this rabbit hole.  Don't get me wrong -- TSAN is a terrific tool, and even with its limitations I've been able to use it effectively by carving out pieces of my application and running them under TSAN, and found some bugs that way.  But it took a fair amount of my (and Dmitry's) time to get to this point, so it would be helpful to capture this information somehow.

Dmitry has been kind enough to update the docs with some of this information, but a more detailed write-up might help others who are going down this road.  I'd be happy to try to work something up if you like -- please let me know.
