### ISSUE TITLE
MSan: SEGV at instrumented libc++ on static initialization of standard streams

### ISSUE THREAD

**Issue by compor** [google/sanitizers#947]
I have followed the instructions [here][1] in order to instrument `libc++` and `googletest`.
The proposed test programs get executed properly (both the [initial one][2] that used to report a false positive and the [later one][3] where we introduced a bug).

```bash
clang version 6.0.1 (https://github.com/llvm-mirror/clang.git 0e746072ed897a85b4f533ab050b9f506941a097) (https://github.com/llvm-mirror/llvm.git f1b37feef3d5f09dadf6a46fdb11fa7e4218cf6c)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /bulk/workbench/llvm/6.0/toolchain1/bin
```

I have also verified that both my `libc++` and `googletest` have been properly instrumented with MSan (if there is a better way, I'd be happy to use that):

```bash
nm /bulk/workbench/llvm/6.0/libcxx-msan/lib/libc++.so.1.0  | grep '__asan\|__tsan\|__msan'
                 U __msan_init                                                                 
                 U __msan_memcpy                                                               
                 U __msan_memmove                                                              
                 U __msan_memset                                                               
                 U __msan_param_tls                                                            
                 U __msan_retval_tls
                 U __msan_va_arg_overflow_size_tls                                             
                 U __msan_va_arg_tls                                                           
                 U __msan_warning_noreturn    
```

However, when I'm applying all that to my unit test executable for my library I get the following:

```bash
MemorySanitizer:DEADLYSIGNAL                                                                   
==25127==ERROR: MemorySanitizer: SEGV on unknown address 0x3fffffffc4e0 (pc 0x7ffff7ecafca bp 0x7fffffffc510 sp 0x7fffffffc460 T25127)                                                        
==25127==The signal is caused by a WRITE memory access.                                        
    #0 0x7ffff7ecafc9 in std::__1::ios_base::Init::Init() /bulk/workbench/llvm/6.0/source/libcxx/src/iostream.cpp:83                                                                          
    #1 0x7ffff7e78639 in __cxx_global_var_init /bulk/workbench/llvm/6.0/source/libcxx/src/iostream.cpp:80:16                                                                                  
    #2 0x7ffff7e78639 in _GLOBAL__sub_I_iostream.cpp /bulk/workbench/llvm/6.0/source/libcxx/src/iostream.cpp                                                                                  
    #3 0x7ffff7dea1d9 in call_init /build/eglibc-ripdx6/eglibc-2.19/elf/dl-init.c:78           
    #4 0x7ffff7dea2c2 in call_init /build/eglibc-ripdx6/eglibc-2.19/elf/dl-init.c:36           
    #5 0x7ffff7dea2c2 in _dl_init /build/eglibc-ripdx6/eglibc-2.19/elf/dl-init.c:126           
    #6 0x7ffff7ddb299  (/lib64/ld-linux-x86-64.so.2+0x1299)    
```

The `gdb` trace is pretty much the same:

```bash
Program received signal SIGSEGV, Segmentation fault.                                           
0x00007ffff7ecafca in Init () at /bulk/workbench/llvm/6.0/source/libcxx/src/iostream.cpp:83    
83      {                                                                                      
(gdb) bt                                                                                       
#0  0x00007ffff7ecafca in Init () at /bulk/workbench/llvm/6.0/source/libcxx/src/iostream.cpp:83                                                                                               
#1  0x00007ffff7e7863a in _GLOBAL__sub_I_iostream.cpp () at /bulk/workbench/llvm/6.0/source/libcxx/src/iostream.cpp:80                                                                        
#2  0x00007ffff7dea1da in call_init (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0x7fffffffc5b8, env=env@entry=0x7fffffffc5c8) at dl-init.c:78                                      
#3  0x00007ffff7dea2c3 in call_init (env=<optimized out>, argv=<optimized out>, argc=<optimized out>, l=<optimized out>) at dl-init.c:36                                                      
#4  _dl_init (main_map=0x7ffff7ffe1c8, argc=1, argv=0x7fffffffc5b8, env=0x7fffffffc5c8) at dl-init.c:126                                                                                      
#5  0x00007ffff7ddb29a in _dl_start_user () from /lib64/ld-linux-x86-64.so.2                   
#6  0x0000000000000001 in ?? ()                                                                
#7  0x00007fffffffcb95 in ?? ()                                                                
#8  0x0000000000000000 in ?? ()
```

Now, this seems like an initialization problem (e.g. similar to issue #30) with the C++ standard stream objects (`std::cout`, etc.), since the reference call in the stack traces is [`std::ios_base::Init`][4].

This doesn't make much sense and I can't think of any way to trigger it at the smaller test program, although I did try adding this to the basic test case to no avail:

```c++
#include <iostream>

struct bar { bar() { std::cout << "bar"; }  };

bar b;
```

Any ideas/suggestions?

[1]: https://github.com/google/sanitizers/wiki/MemorySanitizerLibcxxHowTo
[2]: https://github.com/google/sanitizers/wiki/MemorySanitizerLibcxxHowTo#test-program
[3]: https://github.com/google/sanitizers/wiki/MemorySanitizerLibcxxHowTo#bugs-reporting
[4]: http://en.cppreference.com/w/cpp/io/ios_base/Init

**Comment by eugenis** [comment]
In your maps all origin regions are PROT_NONE, as expected when none of the libraries are built with -fsanitize-memory-track-origins. I'm not sure what went wrong. You can try looking at the assembly to understand what this access is supposed to do.

> I haven't built LLVM against MSan, although I think I should. However, my understanding is that the aforementioned std::ios_base::Init call is provided by the MSan libc++, so I haven't hit any issue with that yet. If so, I'd have gotten a false positive and not a crash. Is there any basis to those assumptions?

Yes, this should not cause a crash.

**Comment by compor** [comment]
Thanks for your replies so far.

I did rebuilt everything with `-fsanitize-memory-track-origins`, but I didn't notice anything different apart from this text being added on the verbose output:

```bash
msan_track_origins
__msan_init 0x7f1a0cdbdc10
```

Do you mean disassembling with `gdb` around the "crash site"? I'm not sure what I'll be looking for, but I'll give it go.
If you have any suggestions/ideas (even wild guesses), please post them here.

**Comment by eugenis** [comment]
With track-origins maps should look something like this:
300000000000-400000000000 rw-p
400000000000-500000000000 ---p

If this access to 0x30... is MSan origin store, then it should be the result of some application pointer (p^0x50... + 0x10...) . Of course, that's only possible if the code was built with -fsanitize-memory-track-origins.
