### ISSUE TITLE
All 32-bit binaries crash with glibc 2.27

### ISSUE THREAD

**Issue by Lekensteyn** [google/sanitizers#954]
All 32-bit applications currently crash with glibc 2.27 as demonstrated by:
```
$ echo 'int main(){}' > empty.c
$ clang -g -fsanitize=address -m32 empty.c -o empty && ./empty
=================================================================
==27867==ERROR: AddressSanitizer: SEGV on unknown address 0xf7f70020 (pc 0xf7f70034 bp 0xffa9ac1c sp 0xffa9abdc T16777215)
==27867==The signal is caused by a WRITE memory access.
    #0 0xf7f70033 in _dl_get_tls_static_info (/lib/ld-linux.so.2+0x12033)
    #1 0x567081cb in __sanitizer::InitTlsSize() (main+0x11b1cb)
    #2 0x566e7cd2 in __asan::AsanInitInternal() [clone .part.0] (main+0xfacd2)
    #3 0xf7f6da57 in _dl_init (/lib/ld-linux.so.2+0xfa57)
    #4 0xf7f5ec99  (/lib/ld-linux.so.2+0xc99)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/lib/ld-linux.so.2+0x12033) in _dl_get_tls_static_info
==27867==ABORTING
```
For some reason the calling convention has changed from `regparm(2)` to cdecl. It has likely something to do with https://sourceware.org/git/gitweb.cgi?p=glibc.git;a=commit;h=17e00cc69eac2ec10ac69a3f85db0dffc9d73845

Environment: Arch Linux x86_64 with lib32-glibc 2.27-3. Working version is lib32-glibc 2.26-11.

Related topic: #914

**Comment by kcc** [comment]
The discussion with the glibc folks died out. I will ping, but I don't have high hopes. 
My team does not have resources to chaise all glibc versions especially if the glibc team does not cooperate.

**Comment by fweimer** [comment]
Jakub fix this in the GCC copy of the code: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=84761

**Comment by kcc** [comment]
.. and looks like the same change has never been applied to clang
https://reviews.llvm.org/D44623

As we agreed many years ago, GCC variant of run-time should be a verbatim copy of one in LLVM
and the changes should go to LLVM first. 
It's sad that we don't follow this agreement any more.

**Comment by krytarowski** [comment]
I've fixed ASan for NetBSD/i386 https://reviews.llvm.org/D45652

**Comment by Lekensteyn** [comment]
@krytarowski is that related to this issue or the other? I am not sure if NetBSD uses glibc.

Is it OK to fix LLVM and then retroactively change GCC? I would prefer making progress in LLVM and not depend on GCC for fixing this. D44623 seems a good start.

There is another version check slightly below in `InitTlsSize`, it parses `_CS_GNU_LIBC_VERSION`. Would it be worth pulling that into a separate function and reuse it? Then the `dlvsym` call could be dropped.

Regarding the synchronization between GCC/LLVM wrt compiler-rt, I have no idea about that. Perhaps @fweimer could comment on that?

**Comment by kcc** [comment]
Our contract between LLVM and GCC is (has been?) that *all* changes to sanitizer run-times are first made to the LLVM tree. Then GCC pulls them whenever they need to. 
If this contract is not respected by the GCC team any more (is it?) -- I am sorry, but I have no control over it.

**Comment by krytarowski** [comment]
@Lekensteyn I've noted issues with TLS and i386 and though it will be worth to share for your interest. We can use GLIBC, but it's non-orthodox :)

If it's totally unrelated, please disregard.

**Comment by Lekensteyn** [comment]
Perhaps it is a misunderstanding and not an intentional contract violation. Let's see what GCC/@jakubjelinek has to say about the comment in https://gcc.gnu.org/bugzilla/show_bug.cgi?id=84761#c12
