### ISSUE TITLE
make -fsanitize=memory,fuzzer work out of the box

### ISSUE THREAD

**Issue by kcc** [google/sanitizers#958]
Now that libFuzzer uses a private version of libc++ this may become possible. Please investigate.

**Comment by morehouse** [comment]
Just making sure I understand this...

We currently build libc++ in a private namespace for use by libFuzzer only (not application code).  So probably false positives coming from libFuzzer's use of libc++ can be avoided for MSan.  But won't we still need to build lib[std]c++ with MSan for application code?

**Comment by kcc** [comment]
Of course, the application code still need its own instrumented copy of libc++. 
But we should not need to rebuild libFuzzer with msan as we do on oss-fuzz now
if libFuzzer uses its own private libc++ (hopefully)

**Comment by morehouse** [comment]
There's also difficulties with interceptors checking for poisoned arguments when called within libFuzzer.  Any way to disable/avoid those just for libFuzzer?  Things could get ugly if we have to unpoison things before every libc call.

**Comment by morehouse** [comment]
Yes, I've had issues with `fopen`, `memmem`, and `memcmp` so far.  

```
Uninitialized bytes in __interceptor_memmem at offset 0 inside [0x720000000000, 1)
==14055==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x45cec3 in fuzzer::MutationDispatcher::MakeDictionaryEntryFromCMP(void const*, void const*, void const*, void const*, unsigned long, unsigned char const*, unsigned long) /lib/fuzzer/FuzzerMutate.cpp:214:28
    #1 0x45da52 in fuzzer::DictionaryEntry fuzzer::MutationDispatcher::MakeDictionaryEntryFromCMP<unsigned short>(unsigned short, unsigned short, unsigned char const*, unsigned long) lib/fuzzer/FuzzerMutate.cpp:233:10
    #2 0x45c25d in fuzzer::MutationDispatcher::Mutate_AddWordFromTORC(unsigned char*, unsigned long, unsigned long) lib/fuzzer/FuzzerMutate.cpp:255:12
    #3 0x4602e4 in fuzzer::MutationDispatcher::MutateImpl(unsigned char*, unsigned long, unsigned long, std::__Fuzzer::vector<fuzzer::MutationDispatcher::Mutator, fuzzer::fuzzer_allocator<fuzzer::MutationDispatcher::Mutator> >&) lib/fuzzer/FuzzerMutate.cpp:518:22
    #4 0x449a3d in fuzzer::Fuzzer::MutateAndTestOne() lib/fuzzer/FuzzerLoop.cpp:653:18
    #5 0x44a625 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<std::__Fuzzer::basic_string<char, std::__Fuzzer::char_traits<char>, std::__Fuzzer::allocator<char> >, fuzzer::fuzzer_allocator<std::__Fuzzer::basic_string<char, std::__Fuzzer::char_traits<char>, std::__Fuzzer::allocator<char> > > > const&) lib/fuzzer/FuzzerLoop.cpp:791:5
```
```
Uninitialized bytes in __interceptor_memcmp at offset 0 inside [0x703000000330, 40)
==506==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x44d6ae in compare build/projects/compiler-rt/lib/fuzzer/libcxx_fuzzer_x86_64/include/c++/v1/__string:249:12
    #1 0x44d6ae in operator==<std::__Fuzzer::allocator<char> > build/projects/compiler-rt/lib/fuzzer/libcxx_fuzzer_x86_64/include/c++/v1/string:3625
    #2 0x44d6ae in operator() build/projects/compiler-rt/lib/fuzzer/libcxx_fuzzer_x86_64/include/c++/v1/functional:670
    #3 0x44d6ae in std::__Fuzzer::__hash_iterator<std::__Fuzzer::__hash_node<std::__Fuzzer::basic_string<char, std::__Fuzzer::char_traits<char>, std::__Fuzzer::allocator<char> >, void*>*> std::__Fuzzer::__hash_table<std::__Fuzzer::basic_string<char, std::__Fuzzer::char_traits<char>, std::__Fuzzer::allocator<char> >, std::__Fuzzer::hash<std::__Fuzzer::basic_string<char, std::__Fuzzer::char_traits<char>, std::__Fuzzer::allocator<char> > >, std::__Fuzzer::equal_to<std::__Fuzzer::basic_string<char, std::__Fuzzer::char_traits<char>, std::__Fuzzer::allocator<char> > >, std::__Fuzzer::allocator<std::__Fuzzer::basic_string<char, std::__Fuzzer::char_traits<char>, std::__Fuzzer::allocator<char> > > >::find<std::__Fuzzer::basic_string<char, std::__Fuzzer::char_traits<char>, std::__Fuzzer::allocator<char> > >(std::__Fuzzer::basic_string<char, std::__Fuzzer::char_traits<char>, std::__Fuzzer::allocator<char> > const&) build/projects/compiler-rt/lib/fuzzer/libcxx_fuzzer_x86_64/include/c++/v1/__hash_table:2227
    #4 0x448f44 in __erase_unique<std::__Fuzzer::basic_string<char> > build/projects/compiler-rt/lib/fuzzer/libcxx_fuzzer_x86_64/include/c++/v1/__hash_table:2390:20
    #5 0x448f44 in erase build/projects/compiler-rt/lib/fuzzer/libcxx_fuzzer_x86_64/include/c++/v1/unordered_set:537
    #6 0x448f44 in fuzzer::InputCorpus::Replace(fuzzer::InputInfo*, std::__Fuzzer::vector<unsigned char, fuzzer::fuzzer_allocator<unsigned char> > const&) lib/fuzzer/FuzzerCorpus.h:156
    #7 0x447f68 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) lib/fuzzer/FuzzerLoop.cpp:481:12
    #8 0x449a6e in fuzzer::Fuzzer::MutateAndTestOne() lib/fuzzer/FuzzerLoop.cpp:661:19
    #9 0x44a625 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<std::__Fuzzer::basic_string<char, std::__Fuzzer::char_traits<char>, std::__Fuzzer::allocator<char> >, fuzzer::fuzzer_allocator<std::__Fuzzer::basic_string<char, std::__Fuzzer::char_traits<char>, std::__Fuzzer::allocator<char> > > > const&) lib/fuzzer/FuzzerLoop.cpp:792:5
```
```
Uninitialized bytes in __interceptor_fopen at offset 0 inside [0x7040000000c0, 49)
==4476==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x444d31 in fuzzer::WriteToFile(std::__Fuzzer::vector<unsigned char, fuzzer::fuzzer_allocator<unsigned char> > const&, std::__Fuzzer::basic_string<char, std::__Fuzzer::char_traits<char>, std::__Fuzzer::allocator<char> > const&) lib/fuzzer/FuzzerIO.cpp:65:15
    #1 0x446dbe in fuzzer::Fuzzer::WriteUnitToFileWithPrefix(std::__Fuzzer::vector<unsigned char, fuzzer::fuzzer_allocator<unsigned char> > const&, char const*) lib/fuzzer/FuzzerLoop.cpp:558:3
    #2 0x446500 in fuzzer::Fuzzer::DumpCurrentUnit(char const*) lib/fuzzer/FuzzerLoop.cpp:191:3
    #3 0x447099 in fuzzer::Fuzzer::ExitCallback() lib/fuzzer/FuzzerLoop.cpp:255:3
    #4 0x4caa83 in MSanAtExitWrapper(void*) lib/msan/msan_interceptors.cc:1087:3
    #5 0x7efd90b6f90f  (/lib/x86_64-linux-gnu/libc.so.6+0x3590f)
    #6 0x7efd90b6f969 in exit (/lib/x86_64-linux-gnu/libc.so.6+0x35969)
    #7 0x516402 in LLVMFuzzerTestOneInput test/fuzzer/NoLibcxx.cpp:16:9
    #8 0x4482ba in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) lib/fuzzer/FuzzerLoop.cpp:529:13
    #9 0x447c9b in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) lib/fuzzer/FuzzerLoop.cpp:453:3
    #10 0x449a6e in fuzzer::Fuzzer::MutateAndTestOne() lib/fuzzer/FuzzerLoop.cpp:661:19
    #11 0x44a625 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<std::__Fuzzer::basic_string<char, std::__Fuzzer::char_traits<char>, std::__Fuzzer::allocator<char> >, fuzzer::fuzzer_allocator<std::__Fuzzer::basic_string<char, std::__Fuzzer::char_traits<char>, std::__Fuzzer::allocator<char> > > > const&) lib/fuzzer/FuzzerLoop.cpp:792:5
```

Each time I silence one warning with an `__msan_unpoison`, another seems to pop up.

**Comment by morehouse** [comment]
Been working on this for a few days.  So far I have workarounds or private implementations for `memcmp`, `strstr`, `strlen`, `memmem`, `std::string`, `fopen`, `opendir`, `std::ifstream`.

Some of my implementations are probably not as efficient as the LibC versions.  Some of my workarounds are kind of hacky (e.g. using `fdopendir(open(...))` instead of `opendir(...)`).

102 / 126 tests are passing under MSan.  The 24 failures are ~50% false positives and 50% due to being written for ASan.

How badly do we want this?  I don't want to keep working on this if we don't want to pay for the slightly slower implementation and uglier code.

**Comment by eugenis** [comment]
AFAIK any interceptor in msan is a scoped-ignore interceptor, but I'm not sure what are you proposing to do with it. Did you mean scoped-not-ignore?

**Comment by morehouse** [comment]
Works on tests as of https://reviews.llvm.org/D48891.
