### ISSUE TITLE
dr asan inlined strlen false positive in libfontconfig.so

### ISSUE THREAD

**Issue by ramosian-glider** [google/sanitizers#97]
Originally reported on Google Code with ID 97
```
This is running DRT on gPrecise.

The asan report has a crummy stack trace still:
=================================================================
==16664== ERROR: AddressSanitizer heap-buffer-overflow on address 0x7fffef2c1f94 at
pc 0x7ffff58620d3 bp 0x7fffffffa910 sp 0x7fffffffa908
READ of size 4 at 0x7fffef2c1f94 thread T0
    #0 0x7ffff58620d3 (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1.4.4+0x80d3)
0x7fffef2c1f94 is located 0 bytes to the right of 22-byte region [0x7fffef2c1f80,0x7fffef2c1f96)
allocated by thread T0 here:
    #0 0x5463022 (/usr/local/google/home/rnk/chromium/src/out_asan/Release/DumpRenderTree+0x5463022)
    #1 0x7ffff586202d (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1.4.4+0x802d)

I should fix that.

I got one from gdb:

#0  0x0000000005464964 in __asan_report_load4 ()
#1  0x00007ffff58620d3 in FcConfigFileExists (dir=0x7fffef2c1f80 "/etc/fonts", file=0x7ffff5879ab5
"fonts.conf") at fccfg.c:1671
#2  0x00007ffff5864465 in IA__FcConfigFilename (url=0x7ffff5879ab5 "fonts.conf") at
fccfg.c:1828
#3  0x00007ffff5877a16 in IA__FcConfigParseAndLoad (config=0x7fffefdf6480, name=0x0,
complain=1) at fcxml.c:2459
#4  0x00007ffff586d177 in IA__FcInitLoadConfig () at fcinit.c:67
#5  0x00007ffff586d266 in IA__FcInitLoadConfigAndFonts () at fcinit.c:101
#6  0x00007ffff586d485 in IA__FcInit () at fcinit.c:124
#7  0x00000000004cf699 in setupFontconfig () at ../../third_party/WebKit/Tools/DumpRenderTree/chromium/TestShellX11.cpp:86
#8  platformInit (argc=0x7fffef2c2094, argv=0x7fffef2c2094) at ../../third_party/WebKit/Tools/DumpRenderTree/chromium/TestShellX11.cpp:189
#9  0x000000000045fc0d in main (argc=<optimized out>, argv=<optimized out>) at ../../third_party/WebKit/Tools/DumpRenderTree/chromium/DumpRenderTree.cpp:123

Here's the disassembly which makes me think it's strlen.  I haven't verified that the
code actually works or corresponds.

   0x00007ffff58620cb <+203>:	callq  0x7ffff585fda0 <strcat@plt>
---Type <return> to continue, or q <return> to quit---
   0x00007ffff58620d0 <+208>:	mov    %rbx,%rsi
=> 0x00007ffff58620d3 <+211>:	mov    (%rsi),%edx
   0x00007ffff58620d5 <+213>:	add    $0x4,%rsi
   0x00007ffff58620d9 <+217>:	lea    -0x1010101(%rdx),%eax
   0x00007ffff58620df <+223>:	not    %edx
   0x00007ffff58620e1 <+225>:	and    %edx,%eax
   0x00007ffff58620e3 <+227>:	and    $0x80808080,%eax
   0x00007ffff58620e8 <+232>:	je     0x7ffff58620d3 <FcConfigFileExists+211>


Maybe we can suppress this by looking for "and 0x8080808080" in the current bb?  Sounds
pretty hacky.  We have a bunch of pattern matchers for this kind of thing in drmemory.
```

Reported by `rnk@google.com` on 2012-08-02 20:05:34

**Comment by kcc** [comment]
no more DR work
