### ISSUE TITLE
asan: `stack-use-after-scope` false positive(?) when adding omp pragma to basic loop 

### ISSUE THREAD

**Issue by martyngigg** [google/sanitizers#994]
I have been successfully eliminating hard to find bugs with the help of address sanitizer - thanks for the great tool! I have, however, come across an issue that I don't understand and I think might be a false positive.

The following code:
```c++
#include <memory>

int main(int argc, char**) {
  #pragma omp parallel for
  for(int i = 0; i < 10000 + argc; ++i) {
    auto p = std::make_unique<int>(i);
  }
  return 0;
}
```
is the most basic version that I could get to reproduce the issue that our code base is also generating. It only appears when using the `#pramga omp parallel for` and commenting this out removes the sanitizer issue.

I compiled the above with `clang++ -Wall -Wextra -fopenmp -O1 -std=c++14 -g -fsanitize=address -o omp omp.cpp` and running the executable gives:
```
$ ./omp
=================================================================
==13101==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7ffe6e6a1480 at pc 0x0000005174ec bp 0x7ffe6e6a13f0 sp 0x7ffe6e6a13e8
WRITE of size 4 at 0x7ffe6e6a1480 thread T0
    #0 0x5174eb in .omp_outlined._debug__ /home/mgigg/Code/git/martyngigg/sandbox/cpp/asan/omp/omp.cpp:5:36
    #1 0x7f3bdf780452 in __kmp_invoke_microtask (/usr/lib/x86_64-linux-gnu/libomp.so.5+0x7c452)
    #2 0x7f3bdf73a1b6  (/usr/lib/x86_64-linux-gnu/libomp.so.5+0x361b6)
    #3 0x7f3bdf73b2b5 in __kmp_fork_call (/usr/lib/x86_64-linux-gnu/libomp.so.5+0x372b5)
    #4 0x7f3bdf72e7be in __kmpc_fork_call (/usr/lib/x86_64-linux-gnu/libomp.so.5+0x2a7be)
    #5 0x516f88 in main /home/mgigg/Code/git/martyngigg/sandbox/cpp/asan/omp/omp.cpp:4:11
    #6 0x7f3bdf11cb96 in __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310
    #7 0x41a629 in _start (/home/mgigg/Code/git/martyngigg/sandbox/cpp/asan/omp/omp+0x41a629)

Address 0x7ffe6e6a1480 is located in stack of thread T0 at offset 32 in frame
    #0 0x51702f in .omp_outlined._debug__ /home/mgigg/Code/git/martyngigg/sandbox/cpp/asan/omp/omp.cpp:5

  This frame has 6 object(s):
    [32, 36) 'i' (line 5) <== Memory access at offset 32 is inside this variable
    [48, 52) '.omp.lb' (line 4)
    [64, 68) '.omp.ub' (line 4)
    [80, 84) '.omp.stride' (line 4)
    [96, 100) '.omp.is_last' (line 4)
    [112, 136) '.kmpc_loc.addr'
HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-use-after-scope /home/mgigg/Code/git/martyngigg/sandbox/cpp/asan/omp/omp.cpp:5:36 in .omp_outlined._debug__
Shadow bytes around the buggy address:
  0x10004dccc240: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10004dccc250: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10004dccc260: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10004dccc270: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10004dccc280: ca ca ca ca 00 cb cb cb cb cb cb cb f1 f1 f1 f1
=>0x10004dccc290:[f8]f2 04 f2 04 f2 04 f2 04 f2 00 00 00 f3 f3 f3
  0x10004dccc2a0: f3 f3 f3 f3 00 00 00 00 00 00 00 00 00 00 00 00
  0x10004dccc2b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10004dccc2c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10004dccc2d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10004dccc2e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==13101==ABORTING
```

## System Details
OS: Ubuntu 18.04

$ clang++ --version
clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

**Comment by vitalybuka** [comment]
Very likely false positive. Probably "#pragma omp" somehow breaks lifetime markers.

**Comment by thejinx0r** [comment]
I have a similar issue on GCC 7.3, ubuntu / kubuntu 18.04, x86_64.

**Comment by xuchen-plus** [comment]
Encountered same issue on g++ 7.3.1,  centos 7.4.
